import type { Species } from './types';

/**
 * Thirty plants, each researched rather than invented.
 *
 * They are chosen to span the axes the simulation actually exercises, so that a
 * tester dragging the sliders sees genuinely different behaviour rather than
 * thirty variations on a green blob:
 *
 *   growth      eucalyptus (a metre a year) → pinus mugo (a few centimetres)
 *   persistence yew standing for centuries → cosmos, a different plant each year
 *   foliage     evergreen laurustinus → allium, gone from August to March
 *   season      hellebore in February → miscanthus plumes still up in January
 *   light       lavender demanding full sun → hosta and hellebore wanting shade
 *
 * Several exist to exercise a specific piece of the model, and it is worth
 * knowing which: magnolia flowers on bare wood, viburnum flowers across the turn
 * of the year, cornus is grown for the colour of its leafless stems, allium goes
 * dormant in high summer rather than in winter, and rowan and crab apple carry
 * fruit long after their leaves have gone.
 *
 * Dimensions and flowering periods are from the RHS entry for each plant (linked
 * in `source`); where nursery sources give a realistic 20-year size that differs
 * from the RHS "ultimate" figure, the growth curve is tuned to hit the 20-year
 * number, since that is the range the age slider covers.
 */

export const SPECIES: Species[] = [
  {
    id: 'betula-jacquemontii',
    common: 'West Himalayan birch',
    latin: 'Betula utilis var. jacquemontii',
    genus: 'Betula',
    family: 'Betulaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 3.0,
    plantedSpread: 1.2,
    matureHeight: 14,
    matureSpread: 6.5,
    yearsToMature: 32,
    budBurst: 95,
    fullLeaf: 125,
    autumnStart: 274,
    leafFall: 320,
    flowerStart: 85,
    flowerEnd: 112,
    colors: {
      leafSpring: '#a8c96b',
      leafSummer: '#5d8c47',
      leafAutumn: '#e3bb45',
      flower: '#c2bd6d',
      bark: '#f4f2ea',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'large',
    flowerColour: 'green-yellow catkins',
    foliageColour: 'mid green',
    notes:
      'Vigorous, with brilliant white bark on trunk and larger branches; clear yellow in autumn. Reaches roughly 10–12 m in twenty years, well over 12 m eventually. Casts light, dappled shade rather than dense.',
    source: 'https://www.rhs.org.uk/plants/94928/betula-utilis-var-jacquemontii/details',
  },
  {
    id: 'amelanchier-lamarckii',
    common: 'Snowy mespilus',
    latin: 'Amelanchier lamarckii',
    genus: 'Amelanchier',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'multistem',
    foliage: 'deciduous',
    plantedHeight: 2.2,
    plantedSpread: 1.0,
    matureHeight: 7,
    matureSpread: 5,
    yearsToMature: 45,
    budBurst: 90,
    fullLeaf: 118,
    autumnStart: 266,
    leafFall: 310,
    flowerStart: 96,
    flowerEnd: 118,
    colors: {
      leafSpring: '#b08a63',
      leafSummer: '#5f8f52',
      leafAutumn: '#d4562e',
      flower: '#fbf7f0',
      bark: '#6f5a4a',
    },
    sun: ['full', 'partial', 'dappled'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'white',
    foliageColour: 'mid green, bronze when young',
    notes:
      'Multi-stemmed small tree. A profusion of star-shaped white flowers in April with bronze-tinged young leaves, then orange to red autumn colour. About 4–5 m in twenty years despite a larger ultimate size. RHS Award of Garden Merit.',
    source: 'https://www.rhs.org.uk/plants/26602/amelanchier-lamarckii/details',
  },
  {
    id: 'acer-osakazuki',
    common: 'Japanese maple',
    latin: "Acer palmatum 'Ōsakazuki'",
    genus: 'Acer',
    family: 'Sapindaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 1.5,
    plantedSpread: 1.0,
    matureHeight: 6,
    matureSpread: 5,
    yearsToMature: 45,
    budBurst: 100,
    fullLeaf: 130,
    autumnStart: 272,
    leafFall: 318,
    flowerStart: 125,
    flowerEnd: 142,
    colors: {
      leafSpring: '#7fa055',
      leafSummer: '#4f7f3f',
      leafAutumn: '#d92b1f',
      flower: '#8c2f39',
      bark: '#7a6154',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'small red',
    foliageColour: 'green, scarlet in autumn',
    notes:
      'Large rounded deciduous shrub or small tree, about 4 × 3 m over twenty years. Seven-lobed leaves turn a brilliant orange-scarlet in autumn — among the most reliable of any Japanese maple. Wants shelter from cold wind and hot afternoon sun.',
    source: 'https://www.rhs.org.uk/plants/235/acer-palmatum-(elegans-group)-osakazuki-/details',
  },
  {
    id: 'taxus-baccata',
    common: 'Yew (clipped)',
    latin: 'Taxus baccata',
    genus: 'Taxus',
    family: 'Taxaceae',
    type: 'conifer',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.3,
    plantedHeight: 0.8,
    plantedSpread: 0.5,
    matureHeight: 2.0,
    matureSpread: 0.9,
    yearsToMature: 6,
    budBurst: 110,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 330,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#6f9c4e',
      leafSummer: '#28442c',
      leafAutumn: '#28442c',
      flower: '#c23b22',
      bark: '#8a6650',
    },
    sun: ['full', 'dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'none (red arils on female plants)',
    foliageColour: 'very dark green',
    notes:
      'The workhorse of formal structure. Clipped as a column or hedge it puts on 20–40 cm a year until it reaches the height it is being held at, then stays there. The darkest green in the palette, and it will take deep shade. All parts are toxic.',
    source: 'https://www.rhs.org.uk/plants/18025/taxus-baccata/details',
  },
  {
    id: 'hydrangea-limelight',
    common: 'Panicle hydrangea',
    latin: "Hydrangea paniculata 'Limelight'",
    genus: 'Hydrangea',
    family: 'Hydrangeaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    plantedHeight: 0.5,
    plantedSpread: 0.4,
    matureHeight: 2.2,
    matureSpread: 2.2,
    yearsToMature: 8,
    budBurst: 108,
    fullLeaf: 138,
    autumnStart: 280,
    leafFall: 320,
    flowerStart: 178,
    flowerEnd: 273,
    colors: {
      leafSpring: '#7fa356',
      leafSummer: '#4a7a3c',
      leafAutumn: '#c9b95f',
      flower: '#e2edbb',
      flowerLate: '#d8a3ac',
      bark: '#7d6a58',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'lime to cream to pink',
    foliageColour: 'mid green',
    notes:
      'Upright deciduous shrub reaching full size in five to ten years. Big conical heads open pale lime from late June, fade through creamy white, then flush pink into autumn — so the flower colour changes as you move the season slider, not just its presence.',
    source: 'https://www.rhs.org.uk/plants/154246/hydrangea-paniculata-limelight/details',
  },
  {
    id: 'lavandula-hidcote',
    common: 'English lavender',
    latin: "Lavandula angustifolia 'Hidcote'",
    genus: 'Lavandula',
    family: 'Lamiaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.25,
    plantedSpread: 0.25,
    matureHeight: 0.6,
    matureSpread: 0.75,
    yearsToMature: 4,
    budBurst: 95,
    fullLeaf: 130,
    autumnStart: 290,
    leafFall: 330,
    flowerStart: 160,
    flowerEnd: 250,
    colors: {
      leafSpring: '#a8b294',
      leafSummer: '#8f9a7e',
      leafAutumn: '#8f9a7e',
      flower: '#5d4a9c',
      bark: '#8a7d68',
    },
    sun: ['full'],
    soilPh: ['neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'deep violet',
    foliageColour: 'silver-grey',
    notes:
      'Bushy dwarf evergreen shrub, 60 × 75 cm, with narrow silvery-grey leaves and deep violet-purple flower spikes from June. Needs full sun and sharp drainage — the one plant here that will sulk anywhere shaded.',
    source: 'https://www.rhs.org.uk/plants/96353/lavandula-angustifolia-hidcote/details',
  },
  {
    id: 'calamagrostis-karl-foerster',
    common: 'Feather reed grass',
    latin: "Calamagrostis × acutiflora 'Karl Foerster'",
    genus: 'Calamagrostis',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    standing: { from: 250, to: 70 },
    plantedHeight: 0.4,
    plantedSpread: 0.3,
    matureHeight: 1.7,
    matureSpread: 0.6,
    yearsToMature: 3,
    budBurst: 78,
    fullLeaf: 132,
    autumnStart: 250,
    leafFall: 330,
    flowerStart: 175,
    flowerEnd: 232,
    colors: {
      leafSpring: '#7fa354',
      leafSummer: '#4f7d42',
      leafAutumn: '#c2a35f',
      flower: '#e8d9b0',
      flowerLate: '#c9a961',
      bark: '#b39a66',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive', 'waterlogged'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'creamy pink ageing to gold',
    foliageColour: 'deep green',
    notes:
      'Stiffly upright clump about 60 cm of foliage with flower stems to 1.7 m. Flowers open creamy white tinged pink in midsummer and age to narrow golden plumes that stand right through winter until they are cut back in February — the only thing in this palette with real January structure.',
    source: 'https://www.rhs.org.uk/plants/72074/calamagrostis-x-acutiflora-karl-foerster/details',
  },
  {
    id: 'hosta-halcyon',
    common: 'Plantain lily',
    latin: "Hosta (Tardiana Group) 'Halcyon'",
    genus: 'Hosta',
    family: 'Asparagaceae',
    type: 'perennial',
    habit: 'clump',
    foliage: 'herbaceous',
    plantedHeight: 0.2,
    plantedSpread: 0.25,
    matureHeight: 0.45,
    matureSpread: 0.9,
    yearsToMature: 5,
    budBurst: 105,
    fullLeaf: 142,
    autumnStart: 258,
    leafFall: 300,
    flowerStart: 190,
    flowerEnd: 226,
    colors: {
      leafSpring: '#8fb0b0',
      leafSummer: '#7593a0',
      leafAutumn: '#d3c26b',
      flower: '#c2bad8',
      bark: '#7593a0',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive', 'waterlogged'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'pale lavender-grey',
    foliageColour: 'intense blue',
    notes:
      'Dense mound of smooth, spear-shaped intensely blue leaves, about 45 cm tall by 90 cm across. Dies back completely — from November to April there is nothing above ground at all, which is worth seeing on the season slider. Best in shade, where the blue holds.',
    source: 'https://www.rhs.org.uk/plants/78423/hosta-halcyon/details',
  },
  {
    id: 'verbena-bonariensis',
    common: 'Purple top',
    latin: 'Verbena bonariensis',
    genus: 'Verbena',
    family: 'Verbenaceae',
    type: 'perennial',
    habit: 'airy',
    foliage: 'herbaceous',
    standing: { from: 300, to: 70 },
    plantedHeight: 0.5,
    plantedSpread: 0.3,
    matureHeight: 1.3,
    matureSpread: 0.6,
    yearsToMature: 2,
    budBurst: 95,
    fullLeaf: 155,
    autumnStart: 285,
    leafFall: 325,
    flowerStart: 185,
    flowerEnd: 292,
    colors: {
      leafSpring: '#6f8f4f',
      leafSummer: '#54763f',
      leafAutumn: '#9c8a5a',
      flower: '#8f5fa8',
      bark: '#6b7a52',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'lilac-purple',
    foliageColour: 'sparse deep green',
    notes:
      'Tall and see-through: 1.2 m of bare wiry stems topped with small lilac-purple flowerheads from July to the first frosts. Designers plant it in front of things precisely because you look through it. Short-lived but self-seeds freely. RHS Award of Garden Merit.',
    source: 'https://www.rhs.org.uk/plants/42079/verbena-bonariensis/details',
  },
  {
    id: 'geranium-rozanne',
    common: 'Cranesbill',
    latin: "Geranium Rozanne ('Gerwat')",
    genus: 'Geranium',
    family: 'Geraniaceae',
    type: 'perennial',
    habit: 'clump',
    foliage: 'herbaceous',
    plantedHeight: 0.2,
    plantedSpread: 0.3,
    matureHeight: 0.45,
    matureSpread: 1.1,
    yearsToMature: 3,
    budBurst: 90,
    fullLeaf: 140,
    autumnStart: 278,
    leafFall: 312,
    flowerStart: 152,
    flowerEnd: 300,
    colors: {
      leafSpring: '#7fa855',
      leafSummer: '#5b8442',
      leafAutumn: '#c96b3f',
      flower: '#4a6fc4',
      bark: '#5b8442',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'violet-blue',
    foliageColour: 'mid green',
    notes:
      'Sprawling groundcover to about a metre across, smothered in violet-blue white-centred flowers from June until the frosts — one of the longest flowering seasons of any hardy perennial. Useful for reading the season slider, since it is in flower across most of it.',
    source: 'https://www.rhs.org.uk/plants/153768/geranium-rozanne-gerwat-pbr/details',
  },
  {
    id: 'eucalyptus-gunnii',
    common: 'Cider gum',
    latin: 'Eucalyptus gunnii',
    genus: 'Eucalyptus',
    family: 'Myrtaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'evergreen',
    plantedHeight: 2.0,
    plantedSpread: 0.8,
    matureHeight: 18,
    matureSpread: 7,
    yearsToMature: 30,
    budBurst: 100,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 340,
    flowerStart: 190,
    flowerEnd: 262,
    colors: {
      leafSpring: '#b3c4b6',
      leafSummer: '#8fa89a',
      leafAutumn: '#8fa89a',
      flower: '#eef0e2',
      bark: '#cbc0b0',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'large',
    flowerColour: 'creamy white',
    foliageColour: 'silver blue-grey',
    notes:
      'By some distance the fastest thing here — a metre or more a year while young, and 15 m within twenty years if left alone. Rounded silver-blue juvenile leaves give way to longer grey-green adult ones unless you coppice it hard each spring to keep the juvenile foliage. Evergreen, so it shades in winter too.',
    source: 'https://www.rhs.org.uk/plants/7141/eucalyptus-gunnii/details',
  },
  {
    id: 'magnolia-soulangeana',
    common: 'Saucer magnolia',
    latin: 'Magnolia × soulangeana',
    genus: 'Magnolia',
    family: 'Magnoliaceae',
    type: 'tree',
    habit: 'multistem',
    foliage: 'deciduous',
    plantedHeight: 1.8,
    plantedSpread: 1.2,
    matureHeight: 7,
    matureSpread: 7,
    yearsToMature: 40,
    budBurst: 118,
    fullLeaf: 148,
    autumnStart: 275,
    leafFall: 315,
    flowerStart: 78,
    flowerEnd: 116,
    flowersOnBareWood: true,
    colors: {
      leafSpring: '#6f8f52',
      leafSummer: '#4e7a45',
      leafAutumn: '#c9b46a',
      flower: '#f4e2ea',
      flowerLate: '#e2b6c8',
      bark: '#8a8378',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'white flushed pink-purple',
    foliageColour: 'mid green',
    notes:
      'Big goblet flowers open on completely bare branches in March and April, weeks before a leaf shows — the reason it is worth the space. Wide-spreading and slow, roughly as broad as it is tall. Late frosts brown the flowers, so it wants shelter.',
    source: 'https://www.rhs.org.uk/plants/11116/magnolia-x-soulangeana/details',
  },
  {
    id: 'malus-evereste',
    common: 'Crab apple',
    latin: "Malus 'Evereste'",
    genus: 'Malus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.0,
    plantedSpread: 1.0,
    matureHeight: 7,
    matureSpread: 6,
    yearsToMature: 35,
    budBurst: 98,
    fullLeaf: 128,
    autumnStart: 272,
    leafFall: 315,
    flowerStart: 112,
    flowerEnd: 142,
    fruitStart: 240,
    fruitEnd: 358,
    colors: {
      leafSpring: '#7fa356',
      leafSummer: '#4f7c40',
      leafAutumn: '#d1a03e',
      flower: '#faf0ea',
      flowerLate: '#f2d6da',
      fruit: '#d9541f',
      bark: '#6f5f4e',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'red buds opening white',
    foliageColour: 'mid green',
    notes:
      'Conical small tree that earns its place twice: red-budded white blossom in late April, then orange-red fruit from September that hangs on well past leaf fall. Reliable and disease-resistant. RHS Award of Garden Merit.',
    source: 'https://www.rhs.org.uk/plants/58567/malus-evereste/details',
  },
  {
    id: 'prunus-serrula',
    common: 'Tibetan cherry',
    latin: 'Prunus serrula',
    genus: 'Prunus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.5,
    plantedSpread: 1.2,
    matureHeight: 9,
    matureSpread: 8,
    yearsToMature: 35,
    budBurst: 100,
    fullLeaf: 128,
    autumnStart: 268,
    leafFall: 312,
    flowerStart: 108,
    flowerEnd: 130,
    colors: {
      leafSpring: '#7fa356',
      leafSummer: '#4a7440',
      leafAutumn: '#d3a747',
      flower: '#fbf6f2',
      bark: '#8c3a20',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'small white',
    foliageColour: 'mid green, yellow in autumn',
    notes:
      'Grown for its bark: a glossy mahogany-red trunk that peels in bands and looks polished, at its best in winter when there is nothing else to look at. The white blossom is modest by cherry standards. Lift the crown so the trunk shows.',
    source: 'https://www.rhs.org.uk/plants/13584/prunus-serrula/details',
  },
  {
    id: 'sorbus-aucuparia',
    common: 'Rowan',
    latin: 'Sorbus aucuparia',
    genus: 'Sorbus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.5,
    plantedSpread: 1.0,
    matureHeight: 12,
    matureSpread: 7,
    yearsToMature: 30,
    budBurst: 96,
    fullLeaf: 124,
    autumnStart: 262,
    leafFall: 305,
    flowerStart: 130,
    flowerEnd: 156,
    fruitStart: 215,
    fruitEnd: 320,
    colors: {
      leafSpring: '#8fb05e',
      leafSummer: '#4f7844',
      leafAutumn: '#d4552e',
      flower: '#f6f2e6',
      fruit: '#d93b1c',
      bark: '#8a8a80',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'large',
    flowerColour: 'creamy white',
    foliageColour: 'fine pinnate green',
    notes:
      'Light, airy and upright, with fine pinnate leaves that cast much less shade than the canopy size suggests. Flat heads of cream flowers in May, then heavy bunches of orange-red berries from August — usually stripped by blackbirds well before Christmas.',
    source: 'https://www.rhs.org.uk/plants/17368/sorbus-aucuparia/details',
  },
  {
    id: 'leptospermum-scoparium',
    common: 'Mānuka',
    latin: 'Leptospermum scoparium',
    genus: 'Leptospermum',
    family: 'Myrtaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.4,
    plantedSpread: 0.35,
    matureHeight: 2.0,
    matureSpread: 1.6,
    yearsToMature: 8,
    budBurst: 105,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 340,
    flowerStart: 132,
    flowerEnd: 192,
    colors: {
      leafSpring: '#6f7f52',
      leafSummer: '#4a5c3f',
      leafAutumn: '#4a5c3f',
      flower: '#e089a6',
      bark: '#7a6250',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['loam', 'sand'],
    drainage: ['free'],
    hardiness: 'H3',
    sizeClass: 'small',
    flowerColour: 'pink',
    foliageColour: 'fine dark green',
    notes:
      'Dense, fine-textured evergreen smothered in small flat flowers in late spring. The least hardy plant here — H3 means it needs a sheltered, sunny, well-drained spot and will not survive a hard winter inland. Worth the risk in a mild coastal garden.',
    source: 'https://www.rhs.org.uk/plants/10038/leptospermum-scoparium/details',
  },
  {
    id: 'cornus-midwinter-fire',
    common: 'Dogwood',
    latin: "Cornus sanguinea 'Midwinter Fire'",
    genus: 'Cornus',
    family: 'Cornaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    plantedHeight: 0.5,
    plantedSpread: 0.5,
    matureHeight: 2.0,
    matureSpread: 2.5,
    yearsToMature: 7,
    budBurst: 105,
    fullLeaf: 138,
    autumnStart: 268,
    leafFall: 305,
    flowerStart: 145,
    flowerEnd: 172,
    colors: {
      leafSpring: '#84a85e',
      leafSummer: '#5b8248',
      leafAutumn: '#e0a63c',
      flower: '#f4f0e4',
      bark: '#e2622a',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive', 'waterlogged'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'small creamy white',
    foliageColour: 'mid green, butter yellow in autumn',
    notes:
      'The one plant here that is at its best with no leaves on it. Bare young stems run from yellow through orange to red, so a group lights up from November to March — then you cut a third of it hard back in early spring to keep the new wood coming.',
    source: 'https://www.rhs.org.uk/plants/97993/cornus-sanguinea-midwinter-fire/details',
  },
  {
    id: 'viburnum-tinus',
    common: 'Laurustinus',
    latin: 'Viburnum tinus',
    genus: 'Viburnum',
    family: 'Adoxaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.6,
    plantedSpread: 0.5,
    matureHeight: 3.0,
    matureSpread: 3.0,
    yearsToMature: 10,
    budBurst: 110,
    fullLeaf: 150,
    autumnStart: 300,
    leafFall: 340,
    flowerStart: 305,
    flowerEnd: 110,
    fruitStart: 150,
    fruitEnd: 250,
    colors: {
      leafSpring: '#5c8a52',
      leafSummer: '#2f5138',
      leafAutumn: '#2f5138',
      flower: '#f4ece8',
      flowerLate: '#f7f2ef',
      fruit: '#2b3a5c',
      bark: '#6b6255',
    },
    sun: ['full', 'dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'pink buds opening white',
    foliageColour: 'dark green',
    notes:
      'Flowers right through the winter — pink buds opening white from November to April, when almost nothing else is out — then metallic blue-black berries in summer. Dense, evergreen, takes shade and clipping. Unglamorous and extremely useful.',
    source: 'https://www.rhs.org.uk/plants/18627/viburnum-tinus/details',
  },
  {
    id: 'rosa-gertrude-jekyll',
    common: 'English shrub rose',
    latin: "Rosa Gertrude Jekyll ('Ausbord')",
    genus: 'Rosa',
    family: 'Rosaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    plantedHeight: 0.5,
    plantedSpread: 0.4,
    matureHeight: 1.5,
    matureSpread: 1.2,
    yearsToMature: 5,
    budBurst: 100,
    fullLeaf: 138,
    autumnStart: 280,
    leafFall: 322,
    flowerStart: 150,
    flowerEnd: 292,
    fruitStart: 288,
    fruitEnd: 345,
    colors: {
      leafSpring: '#6f8f4a',
      leafSummer: '#3f6b3a',
      leafAutumn: '#c9a24a',
      flower: '#e0839c',
      flowerLate: '#e8a8b8',
      fruit: '#b8302a',
      bark: '#6b5a44',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'rich pink',
    foliageColour: 'mid green',
    notes:
      'Repeat-flowering from June until the frosts, with the strongest old-rose scent of any modern shrub rose, then hips if you stop deadheading in autumn. Wants feeding and an open position; it goes bare and twiggy in winter and is not trying to hide it.',
    source: 'https://www.rhs.org.uk/plants/95996/rosa-gertrude-jekyll-ausbord-(s)/details',
  },
  {
    id: 'choisya-sundance',
    common: 'Mexican orange blossom',
    latin: "Choisya ternata 'Sundance'",
    genus: 'Choisya',
    family: 'Rutaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.5,
    plantedSpread: 0.5,
    matureHeight: 2.2,
    matureSpread: 2.2,
    yearsToMature: 8,
    budBurst: 105,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 340,
    flowerStart: 122,
    flowerEnd: 165,
    colors: {
      leafSpring: '#dfe574',
      leafSummer: '#c2c94f',
      leafAutumn: '#c2c94f',
      flower: '#fbf8f2',
      bark: '#7d7052',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'white, strongly scented',
    foliageColour: 'bright gold',
    notes:
      'A rounded evergreen dome of aromatic gold foliage that holds its colour all winter and lifts a dull corner, with scented white flowers in May. The gold scorches in full midday sun and goes lime in deep shade, so it wants somewhere in between.',
    source: 'https://www.rhs.org.uk/plants/3641/choisya-ternata-sundance-(v)/details',
  },
  {
    id: 'pinus-mugo',
    common: 'Dwarf mountain pine',
    latin: "Pinus mugo 'Mughus'",
    genus: 'Pinus',
    family: 'Pinaceae',
    type: 'conifer',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.4,
    plantedSpread: 0.5,
    matureHeight: 2.0,
    matureSpread: 3.0,
    yearsToMature: 22,
    budBurst: 120,
    fullLeaf: 168,
    autumnStart: 300,
    leafFall: 340,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#5c7a48',
      leafSummer: '#2f4a35',
      leafAutumn: '#2f4a35',
      flower: '#8a7d5a',
      bark: '#6b5a4a',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'none',
    foliageColour: 'dark green',
    notes:
      'Slow, tough and completely hardy — a low spreading dome of dark needles that eventually goes wider than it is tall. Useful evergreen weight at ground level where a yew would be too formal. The pale candles of new growth in May are worth watching for.',
    source: 'https://www.rhs.org.uk/plants/12784/pinus-mugo-mughus/details',
  },
  {
    id: 'stipa-gigantea',
    common: 'Giant oat grass',
    latin: 'Stipa gigantea',
    genus: 'Stipa',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'evergreen',
    standing: { from: 195, to: 40 },
    plantedHeight: 0.5,
    plantedSpread: 0.5,
    matureHeight: 2.4,
    matureSpread: 1.2,
    yearsToMature: 5,
    budBurst: 90,
    fullLeaf: 140,
    autumnStart: 300,
    leafFall: 340,
    flowerStart: 158,
    flowerEnd: 212,
    colors: {
      leafSpring: '#7fa354',
      leafSummer: '#5c7a49',
      leafAutumn: '#c9a961',
      flower: '#e8dcb8',
      flowerLate: '#d6b56a',
      bark: '#b39a66',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'silvery gold oats',
    foliageColour: 'evergreen mid green',
    notes:
      'An evergreen knee-high clump that throws 2 m stems of golden oat panicles in June and holds them, catching low light, until they are cut in late winter. Transparent enough to plant in front of things. RHS Award of Garden Merit.',
    source: 'https://www.rhs.org.uk/plants/17827/stipa-gigantea/details',
  },
  {
    id: 'miscanthus-gracillimus',
    common: 'Maiden grass',
    latin: "Miscanthus sinensis 'Gracillimus'",
    genus: 'Miscanthus',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    standing: { from: 265, to: 70 },
    plantedHeight: 0.6,
    plantedSpread: 0.4,
    matureHeight: 1.8,
    matureSpread: 1.2,
    yearsToMature: 4,
    budBurst: 108,
    fullLeaf: 162,
    autumnStart: 265,
    leafFall: 340,
    flowerStart: 248,
    flowerEnd: 302,
    colors: {
      leafSpring: '#7fa354',
      leafSummer: '#5f8248',
      leafAutumn: '#c9a05a',
      flower: '#e6dcd2',
      flowerLate: '#d8c4b0',
      bark: '#b39a66',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive', 'waterlogged'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'silvery bronze plumes',
    foliageColour: 'fine arching green',
    notes:
      'Narrow arching leaves with a white midrib, in a fountain about 1.5 m across, topped with silvery plumes very late — often not until late September. Everything goes buff and stands right through winter until a February cut-back.',
    source: 'https://www.rhs.org.uk/plants/11431/miscanthus-sinensis-gracillimus/details',
  },
  {
    id: 'salvia-caradonna',
    common: 'Balkan clary',
    latin: "Salvia nemorosa 'Caradonna'",
    genus: 'Salvia',
    family: 'Lamiaceae',
    type: 'perennial',
    habit: 'tussock',
    foliage: 'herbaceous',
    plantedHeight: 0.25,
    plantedSpread: 0.25,
    matureHeight: 0.6,
    matureSpread: 0.45,
    yearsToMature: 3,
    budBurst: 95,
    fullLeaf: 140,
    autumnStart: 270,
    leafFall: 310,
    flowerStart: 148,
    flowerEnd: 205,
    colors: {
      leafSpring: '#6f8f52',
      leafSummer: '#4f6b42',
      leafAutumn: '#a08a5a',
      flower: '#4a2d7a',
      bark: '#3a2f4a',
    },
    sun: ['full'],
    soilPh: ['neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'deep violet on black stems',
    foliageColour: 'mid green',
    notes:
      'Narrow spikes of very dark violet held on near-black stems from June, which is what separates it from the rest of the nemorosa salvias. Cut it back after the first flush and it will come again in late summer. Needs sun and sharp drainage.',
    source: 'https://www.rhs.org.uk/plants/98550/salvia-nemorosa-caradonna/details',
  },
  {
    id: 'echinacea-purpurea',
    common: 'Coneflower',
    latin: 'Echinacea purpurea',
    genus: 'Echinacea',
    family: 'Asteraceae',
    type: 'perennial',
    habit: 'airy',
    foliage: 'herbaceous',
    standing: { from: 268, to: 60 },
    plantedHeight: 0.3,
    plantedSpread: 0.3,
    matureHeight: 1.0,
    matureSpread: 0.5,
    yearsToMature: 3,
    budBurst: 100,
    fullLeaf: 150,
    autumnStart: 275,
    leafFall: 315,
    flowerStart: 190,
    flowerEnd: 268,
    colors: {
      leafSpring: '#6f8f4a',
      leafSummer: '#496b3d',
      leafAutumn: '#8a7a52',
      flower: '#c4708f',
      flowerLate: '#b8869a',
      bark: '#5c6b45',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'purple-pink with an orange cone',
    foliageColour: 'coarse dark green',
    notes:
      'Stiff upright stems with big daisies from July to September, and then the reason to grow it: hard black cones that stand all winter and look superb frosted. Leave them up until February. Wants sun and soil that does not sit wet.',
    source: 'https://www.rhs.org.uk/plants/6039/echinacea-purpurea/details',
  },
  {
    id: 'alchemilla-mollis',
    common: "Lady's mantle",
    latin: 'Alchemilla mollis',
    genus: 'Alchemilla',
    family: 'Rosaceae',
    type: 'perennial',
    habit: 'clump',
    foliage: 'herbaceous',
    plantedHeight: 0.2,
    plantedSpread: 0.25,
    matureHeight: 0.5,
    matureSpread: 0.75,
    yearsToMature: 3,
    budBurst: 88,
    fullLeaf: 130,
    autumnStart: 270,
    leafFall: 305,
    flowerStart: 158,
    flowerEnd: 218,
    colors: {
      leafSpring: '#8fa86e',
      leafSummer: '#6f8f5a',
      leafAutumn: '#c2a862',
      flower: '#c8d46a',
      bark: '#6f8f5a',
    },
    sun: ['full', 'dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive', 'waterlogged'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'lime green froth',
    foliageColour: 'soft grey-green',
    notes:
      'Pleated soft leaves that hold beads of rain, under a long-lasting froth of tiny lime-green flowers from June. The classic softener for a path edge or the front of a border. Seeds itself everywhere unless you cut it back after flowering.',
    source: 'https://www.rhs.org.uk/plants/300/alchemilla-mollis/details',
  },
  {
    id: 'rudbeckia-goldsturm',
    common: 'Black-eyed Susan',
    latin: "Rudbeckia fulgida var. sullivantii 'Goldsturm'",
    genus: 'Rudbeckia',
    family: 'Asteraceae',
    type: 'perennial',
    habit: 'airy',
    foliage: 'herbaceous',
    standing: { from: 285, to: 60 },
    plantedHeight: 0.3,
    plantedSpread: 0.3,
    matureHeight: 0.7,
    matureSpread: 0.5,
    yearsToMature: 3,
    budBurst: 100,
    fullLeaf: 150,
    autumnStart: 280,
    leafFall: 315,
    flowerStart: 212,
    flowerEnd: 288,
    colors: {
      leafSpring: '#5f8248',
      leafSummer: '#3f6437',
      leafAutumn: '#8a7440',
      flower: '#e8b52a',
      flowerLate: '#d99a26',
      bark: '#4f6b3f',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive', 'waterlogged'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'deep gold with a black centre',
    foliageColour: 'dark green',
    notes:
      'Sheets of gold daisies from August into October, which is exactly when a border needs them, followed by dark seed cones that stand into winter. Spreads steadily at the root. Reliable to the point of being a cliché, and still worth it.',
    source: 'https://www.rhs.org.uk/plants/16311/rudbeckia-fulgida-var-sullivantii-goldsturm/details',
  },
  {
    id: 'helleborus-hybridus',
    common: 'Lenten rose',
    latin: 'Helleborus × hybridus',
    genus: 'Helleborus',
    family: 'Ranunculaceae',
    type: 'perennial',
    habit: 'clump',
    foliage: 'evergreen',
    plantedHeight: 0.25,
    plantedSpread: 0.3,
    matureHeight: 0.45,
    matureSpread: 0.6,
    yearsToMature: 4,
    budBurst: 62,
    fullLeaf: 120,
    autumnStart: 300,
    leafFall: 340,
    flowerStart: 35,
    flowerEnd: 112,
    colors: {
      leafSpring: '#547046',
      leafSummer: '#2f4f33',
      leafAutumn: '#2f4f33',
      flower: '#c9a8bd',
      flowerLate: '#a8a086',
      bark: '#3f5c3a',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'dusky pink ageing to green',
    foliageColour: 'leathery dark green',
    notes:
      'Nodding flowers from February to April, when the garden has almost nothing else, ageing quietly to green rather than dropping. Leathery evergreen leaves — cut the old ones off in January so you can see the flowers. Happiest in shade under deciduous trees.',
    source: 'https://www.rhs.org.uk/plants/79139/helleborus-x-hybridus/details',
  },
  {
    id: 'allium-purple-sensation',
    common: 'Ornamental onion',
    latin: "Allium hollandicum 'Purple Sensation'",
    genus: 'Allium',
    family: 'Amaryllidaceae',
    type: 'perennial',
    habit: 'globe',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    standing: { from: 165, to: 250 },
    plantedHeight: 0.5,
    plantedSpread: 0.12,
    matureHeight: 0.9,
    matureSpread: 0.15,
    yearsToMature: 3,
    budBurst: 55,
    fullLeaf: 100,
    autumnStart: 140,
    leafFall: 175,
    flowerStart: 128,
    flowerEnd: 166,
    colors: {
      leafSpring: '#7fa86a',
      leafSummer: '#5f8a5c',
      leafAutumn: '#b3a06a',
      flower: '#6b3f96',
      flowerLate: '#8f6ba8',
      bark: '#7f9a63',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'deep purple',
    foliageColour: 'strappy green, dies back early',
    notes:
      'Dense purple spheres on bare 90 cm stems in May. The strappy leaves yellow and collapse just as the flowers open, so plant it through something that will cover the mess. Leave the seedheads — they stand handsomely until midsummer, then go. Nothing above ground from August until March.',
    source: 'https://www.rhs.org.uk/plants/91576/allium-hollandicum-purple-sensation/details',
  },
  {
    id: 'cosmos-bipinnatus',
    common: 'Cosmos',
    latin: "Cosmos bipinnatus 'Sonata'",
    genus: 'Cosmos',
    family: 'Asteraceae',
    type: 'annual',
    habit: 'airy',
    foliage: 'herbaceous',
    lifecycle: 'annual',
    plantedHeight: 0.9,
    plantedSpread: 0.42,
    matureHeight: 1.1,
    matureSpread: 0.45,
    yearsToMature: 2,
    budBurst: 150,
    fullLeaf: 196,
    autumnStart: 292,
    leafFall: 302,
    flowerStart: 190,
    flowerEnd: 300,
    colors: {
      leafSpring: '#7fa86a',
      leafSummer: '#5f8a55',
      leafAutumn: '#8a8a5a',
      flower: '#e88fb0',
      flowerLate: '#f4e0e8',
      bark: '#5f8a55',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H2',
    sizeClass: 'medium',
    flowerColour: 'pink, rose and white',
    foliageColour: 'feathery bright green',
    notes:
      'A half-hardy annual, so the age slider does nothing to it — this is a different plant every year, sown in spring, planted out once the frosts are past and killed outright by the first hard one. Feathery foliage and open saucer flowers from July until it goes. Deadhead and it will not stop.',
    source: 'https://www.rhs.org.uk/plants/70959/cosmos-bipinnatus-sonata-series/details',
  },
];

export const SPECIES_BY_ID: Record<string, Species> = Object.fromEntries(
  SPECIES.map((s) => [s.id, s]),
);

export function getSpecies(id: string): Species {
  const s = SPECIES_BY_ID[id];
  if (!s) throw new Error(`Unknown species: ${id}`);
  return s;
}

export const TYPE_LABELS: Record<Species['type'], string> = {
  tree: 'Trees',
  shrub: 'Shrubs',
  conifer: 'Conifers',
  grass: 'Grasses',
  perennial: 'Perennials',
  annual: 'Annuals',
};
