import type { Species } from './types';

/**
 * A deliberately small palette — ten plants, each researched properly.
 *
 * They are chosen to span the axes the simulation actually exercises, so that a
 * tester dragging the sliders sees genuinely different behaviour rather than ten
 * variations on a green blob:
 *
 *   growth      birch (vigorous, 30+ years) → verbena (full size in two seasons)
 *   foliage     yew and lavender evergreen → hosta vanishing underground each winter
 *   season      amelanchier's April blossom → calamagrostis seedheads standing in January
 *   light       lavender needing full sun → hosta happiest in shade
 *
 * Dimensions and flowering periods are from the RHS entry for each plant (linked
 * in `source`); where nursery sources give a realistic 20-year size that differs
 * from the RHS "ultimate" figure, the growth curve is tuned to hit the 20-year
 * number, since that is the range the age slider covers.
 */

export const SPECIES: Species[] = [
  {
    id: 'betula-jacquemontii',
    common: 'West Himalayan birch',
    latin: 'Betula utilis var. jacquemontii',
    genus: 'Betula',
    family: 'Betulaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 3.0,
    plantedSpread: 1.2,
    matureHeight: 14,
    matureSpread: 6.5,
    yearsToMature: 32,
    budBurst: 95,
    fullLeaf: 125,
    autumnStart: 274,
    leafFall: 320,
    flowerStart: 85,
    flowerEnd: 112,
    colors: {
      leafSpring: '#a8c96b',
      leafSummer: '#5d8c47',
      leafAutumn: '#e3bb45',
      flower: '#c2bd6d',
      bark: '#f4f2ea',
    },
    sun: ['full', 'partial'],
    hardiness: 'H7',
    sizeClass: 'large',
    flowerColour: 'green-yellow catkins',
    foliageColour: 'mid green',
    notes:
      'Vigorous, with brilliant white bark on trunk and larger branches; clear yellow in autumn. Reaches roughly 10–12 m in twenty years, well over 12 m eventually. Casts light, dappled shade rather than dense.',
    source: 'https://www.rhs.org.uk/plants/94928/betula-utilis-var-jacquemontii/details',
  },
  {
    id: 'amelanchier-lamarckii',
    common: 'Snowy mespilus',
    latin: 'Amelanchier lamarckii',
    genus: 'Amelanchier',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'multistem',
    foliage: 'deciduous',
    plantedHeight: 2.2,
    plantedSpread: 1.0,
    matureHeight: 7,
    matureSpread: 5,
    yearsToMature: 45,
    budBurst: 90,
    fullLeaf: 118,
    autumnStart: 266,
    leafFall: 310,
    flowerStart: 96,
    flowerEnd: 118,
    colors: {
      leafSpring: '#b08a63',
      leafSummer: '#5f8f52',
      leafAutumn: '#d4562e',
      flower: '#fbf7f0',
      bark: '#6f5a4a',
    },
    sun: ['full', 'partial'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'white',
    foliageColour: 'mid green, bronze when young',
    notes:
      'Multi-stemmed small tree. A profusion of star-shaped white flowers in April with bronze-tinged young leaves, then orange to red autumn colour. About 4–5 m in twenty years despite a larger ultimate size. RHS Award of Garden Merit.',
    source: 'https://www.rhs.org.uk/plants/26602/amelanchier-lamarckii/details',
  },
  {
    id: 'acer-osakazuki',
    common: 'Japanese maple',
    latin: "Acer palmatum 'Ōsakazuki'",
    genus: 'Acer',
    family: 'Sapindaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 1.5,
    plantedSpread: 1.0,
    matureHeight: 6,
    matureSpread: 5,
    yearsToMature: 45,
    budBurst: 100,
    fullLeaf: 130,
    autumnStart: 272,
    leafFall: 318,
    flowerStart: 125,
    flowerEnd: 142,
    colors: {
      leafSpring: '#7fa055',
      leafSummer: '#4f7f3f',
      leafAutumn: '#d92b1f',
      flower: '#8c2f39',
      bark: '#7a6154',
    },
    sun: ['partial', 'shade'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'small red',
    foliageColour: 'green, scarlet in autumn',
    notes:
      'Large rounded deciduous shrub or small tree, about 4 × 3 m over twenty years. Seven-lobed leaves turn a brilliant orange-scarlet in autumn — among the most reliable of any Japanese maple. Wants shelter from cold wind and hot afternoon sun.',
    source: 'https://www.rhs.org.uk/plants/235/acer-palmatum-(elegans-group)-osakazuki-/details',
  },
  {
    id: 'taxus-baccata',
    common: 'Yew (clipped)',
    latin: 'Taxus baccata',
    genus: 'Taxus',
    family: 'Taxaceae',
    type: 'conifer',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.3,
    plantedHeight: 0.8,
    plantedSpread: 0.5,
    matureHeight: 2.0,
    matureSpread: 0.9,
    yearsToMature: 6,
    budBurst: 110,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 330,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#6f9c4e',
      leafSummer: '#28442c',
      leafAutumn: '#28442c',
      flower: '#c23b22',
      bark: '#8a6650',
    },
    sun: ['full', 'partial', 'shade'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'none (red arils on female plants)',
    foliageColour: 'very dark green',
    notes:
      'The workhorse of formal structure. Clipped as a column or hedge it puts on 20–40 cm a year until it reaches the height it is being held at, then stays there. The darkest green in the palette, and it will take deep shade. All parts are toxic.',
    source: 'https://www.rhs.org.uk/plants/18025/taxus-baccata/details',
  },
  {
    id: 'hydrangea-limelight',
    common: 'Panicle hydrangea',
    latin: "Hydrangea paniculata 'Limelight'",
    genus: 'Hydrangea',
    family: 'Hydrangeaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    plantedHeight: 0.5,
    plantedSpread: 0.4,
    matureHeight: 2.2,
    matureSpread: 2.2,
    yearsToMature: 8,
    budBurst: 108,
    fullLeaf: 138,
    autumnStart: 280,
    leafFall: 320,
    flowerStart: 178,
    flowerEnd: 273,
    colors: {
      leafSpring: '#7fa356',
      leafSummer: '#4a7a3c',
      leafAutumn: '#c9b95f',
      flower: '#e2edbb',
      flowerLate: '#d8a3ac',
      bark: '#7d6a58',
    },
    sun: ['full', 'partial'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'lime to cream to pink',
    foliageColour: 'mid green',
    notes:
      'Upright deciduous shrub reaching full size in five to ten years. Big conical heads open pale lime from late June, fade through creamy white, then flush pink into autumn — so the flower colour changes as you move the season slider, not just its presence.',
    source: 'https://www.rhs.org.uk/plants/154246/hydrangea-paniculata-limelight/details',
  },
  {
    id: 'lavandula-hidcote',
    common: 'English lavender',
    latin: "Lavandula angustifolia 'Hidcote'",
    genus: 'Lavandula',
    family: 'Lamiaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.25,
    plantedSpread: 0.25,
    matureHeight: 0.6,
    matureSpread: 0.75,
    yearsToMature: 4,
    budBurst: 95,
    fullLeaf: 130,
    autumnStart: 290,
    leafFall: 330,
    flowerStart: 160,
    flowerEnd: 250,
    colors: {
      leafSpring: '#a8b294',
      leafSummer: '#8f9a7e',
      leafAutumn: '#8f9a7e',
      flower: '#5d4a9c',
      bark: '#8a7d68',
    },
    sun: ['full'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'deep violet',
    foliageColour: 'silver-grey',
    notes:
      'Bushy dwarf evergreen shrub, 60 × 75 cm, with narrow silvery-grey leaves and deep violet-purple flower spikes from June. Needs full sun and sharp drainage — the one plant here that will sulk anywhere shaded.',
    source: 'https://www.rhs.org.uk/plants/96353/lavandula-angustifolia-hidcote/details',
  },
  {
    id: 'calamagrostis-karl-foerster',
    common: 'Feather reed grass',
    latin: "Calamagrostis × acutiflora 'Karl Foerster'",
    genus: 'Calamagrostis',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    winterStructure: true,
    plantedHeight: 0.4,
    plantedSpread: 0.3,
    matureHeight: 1.7,
    matureSpread: 0.6,
    yearsToMature: 3,
    budBurst: 78,
    fullLeaf: 132,
    autumnStart: 250,
    leafFall: 330,
    flowerStart: 175,
    flowerEnd: 232,
    colors: {
      leafSpring: '#7fa354',
      leafSummer: '#4f7d42',
      leafAutumn: '#c2a35f',
      flower: '#e8d9b0',
      flowerLate: '#c9a961',
      bark: '#b39a66',
    },
    sun: ['full', 'partial'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'creamy pink ageing to gold',
    foliageColour: 'deep green',
    notes:
      'Stiffly upright clump about 60 cm of foliage with flower stems to 1.7 m. Flowers open creamy white tinged pink in midsummer and age to narrow golden plumes that stand right through winter until they are cut back in February — the only thing in this palette with real January structure.',
    source: 'https://www.rhs.org.uk/plants/72074/calamagrostis-x-acutiflora-karl-foerster/details',
  },
  {
    id: 'hosta-halcyon',
    common: 'Plantain lily',
    latin: "Hosta (Tardiana Group) 'Halcyon'",
    genus: 'Hosta',
    family: 'Asparagaceae',
    type: 'perennial',
    habit: 'clump',
    foliage: 'herbaceous',
    plantedHeight: 0.2,
    plantedSpread: 0.25,
    matureHeight: 0.45,
    matureSpread: 0.9,
    yearsToMature: 5,
    budBurst: 105,
    fullLeaf: 142,
    autumnStart: 258,
    leafFall: 300,
    flowerStart: 190,
    flowerEnd: 226,
    colors: {
      leafSpring: '#8fb0b0',
      leafSummer: '#7593a0',
      leafAutumn: '#d3c26b',
      flower: '#c2bad8',
      bark: '#7593a0',
    },
    sun: ['partial', 'shade'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'pale lavender-grey',
    foliageColour: 'intense blue',
    notes:
      'Dense mound of smooth, spear-shaped intensely blue leaves, about 45 cm tall by 90 cm across. Dies back completely — from November to April there is nothing above ground at all, which is worth seeing on the season slider. Best in shade, where the blue holds.',
    source: 'https://www.rhs.org.uk/plants/78423/hosta-halcyon/details',
  },
  {
    id: 'verbena-bonariensis',
    common: 'Purple top',
    latin: 'Verbena bonariensis',
    genus: 'Verbena',
    family: 'Verbenaceae',
    type: 'perennial',
    habit: 'airy',
    foliage: 'herbaceous',
    winterStructure: true,
    plantedHeight: 0.5,
    plantedSpread: 0.3,
    matureHeight: 1.3,
    matureSpread: 0.6,
    yearsToMature: 2,
    budBurst: 95,
    fullLeaf: 155,
    autumnStart: 285,
    leafFall: 325,
    flowerStart: 185,
    flowerEnd: 292,
    colors: {
      leafSpring: '#6f8f4f',
      leafSummer: '#54763f',
      leafAutumn: '#9c8a5a',
      flower: '#8f5fa8',
      bark: '#6b7a52',
    },
    sun: ['full'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'lilac-purple',
    foliageColour: 'sparse deep green',
    notes:
      'Tall and see-through: 1.2 m of bare wiry stems topped with small lilac-purple flowerheads from July to the first frosts. Designers plant it in front of things precisely because you look through it. Short-lived but self-seeds freely. RHS Award of Garden Merit.',
    source: 'https://www.rhs.org.uk/plants/42079/verbena-bonariensis/details',
  },
  {
    id: 'geranium-rozanne',
    common: 'Cranesbill',
    latin: "Geranium Rozanne ('Gerwat')",
    genus: 'Geranium',
    family: 'Geraniaceae',
    type: 'perennial',
    habit: 'clump',
    foliage: 'herbaceous',
    plantedHeight: 0.2,
    plantedSpread: 0.3,
    matureHeight: 0.45,
    matureSpread: 1.1,
    yearsToMature: 3,
    budBurst: 90,
    fullLeaf: 140,
    autumnStart: 278,
    leafFall: 312,
    flowerStart: 152,
    flowerEnd: 300,
    colors: {
      leafSpring: '#7fa855',
      leafSummer: '#5b8442',
      leafAutumn: '#c96b3f',
      flower: '#4a6fc4',
      bark: '#5b8442',
    },
    sun: ['full', 'partial'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'violet-blue',
    foliageColour: 'mid green',
    notes:
      'Sprawling groundcover to about a metre across, smothered in violet-blue white-centred flowers from June until the frosts — one of the longest flowering seasons of any hardy perennial. Useful for reading the season slider, since it is in flower across most of it.',
    source: 'https://www.rhs.org.uk/plants/153768/geranium-rozanne-gerwat-pbr/details',
  },
];

export const SPECIES_BY_ID: Record<string, Species> = Object.fromEntries(
  SPECIES.map((s) => [s.id, s]),
);

export function getSpecies(id: string): Species {
  const s = SPECIES_BY_ID[id];
  if (!s) throw new Error(`Unknown species: ${id}`);
  return s;
}

export const TYPE_LABELS: Record<Species['type'], string> = {
  tree: 'Trees',
  shrub: 'Shrubs',
  conifer: 'Conifers',
  grass: 'Grasses',
  perennial: 'Perennials',
};
