import type { Species } from '../types';

/** Annuals — 8 of them. Appending here adds the plant to the library. */
export const ANNUALS: Species[] = [
  {
    id: 'cosmos-bipinnatus',
    common: 'Cosmos',
    latin: "Cosmos bipinnatus 'Sonata'",
    genus: 'Cosmos',
    family: 'Asteraceae',
    type: 'annual',
    habit: 'airy',
    foliage: 'herbaceous',
    lifecycle: 'annual',
    plantedHeight: 0.9,
    plantedSpread: 0.42,
    matureHeight: 1.1,
    matureSpread: 0.45,
    yearsToMature: 2,
    budBurst: 150,
    fullLeaf: 196,
    autumnStart: 292,
    leafFall: 302,
    flowerStart: 190,
    flowerEnd: 300,
    colors: {
      leafSpring: '#7fa86a',
      leafSummer: '#5f8a55',
      leafAutumn: '#8a8a5a',
      flower: '#e88fb0',
      flowerLate: '#f4e0e8',
      bark: '#5f8a55',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H2',
    sizeClass: 'medium',
    flowerColour: 'pink, rose and white',
    foliageColour: 'feathery bright green',
    notes:
      'A half-hardy annual, so the age slider does nothing to it — this is a different plant every year, sown in spring, planted out once the frosts are past and killed outright by the first hard one. Feathery foliage and open saucer flowers from July until it goes. Deadhead and it will not stop.',
    source: 'https://www.rhs.org.uk/plants/70959/cosmos-bipinnatus-sonata-series/details',
  },
  {
    id: 'nigella-damascena',
    common: 'Love-in-a-mist',
    latin: 'Nigella damascena',
    genus: 'Nigella',
    family: 'Ranunculaceae',
    type: 'annual',
    habit: 'airy',
    foliage: 'herbaceous',
    lifecycle: 'annual',
    standing: { from: 212, to: 300 },
    plantedHeight: 0.2,
    plantedSpread: 0.15,
    matureHeight: 0.5,
    matureSpread: 0.3,
    yearsToMature: 1,
    budBurst: 78,
    fullLeaf: 132,
    autumnStart: 246,
    leafFall: 276,
    flowerStart: 164,
    flowerEnd: 226,
    colors: {
      leafSpring: '#8fb066',
      leafSummer: '#6b9a62',
      leafAutumn: '#b8a878',
      flower: '#7f9ad8',
      flowerLate: '#a8bce0',
      bark: '#7f9a5c',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'sky blue in a collar of fine bracts',
    foliageColour: 'thread-fine bright green',
    notes:
      'A hardy annual, so the age slider does nothing to it — sow it where it is to flower, because it hates being moved. The inflated striped seedpods that follow are as good as the flowers and dry well. Once you have it you have it: it seeds about politely and comes back every year.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Nigella%20damascena',
  },
  {
    id: 'tagetes-cinnabar',
    common: "Marigold 'Cinnabar'",
    latin: "Tagetes 'Cinnabar'",
    genus: 'Tagetes',
    family: 'Asteraceae',
    type: 'annual',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'annual',
    plantedHeight: 0.3,
    plantedSpread: 0.25,
    matureHeight: 0.7,
    matureSpread: 0.5,
    yearsToMature: 1,
    budBurst: 132,
    fullLeaf: 172,
    autumnStart: 292,
    leafFall: 306,
    flowerStart: 172,
    flowerEnd: 296,
    colors: {
      leafSpring: '#7fa055',
      leafSummer: '#4f7546',
      leafAutumn: '#8a7a4a',
      flower: '#9e3620',
      flowerLate: '#c25a2f',
      bark: '#5f7a4a',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H2',
    sizeClass: 'small',
    flowerColour: 'rusty brick red with a gold reverse',
    foliageColour: 'ferny dark green, pungent',
    notes:
      'A single French marigold in a smoky brick red rather than the municipal orange, tall enough to go in a border rather than a bedding scheme. Half-hardy, so it goes out after the last frost and is killed by the first — deadhead it and it flowers from June until then.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Tagetes%20Cinnabar',
  },
  {
    id: 'ammi-majus',
    common: 'Bullwort',
    latin: 'Ammi majus',
    genus: 'Ammi',
    family: 'Apiaceae',
    type: 'annual',
    habit: 'airy',
    foliage: 'herbaceous',
    lifecycle: 'annual',
    plantedHeight: 0.15,
    plantedSpread: 0.1,
    matureHeight: 1.0,
    matureSpread: 0.4,
    yearsToMature: 1,
    budBurst: 105,
    fullLeaf: 145,
    autumnStart: 260,
    leafFall: 295,
    flowerStart: 178,
    flowerEnd: 255,
    colors: {
      leafSpring: '#8fb862',
      leafSummer: '#5f8a4e',
      leafAutumn: '#a89860',
      flower: '#f8f6ee',
      bark: '#5f8a4e',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H3',
    sizeClass: 'medium',
    flowerColour: 'flat white lace plates',
    foliageColour: 'finely cut bright green',
    notes:
      'Cow parsley you are allowed to plant on purpose — flat white lace plates on branching stems from July until autumn, and the best thing here for softening a border that has gone too solid. Sow it in autumn for far bigger plants than a spring sowing gives. Cut it and it lasts a fortnight in water.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Ammi%20majus',
  },
  {
    id: 'papaver-somniferum',
    common: 'Opium poppy',
    latin: 'Papaver somniferum',
    genus: 'Papaver',
    family: 'Papaveraceae',
    type: 'annual',
    habit: 'airy',
    foliage: 'herbaceous',
    lifecycle: 'annual',
    standing: { from: 210, to: 300 },
    plantedHeight: 0.15,
    plantedSpread: 0.15,
    matureHeight: 1.0,
    matureSpread: 0.4,
    yearsToMature: 1,
    budBurst: 95,
    fullLeaf: 140,
    autumnStart: 240,
    leafFall: 285,
    flowerStart: 172,
    flowerEnd: 208,
    colors: {
      leafSpring: '#a8bfae',
      leafSummer: '#8faa96',
      leafAutumn: '#a89a78',
      flower: '#b04a7a',
      flowerLate: '#d0a0b8',
      bark: '#8faa96',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'mauve-pink to plum, sometimes double',
    foliageColour: 'glaucous blue-grey, sculptural',
    notes:
      'Each flower lasts two days and the plant is worth it anyway — huge crumpled mauve or plum tissue over blue-grey sculptural leaves. Then the seedpods, which are the real point: perfect grey-green pepperpots that stand well into autumn and dry for the house. Seeds itself for ever once you have it.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Papaver%20somniferum',
  },
  {
    id: 'cerinthe-purpurascens',
    common: 'Honeywort',
    latin: "Cerinthe major 'Purpurascens'",
    genus: 'Cerinthe',
    family: 'Boraginaceae',
    type: 'annual',
    habit: 'mound',
    foliage: 'herbaceous',
    lifecycle: 'annual',
    plantedHeight: 0.1,
    plantedSpread: 0.15,
    matureHeight: 0.6,
    matureSpread: 0.5,
    yearsToMature: 1,
    budBurst: 92,
    fullLeaf: 135,
    autumnStart: 255,
    leafFall: 292,
    flowerStart: 150,
    flowerEnd: 260,
    colors: {
      leafSpring: '#9ab4b0',
      leafSummer: '#7f9ea8',
      leafAutumn: '#8a9080',
      flower: '#3a3a7a',
      flowerLate: '#5f5a9a',
      bark: '#7f9ea8',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H3',
    sizeClass: 'small',
    flowerColour: 'deep indigo tubes under blue-purple bracts',
    foliageColour: 'sea-green, spotted, waxy',
    notes:
      'Waxy sea-green leaves that shade upward into blue-purple bracts, with dark indigo tubes hanging underneath — the whole plant is a colour rather than a flower, and nothing else here does it. Bees work it constantly. Half hardy, so sow after frost, and let it seed itself for next year.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Cerinthe%20major%20Purpurascens',
  },
  {
    id: 'antirrhinum-majus',
    common: 'Snapdragon',
    latin: 'Antirrhinum majus',
    genus: 'Antirrhinum',
    family: 'Plantaginaceae',
    type: 'annual',
    habit: 'spire',
    foliage: 'herbaceous',
    lifecycle: 'annual',
    plantedHeight: 0.12,
    plantedSpread: 0.1,
    matureHeight: 0.75,
    matureSpread: 0.35,
    yearsToMature: 1,
    budBurst: 98,
    fullLeaf: 142,
    autumnStart: 265,
    leafFall: 300,
    flowerStart: 168,
    flowerEnd: 288,
    colors: {
      leafSpring: '#8fb85e',
      leafSummer: '#57804a',
      leafAutumn: '#a89860',
      flower: '#d8546a',
      flowerLate: '#e8909a',
      bark: '#57804a',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H3',
    sizeClass: 'small',
    flowerColour: 'crimson-pink, in dense pinchable spikes',
    foliageColour: 'narrow glossy dark green',
    notes:
      'Dense spikes of flowers that snap open when you pinch them, from June until the first hard frost if you keep deadheading. Technically a short-lived perennial and often survives a mild winter, so an old plant will sometimes surprise you in year two. Rust is the enemy; give it air and full sun.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Antirrhinum%20majus',
  },
  {
    id: 'zinnia-elegans',
    common: 'Zinnia',
    latin: 'Zinnia elegans',
    genus: 'Zinnia',
    family: 'Asteraceae',
    type: 'annual',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'annual',
    plantedHeight: 0.12,
    plantedSpread: 0.12,
    matureHeight: 0.7,
    matureSpread: 0.4,
    yearsToMature: 1,
    budBurst: 122,
    fullLeaf: 158,
    autumnStart: 265,
    leafFall: 292,
    flowerStart: 190,
    flowerEnd: 285,
    colors: {
      leafSpring: '#8fb058',
      leafSummer: '#5f8a48',
      leafAutumn: '#a89058',
      flower: '#e0542a',
      flowerLate: '#e88a4a',
      bark: '#5f8a48',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H2',
    sizeClass: 'small',
    flowerColour: 'hot orange, scarlet and magenta',
    foliageColour: 'coarse mid green',
    notes:
      'The hottest colours available from a packet of seed, on stiff stems that make it a first-rate cutting flower. Genuinely tender — do not sow before late May, and it will be killed by the first frost. Hates cold wet roots and root disturbance, so sow direct or plant out from deep modules.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Zinnia%20elegans',
  },
];
