import type { Species } from '../types';

/** Bulbs — 21 of them. Appending here adds the plant to the library. */
export const BULBS: Species[] = [
  {
    id: 'allium-purple-sensation',
    common: 'Ornamental onion',
    latin: "Allium hollandicum 'Purple Sensation'",
    genus: 'Allium',
    family: 'Amaryllidaceae',
    type: 'bulb',
    habit: 'globe',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    standing: { from: 165, to: 250 },
    plantedHeight: 0.5,
    plantedSpread: 0.12,
    matureHeight: 0.9,
    matureSpread: 0.15,
    yearsToMature: 3,
    budBurst: 55,
    fullLeaf: 100,
    autumnStart: 140,
    leafFall: 175,
    flowerStart: 128,
    flowerEnd: 166,
    colors: {
      leafSpring: '#7fa86a',
      leafSummer: '#5f8a5c',
      leafAutumn: '#b3a06a',
      flower: '#6b3f96',
      flowerLate: '#8f6ba8',
      bark: '#7f9a63',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'deep purple',
    foliageColour: 'strappy green, dies back early',
    notes:
      'Dense purple spheres on bare 90 cm stems in May. The strappy leaves yellow and collapse just as the flowers open, so plant it through something that will cover the mess. Leave the seedheads — they stand handsomely until midsummer, then go. Nothing above ground from August until March.',
    source: 'https://www.rhs.org.uk/plants/91576/allium-hollandicum-purple-sensation/details',
  },
  {
    id: 'galanthus-nivalis',
    common: 'Snowdrop',
    latin: 'Galanthus nivalis',
    genus: 'Galanthus',
    family: 'Amaryllidaceae',
    type: 'bulb',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.1,
    plantedSpread: 0.06,
    matureHeight: 0.15,
    matureSpread: 0.12,
    yearsToMature: 4,
    budBurst: 14,
    fullLeaf: 40,
    autumnStart: 120,
    leafFall: 150,
    flowerStart: 24,
    flowerEnd: 66,
    colors: {
      leafSpring: '#7f9a78',
      leafSummer: '#6f8f74',
      leafAutumn: '#b8b083',
      flower: '#fbfbf3',
      bark: '#6f8f74',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive', 'free'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'white',
    foliageColour: 'narrow grey-green',
    notes:
      'The first thing to happen in the garden, in January or February when nothing else is moving. Everything above ground is gone by late May, so it wants planting where something later will cover the space. Increases into sheets if left alone; move it in the green rather than as a dry bulb.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Galanthus%20nivalis',
  },
  {
    id: 'chionodoxa-forbesii',
    common: 'Glory of the snow',
    latin: 'Scilla forbesii',
    genus: 'Scilla',
    family: 'Asparagaceae',
    type: 'bulb',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.1,
    plantedSpread: 0.06,
    matureHeight: 0.15,
    matureSpread: 0.1,
    yearsToMature: 4,
    budBurst: 40,
    fullLeaf: 64,
    autumnStart: 125,
    leafFall: 152,
    flowerStart: 62,
    flowerEnd: 102,
    colors: {
      leafSpring: '#7fa072',
      leafSummer: '#6f9070',
      leafAutumn: '#b8b083',
      flower: '#6f8fd2',
      bark: '#6f9070',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'clear blue with a white eye',
    foliageColour: 'narrow mid green',
    notes:
      'Still catalogued and sold as Chionodoxa, though botanically it has gone back to Scilla. Starry blue over March, before the trees come into leaf, and it seeds about generously under deciduous planting. Gone by the end of May.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Scilla%20forbesii',
  },
  {
    id: 'cyclamen-coum',
    common: 'Eastern cyclamen',
    latin: 'Cyclamen coum',
    genus: 'Cyclamen',
    family: 'Primulaceae',
    type: 'bulb',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.07,
    plantedSpread: 0.1,
    matureHeight: 0.1,
    matureSpread: 0.22,
    yearsToMature: 5,
    budBurst: 4,
    fullLeaf: 28,
    autumnStart: 126,
    leafFall: 152,
    flowerStart: 30,
    flowerEnd: 88,
    colors: {
      leafSpring: '#4f6f56',
      leafSummer: '#46654f',
      leafAutumn: '#9aa07a',
      flower: '#c9418c',
      bark: '#46654f',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['neutral', 'alkaline'],
    soilType: ['loam', 'chalk', 'sand'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'magenta-pink',
    foliageColour: 'rounded, silver-marbled dark green',
    notes:
      'Flowers in the depths of February, and the marbled leaves are worth as much as the flowers. Wants dry shade under a deciduous tree or a hedge bottom, where summer drought is a feature rather than a problem. Note that the real leaf season runs from November, which the model cannot express — it shows the foliage from the turn of the year until it dies back in May.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Cyclamen%20coum',
  },
  {
    id: 'narcissus-poeticus',
    common: "Pheasant's eye daffodil",
    latin: 'Narcissus poeticus var. recurvus',
    genus: 'Narcissus',
    family: 'Amaryllidaceae',
    type: 'bulb',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.25,
    plantedSpread: 0.08,
    matureHeight: 0.4,
    matureSpread: 0.15,
    yearsToMature: 4,
    budBurst: 44,
    fullLeaf: 82,
    autumnStart: 152,
    leafFall: 178,
    flowerStart: 124,
    flowerEnd: 152,
    colors: {
      leafSpring: '#7f9a72',
      leafSummer: '#6b8c6b',
      leafAutumn: '#b8b083',
      flower: '#fdfaf0',
      flowerLate: '#f2e6c8',
      bark: '#6b8c6b',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive', 'free'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'white with a small red-rimmed eye',
    foliageColour: 'strappy grey-green',
    notes:
      'The last daffodil to open, in May when the rest are over, and the only one most people would call beautiful rather than cheerful. Powerfully scented. Naturalises in grass that can be left uncut until midsummer, which is the constraint worth knowing before planting it in a lawn.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Narcissus%20poeticus%20recurvus',
  },
  {
    id: 'narcissus-minnow',
    common: "Daffodil 'Minnow'",
    latin: "Narcissus 'Minnow'",
    genus: 'Narcissus',
    family: 'Amaryllidaceae',
    type: 'bulb',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.15,
    plantedSpread: 0.07,
    matureHeight: 0.22,
    matureSpread: 0.12,
    yearsToMature: 4,
    budBurst: 40,
    fullLeaf: 72,
    autumnStart: 142,
    leafFall: 168,
    flowerStart: 76,
    flowerEnd: 112,
    colors: {
      leafSpring: '#7fa07a',
      leafSummer: '#6b8c70',
      leafAutumn: '#b8b083',
      flower: '#f6efc9',
      flowerLate: '#fbf7e4',
      bark: '#6b8c70',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'cream with a lemon cup',
    foliageColour: 'short grey-green',
    notes:
      'A tazetta with several small scented flowers to a stem, at 20 cm rather than the 40 of a border daffodil — which makes it one of the few that looks right in a pot or at the front of a bed. Dies back quickly and tidily.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Narcissus%20Minnow',
  },
  {
    id: 'allium-summer-drummer',
    common: "Allium 'Summer Drummer'",
    latin: "Allium 'Summer Drummer'",
    genus: 'Allium',
    family: 'Amaryllidaceae',
    type: 'bulb',
    habit: 'globe',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    standing: { from: 226, to: 310 },
    plantedHeight: 1.0,
    plantedSpread: 0.15,
    matureHeight: 1.9,
    matureSpread: 0.2,
    yearsToMature: 3,
    budBurst: 58,
    fullLeaf: 110,
    autumnStart: 178,
    leafFall: 212,
    flowerStart: 188,
    flowerEnd: 228,
    colors: {
      leafSpring: '#7fa86a',
      leafSummer: '#5f8a5c',
      leafAutumn: '#b3a06a',
      flower: '#8a5fa0',
      flowerLate: '#b49ac0',
      bark: '#7f9a63',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'purple and white striped',
    foliageColour: 'strappy grey-green, gone by flowering',
    notes:
      'Nearly two metres, and flowering in July and August when the spring alliums are long over — which is the whole reason to grow it. Needs to come up through something sturdy, because the stems are tall and the leaves have collapsed by the time it flowers.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Allium%20Summer%20Drummer',
  },
  {
    id: 'allium-sphaerocephalon',
    common: 'Drumstick allium',
    latin: 'Allium sphaerocephalon',
    genus: 'Allium',
    family: 'Amaryllidaceae',
    type: 'bulb',
    habit: 'globe',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    standing: { from: 205, to: 285 },
    plantedHeight: 0.5,
    plantedSpread: 0.08,
    matureHeight: 0.85,
    matureSpread: 0.1,
    yearsToMature: 3,
    budBurst: 55,
    fullLeaf: 105,
    autumnStart: 155,
    leafFall: 188,
    flowerStart: 166,
    flowerEnd: 206,
    colors: {
      leafSpring: '#7fa86a',
      leafSummer: '#5f8a5c',
      leafAutumn: '#b3a06a',
      flower: '#8f3f5f',
      flowerLate: '#a86b7f',
      bark: '#7f9a63',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'green turning claret',
    foliageColour: 'thin grey-green, gone by flowering',
    notes:
      'Egg-shaped heads rather than spheres, opening green and staining claret from the top down over June and July, so a drift is never all one colour. Cheap enough to plant by the hundred, which is how it works — singly it disappears.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Allium%20sphaerocephalon',
  },
  {
    id: 'lilium-orienpet',
    common: 'Tree lily',
    latin: 'Lilium Orienpet Group',
    genus: 'Lilium',
    family: 'Liliaceae',
    type: 'bulb',
    habit: 'spire',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.8,
    plantedSpread: 0.2,
    matureHeight: 1.8,
    matureSpread: 0.4,
    yearsToMature: 4,
    budBurst: 78,
    fullLeaf: 132,
    autumnStart: 240,
    leafFall: 276,
    flowerStart: 194,
    flowerEnd: 232,
    colors: {
      leafSpring: '#6f9a5c',
      leafSummer: '#4f7a4a',
      leafAutumn: '#b0a068',
      flower: '#f6d9c0',
      flowerLate: '#e8b58f',
      bark: '#5a7a4a',
    },
    sun: ['full', 'dappled'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['loam', 'sand'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'cream, apricot and gold',
    foliageColour: 'glossy dark green',
    notes:
      'A cross between oriental and trumpet lilies, reaching well over head height in a few years with enormous scented flowers in July and August. Not really a tree — the name is a nursery one for how tall it gets. Watch for lily beetle, which will strip it in days.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Lilium%20Orienpet',
  },
  {
    id: 'tulipa-pink-impression',
    common: 'Tulip',
    latin: "Tulipa 'Pink Impression'",
    genus: 'Tulipa',
    family: 'Liliaceae',
    type: 'bulb',
    habit: 'globe',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.18,
    plantedSpread: 0.1,
    matureHeight: 0.55,
    matureSpread: 0.18,
    yearsToMature: 2,
    budBurst: 52,
    fullLeaf: 96,
    autumnStart: 148,
    leafFall: 182,
    flowerStart: 105,
    flowerEnd: 132,
    colors: {
      leafSpring: '#9aae94',
      leafSummer: '#819980',
      leafAutumn: '#c0b47e',
      flower: '#e0709a',
      bark: '#8aa07f',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['chalk', 'loam', 'sand'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'deep pink',
    foliageColour: 'broad, grey-green',
    notes:
      'A Darwin Hybrid, which is the group worth knowing about: most tulips are effectively annual in a border and are lifted or replaced, while these come back for several years if the ground is sharply drained and the leaves are left to die down. Big rounded flowers on 55 cm stems in late April, and stout enough not to need staking.',
    source: 'https://www.rhs.org.uk/plants/45510/tulipa-pink-impression-4/details',
  },
  {
    id: 'tulipa-black-parrot',
    common: 'Parrot tulip',
    latin: "Tulipa 'Black Parrot'",
    genus: 'Tulipa',
    family: 'Liliaceae',
    type: 'bulb',
    habit: 'globe',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.16,
    plantedSpread: 0.1,
    matureHeight: 0.5,
    matureSpread: 0.2,
    yearsToMature: 2,
    budBurst: 55,
    fullLeaf: 100,
    autumnStart: 152,
    leafFall: 186,
    flowerStart: 120,
    flowerEnd: 148,
    colors: {
      leafSpring: '#8fa87f',
      leafSummer: '#6f8f68',
      leafAutumn: '#bdb079',
      flower: '#3b2340',
      bark: '#7f9a70',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['chalk', 'loam', 'sand'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'deep purple, near black',
    foliageColour: 'broad, mid green',
    notes:
      'Enormous ragged flowers of so dark a purple they read as black, with frilled and twisted margins — the most theatrical thing in this palette and the one that divides opinion. Late, flowering into May when the Darwin hybrids are going over. The heads are heavy enough to flop after rain, which is the price of them.',
    source: 'https://www.rhs.org.uk/plants/84891/tulipa-black-parrot-10/details',
  },
  {
    id: 'tulipa-lilac-wonder',
    common: 'Candia tulip',
    latin: "Tulipa saxatilis (Bakeri Group) 'Lilac Wonder'",
    genus: 'Tulipa',
    family: 'Liliaceae',
    type: 'bulb',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.08,
    plantedSpread: 0.08,
    matureHeight: 0.25,
    matureSpread: 0.22,
    yearsToMature: 3,
    budBurst: 48,
    fullLeaf: 88,
    autumnStart: 140,
    leafFall: 172,
    flowerStart: 95,
    flowerEnd: 122,
    colors: {
      leafSpring: '#8fb27a',
      leafSummer: '#63894f',
      leafAutumn: '#bcae72',
      flower: '#b98fc4',
      bark: '#7f9a63',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['chalk', 'loam', 'sand'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'mauve-pink with a yellow base',
    foliageColour: 'narrow, glossy green',
    notes:
      'A species tulip rather than a garden one, and the difference matters: this is the tulip that genuinely settles in, running about by underground stolons into a widening patch rather than dwindling. Low, at 25 cm, and it wants a hot dry spot that bakes in summer — a gravel garden or the foot of a south wall. The mauve flowers open flat to a yellow centre in sun and shut again in dull weather.',
    source: 'https://www.rhs.org.uk/plants/67509/tulipa-saxatilis-bakeri-group-lilac-wonder-15/details',
  },
  {
    id: 'crocus-tommasinianus',
    common: 'Early crocus',
    latin: 'Crocus tommasinianus',
    genus: 'Crocus',
    family: 'Iridaceae',
    type: 'bulb',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.05,
    plantedSpread: 0.05,
    matureHeight: 0.1,
    matureSpread: 0.1,
    yearsToMature: 3,
    budBurst: 32,
    fullLeaf: 60,
    autumnStart: 130,
    leafFall: 160,
    flowerStart: 42,
    flowerEnd: 75,
    colors: {
      leafSpring: '#7fa860',
      leafSummer: '#5f8a52',
      leafAutumn: '#a8a070',
      flower: '#9a7fc4',
      flowerLate: '#b8a4d4',
      bark: '#5f8a52',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'slender pale lilac, silver on the outside',
    foliageColour: 'fine grassy green with a white midrib',
    notes:
      'The crocus that naturalises properly — thin lilac goblets from mid February, weeks before the fat Dutch ones, and it seeds itself into drifts through grass rather than sitting where you planted it. Opens flat in sun and shuts to a silver spike in dull weather. Squirrels take the corms of everything else and mostly leave this alone.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Crocus%20tommasinianus',
  },
  {
    id: 'camassia-leichtlinii',
    common: 'Quamash',
    latin: 'Camassia leichtlinii',
    genus: 'Camassia',
    family: 'Asparagaceae',
    type: 'bulb',
    habit: 'spire',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.2,
    plantedSpread: 0.1,
    matureHeight: 1.0,
    matureSpread: 0.2,
    yearsToMature: 3,
    budBurst: 62,
    fullLeaf: 105,
    autumnStart: 175,
    leafFall: 205,
    flowerStart: 128,
    flowerEnd: 158,
    colors: {
      leafSpring: '#8fb862',
      leafSummer: '#5f8a52',
      leafAutumn: '#b0a468',
      flower: '#8fa4d8',
      bark: '#5f8a52',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'starry blue spires in May',
    foliageColour: 'broad strappy green, gone by July',
    notes:
      'The bulb for long grass on heavy soil, where tulips rot and most bulbs sulk — metre-tall spires of starry blue in May, exactly between the daffodils finishing and the meadow getting going. Wants ground that stays moist in spring. Leave the grass uncut until the leaves have yellowed in July.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Camassia%20leichtlinii',
  },
  {
    id: 'fritillaria-meleagris',
    common: "Snake's head fritillary",
    latin: 'Fritillaria meleagris',
    genus: 'Fritillaria',
    family: 'Liliaceae',
    type: 'bulb',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.1,
    plantedSpread: 0.05,
    matureHeight: 0.3,
    matureSpread: 0.1,
    yearsToMature: 3,
    budBurst: 58,
    fullLeaf: 95,
    autumnStart: 165,
    leafFall: 195,
    flowerStart: 100,
    flowerEnd: 128,
    colors: {
      leafSpring: '#8faa78',
      leafSummer: '#6f8f68',
      leafAutumn: '#a89a70',
      flower: '#8a4a6a',
      flowerLate: '#b08a9a',
      bark: '#6f8f68',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam'],
    drainage: ['retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'nodding bells chequered dusky purple and grey',
    foliageColour: 'sparse, narrow, grey-green',
    notes:
      'Nodding bells chequered like a snake — a genuinely strange flower, and a British native now rare in the wild. Wants a damp meadow: heavy soil that stays wet through spring and only dries in summer. It will not establish in a dry border. Plant the bulbs the moment you get them; they dry out and die quickly.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Fritillaria%20meleagris',
  },
  {
    id: 'muscari-armeniacum',
    common: 'Grape hyacinth',
    latin: 'Muscari armeniacum',
    genus: 'Muscari',
    family: 'Asparagaceae',
    type: 'bulb',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.08,
    plantedSpread: 0.06,
    matureHeight: 0.2,
    matureSpread: 0.12,
    yearsToMature: 3,
    budBurst: 40,
    fullLeaf: 85,
    autumnStart: 150,
    leafFall: 182,
    flowerStart: 92,
    flowerEnd: 128,
    colors: {
      leafSpring: '#7fa860',
      leafSummer: '#5f8a52',
      leafAutumn: '#a8a070',
      flower: '#3f4a9a',
      flowerLate: '#6a74b8',
      bark: '#5f8a52',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'dense cobalt-blue spikes',
    foliageColour: 'floppy grassy green, up from autumn',
    notes:
      'The strongest blue of early spring, in dense little spikes, and it multiplies into a solid river given a few years. The catch is habit: in life the leaves come up in autumn and lie about looking untidy all winter before the flowers arrive in April. Drawn here with an ordinary spring cycle from February instead, because the seasonal model runs bud burst through to leaf fall within one year and cannot carry a leaf window across the turn of it — so the untidy winter foliage is real and is not shown.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Muscari%20armeniacum',
  },
  {
    id: 'hyacinthoides-non-scripta',
    common: 'English bluebell',
    latin: 'Hyacinthoides non-scripta',
    genus: 'Hyacinthoides',
    family: 'Asparagaceae',
    type: 'bulb',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.1,
    plantedSpread: 0.08,
    matureHeight: 0.35,
    matureSpread: 0.15,
    yearsToMature: 4,
    budBurst: 48,
    fullLeaf: 92,
    autumnStart: 160,
    leafFall: 190,
    flowerStart: 112,
    flowerEnd: 142,
    colors: {
      leafSpring: '#7fb058',
      leafSummer: '#5f8a4a',
      leafAutumn: '#a8a068',
      flower: '#5a5fc0',
      bark: '#5f8a4a',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'deep violet-blue, all hanging one way, scented',
    foliageColour: 'narrow arching green, gone by July',
    notes:
      'The native bluebell, with the flowers all hung down one side of an arching stem and a real scent — the Spanish one stands upright, faces every way and barely smells. Buy cultivated stock, never wild-collected, and keep the two species apart: they hybridise readily and the hybrid swamps the native. Wants dappled woodland shade.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Hyacinthoides%20non-scripta',
  },
  {
    id: 'nectaroscordum-siculum',
    common: 'Sicilian honey garlic',
    latin: 'Nectaroscordum siculum',
    genus: 'Nectaroscordum',
    family: 'Amaryllidaceae',
    type: 'bulb',
    habit: 'globe',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    standing: { from: 180, to: 260 },
    plantedHeight: 0.3,
    plantedSpread: 0.1,
    matureHeight: 1.1,
    matureSpread: 0.2,
    yearsToMature: 3,
    budBurst: 55,
    fullLeaf: 100,
    autumnStart: 155,
    leafFall: 185,
    flowerStart: 138,
    flowerEnd: 172,
    colors: {
      leafSpring: '#8fae70',
      leafSummer: '#6f8f60',
      leafAutumn: '#b0a468',
      flower: '#c4b48f',
      flowerLate: '#a89878',
      bark: '#6f8f60',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'drooping cream bells washed green and maroon',
    foliageColour: 'strappy grey-green, dying as it flowers',
    notes:
      'A relative of the alliums that hangs its flowers instead of bunching them: loose parasols of cream bells stained green and dusky pink, on metre stems in late May. Then every seedpod turns upward at once into a spiky candelabra that stands until August. Seeds itself enthusiastically, which is worth knowing.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Nectaroscordum%20siculum',
  },
  {
    id: 'erythronium-pagoda',
    common: "Dog's tooth violet",
    latin: "Erythronium 'Pagoda'",
    genus: 'Erythronium',
    family: 'Liliaceae',
    type: 'bulb',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.1,
    plantedSpread: 0.1,
    matureHeight: 0.35,
    matureSpread: 0.25,
    yearsToMature: 4,
    budBurst: 62,
    fullLeaf: 98,
    autumnStart: 160,
    leafFall: 190,
    flowerStart: 95,
    flowerEnd: 122,
    colors: {
      leafSpring: '#6f9a5a',
      leafSummer: '#4f7a4a',
      leafAutumn: '#a89868',
      flower: '#e8dc72',
      bark: '#4f7a4a',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam'],
    drainage: ['retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'sulphur-yellow with swept-back petals',
    foliageColour: 'broad, glossy, faintly mottled green',
    notes:
      'Sulphur-yellow flowers with the petals swept right back like a small cyclamen, held above broad mottled leaves in April. A woodland bulb — it wants leafy soil that never bakes, and it resents being dried out in a packet, so buy it potted or plant it the day it arrives.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Erythronium%20Pagoda',
  },
  {
    id: 'colchicum-autumnale',
    common: 'Autumn crocus',
    latin: 'Colchicum autumnale',
    genus: 'Colchicum',
    family: 'Colchicaceae',
    type: 'bulb',
    habit: 'clump',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    plantedHeight: 0.1,
    plantedSpread: 0.1,
    matureHeight: 0.25,
    matureSpread: 0.25,
    yearsToMature: 3,
    budBurst: 55,
    fullLeaf: 95,
    autumnStart: 150,
    leafFall: 185,
    flowerStart: 248,
    flowerEnd: 288,
    colors: {
      leafSpring: '#7fa858',
      leafSummer: '#5f8a4a',
      leafAutumn: '#b0a468',
      flower: '#c48ac0',
      bark: '#5f8a4a',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'lilac-pink goblets on bare ground',
    foliageColour: 'coarse glossy green in spring only',
    notes:
      'Does everything in the wrong order: big lilac goblets straight out of bare earth in September with no leaf at all, then coarse glossy foliage from February to June and nothing above ground in between. Nothing to do with crocuses and extremely poisonous. Plant it through low ground cover so the naked flowers have something to lean on.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Colchicum%20autumnale',
  },
  {
    id: 'eremurus-cleopatra',
    common: 'Foxtail lily',
    latin: "Eremurus × isabellinus 'Cleopatra'",
    genus: 'Eremurus',
    family: 'Asphodelaceae',
    type: 'bulb',
    habit: 'spire',
    foliage: 'herbaceous',
    lifecycle: 'bulb',
    standing: { from: 200, to: 260 },
    plantedHeight: 0.3,
    plantedSpread: 0.3,
    matureHeight: 1.5,
    matureSpread: 0.5,
    yearsToMature: 4,
    budBurst: 68,
    fullLeaf: 108,
    autumnStart: 175,
    leafFall: 210,
    flowerStart: 155,
    flowerEnd: 190,
    colors: {
      leafSpring: '#8fae78',
      leafSummer: '#6f9068',
      leafAutumn: '#b0a068',
      flower: '#e07a3a',
      flowerLate: '#c88a5a',
      bark: '#6f9068',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'burnt orange, opening from the bottom up',
    foliageColour: 'strappy blue-green rosette, gone by July',
    notes:
      'A metre and a half of densely packed burnt-orange stars that open from the bottom of the spike upward over three weeks — one of the great vertical accents of June. The root is a brittle starfish that must be planted shallow on a mound of grit; it rots at the crown in wet winter soil, which is how most of them are lost.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Eremurus%20isabellinus%20Cleopatra',
  },
];
