import type { Species } from '../types';

/** Climbers — 18 of them. Appending here adds the plant to the library. */
export const CLIMBERS: Species[] = [
  {
    id: 'clematis-montana',
    common: 'Mountain clematis',
    latin: 'Clematis montana var. rubens',
    genus: 'Clematis',
    family: 'Ranunculaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'deciduous',
    plantedHeight: 1.5,
    plantedSpread: 0.6,
    matureHeight: 8,
    matureSpread: 4.5,
    yearsToMature: 12,
    budBurst: 86,
    fullLeaf: 122,
    autumnStart: 284,
    leafFall: 320,
    flowerStart: 124,
    flowerEnd: 158,
    colors: {
      leafSpring: '#7f8f5c',
      leafSummer: '#4f6b46',
      leafAutumn: '#a89a62',
      flower: '#e6a8bf',
      bark: '#7a6248',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'large',
    flowerColour: 'soft pink',
    foliageColour: 'bronze-tinted mid green',
    notes:
      'Enormous and enormously generous — a sheet of pink over three weeks in May, and quite capable of pulling down a weak trellis or swamping a small tree. Prune straight after flowering or not at all; cut it back hard in spring and there is no flower that year.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Clematis%20montana%20rubens',
  },
  {
    id: 'clematis-armandii',
    common: 'Evergreen clematis',
    latin: 'Clematis armandii',
    genus: 'Clematis',
    family: 'Ranunculaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'evergreen',
    plantedHeight: 1.2,
    plantedSpread: 0.5,
    matureHeight: 6,
    matureSpread: 3.5,
    yearsToMature: 12,
    budBurst: 82,
    fullLeaf: 132,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 68,
    flowerEnd: 112,
    colors: {
      leafSpring: '#8a9a5c',
      leafSummer: '#3f6042',
      leafAutumn: '#7a7a4a',
      flower: '#fbf8ee',
      bark: '#6b5a42',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H4',
    sizeClass: 'large',
    flowerColour: 'creamy white',
    foliageColour: 'long, leathery, dark green',
    notes:
      'The only widely grown evergreen clematis, and worth it for almond-scented flowers in March and April when little else is climbing. Wants a warm sheltered wall — H4 means it will scorch badly in a cold wind — and it accumulates a thatch of dead leaves at the base that needs pulling out.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Clematis%20armandii',
  },
  {
    id: 'clematis-viticella',
    common: 'Italian leather flower',
    latin: 'Clematis viticella',
    genus: 'Clematis',
    family: 'Ranunculaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'deciduous',
    plantedHeight: 1.0,
    plantedSpread: 0.4,
    matureHeight: 3.5,
    matureSpread: 1.8,
    yearsToMature: 5,
    budBurst: 98,
    fullLeaf: 138,
    autumnStart: 272,
    leafFall: 306,
    flowerStart: 188,
    flowerEnd: 262,
    colors: {
      leafSpring: '#7f9a5c',
      leafSummer: '#4f6b46',
      leafAutumn: '#a09a62',
      flower: '#6b3f8a',
      bark: '#7a6248',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'nodding violet-purple bells',
    foliageColour: 'mid green',
    notes:
      'The easiest clematis there is: cut the whole thing to 30 cm every February and it flowers from July to September on the new growth, which means it never turns into the bare-legged tangle the large-flowered hybrids do. Resistant to clematis wilt, unlike them.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Clematis%20viticella',
  },
  {
    id: 'vitis-coignetiae',
    common: 'Crimson glory vine',
    latin: 'Vitis coignetiae',
    genus: 'Vitis',
    family: 'Vitaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'deciduous',
    plantedHeight: 1.5,
    plantedSpread: 0.6,
    matureHeight: 12,
    matureSpread: 5,
    yearsToMature: 16,
    budBurst: 106,
    fullLeaf: 142,
    autumnStart: 266,
    leafFall: 312,
    flowerStart: 150,
    flowerEnd: 166,
    fruitStart: 252,
    fruitEnd: 306,
    colors: {
      leafSpring: '#8fa860',
      leafSummer: '#4f6b42',
      leafAutumn: '#b4342a',
      flower: '#a8b06a',
      fruit: '#3a3550',
      bark: '#7a6042',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'large',
    flowerColour: 'insignificant green',
    foliageColour: 'huge heart-shaped leaves, scarlet in autumn',
    notes:
      'Grown entirely for October, when leaves the size of dinner plates turn scarlet and crimson. Vigorous enough to need a serious structure and an annual reckoning with the secateurs. The small black grapes are ornamental rather than edible.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Vitis%20coignetiae',
  },
  {
    id: 'trachelospermum-jasminoides',
    common: 'Star jasmine',
    latin: 'Trachelospermum jasminoides',
    genus: 'Trachelospermum',
    family: 'Apocynaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'evergreen',
    plantedHeight: 1.0,
    plantedSpread: 0.4,
    matureHeight: 5,
    matureSpread: 3,
    yearsToMature: 14,
    budBurst: 106,
    fullLeaf: 152,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 166,
    flowerEnd: 236,
    colors: {
      leafSpring: '#8fa862',
      leafSummer: '#2f5a3c',
      leafAutumn: '#8a4a3a',
      flower: '#fbf9f0',
      bark: '#6b5a42',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'white pinwheels',
    foliageColour: 'glossy dark green, bronzing in winter',
    notes:
      'Slow for the first two or three years and then steadily excellent: glossy evergreen cover on a warm wall, with intensely fragrant white flowers all through July and August. The leaves take on a red-bronze cast in a cold winter, which is a feature and not a problem.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Trachelospermum%20jasminoides',
  },
  {
    id: 'jasminum-nudiflorum',
    common: 'Winter jasmine',
    latin: 'Jasminum nudiflorum',
    genus: 'Jasminum',
    family: 'Oleaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 0.8,
    plantedSpread: 0.5,
    matureHeight: 3.0,
    matureSpread: 2.4,
    yearsToMature: 9,
    budBurst: 96,
    fullLeaf: 136,
    autumnStart: 278,
    leafFall: 314,
    flowerStart: 312,
    flowerEnd: 62,
    colors: {
      leafSpring: '#7fa060',
      leafSummer: '#4f7046',
      leafAutumn: '#9a9a5c',
      flower: '#f2c22e',
      bark: '#5f8046',
    },
    sun: ['full', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'bright yellow',
    foliageColour: 'dark green on green stems',
    notes:
      'Yellow flowers on bare green stems from November right through to February, in the one season when a wall has nothing else to offer. Not a true climber — it has no means of attaching itself and must be tied in, or it will simply arch over and root where it touches. Takes a north wall.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Jasminum%20nudiflorum',
  },
  {
    id: 'jasminum-polyanthum',
    common: 'Pink jasmine',
    latin: 'Jasminum polyanthum',
    genus: 'Jasminum',
    family: 'Oleaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'evergreen',
    plantedHeight: 1.0,
    plantedSpread: 0.4,
    matureHeight: 4,
    matureSpread: 2.5,
    yearsToMature: 8,
    budBurst: 96,
    fullLeaf: 146,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 74,
    flowerEnd: 146,
    colors: {
      leafSpring: '#8fa862',
      leafSummer: '#3f6b44',
      leafAutumn: '#8a8a52',
      flower: '#fbf4f2',
      flowerLate: '#f7fbfb',
      bark: '#6b5a42',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H2',
    sizeClass: 'medium',
    flowerColour: 'pink buds opening white',
    foliageColour: 'glossy dark green',
    notes:
      'Overwhelmingly fragrant, and H2 — which in practice means a conservatory, a porch or a very sheltered city courtyard, not an open garden anywhere in Britain. Included because it is asked for constantly; the hardiness rating is the thing to read before buying one for a wall.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Jasminum%20polyanthum',
  },
  {
    id: 'hedera-helix',
    common: 'Common ivy',
    latin: 'Hedera helix',
    genus: 'Hedera',
    family: 'Araliaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'evergreen',
    plantedHeight: 0.6,
    plantedSpread: 0.3,
    matureHeight: 10,
    matureSpread: 3.5,
    yearsToMature: 18,
    budBurst: 92,
    fullLeaf: 138,
    autumnStart: 300,
    leafFall: 350,
    flowerStart: 250,
    flowerEnd: 300,
    fruitStart: 330,
    fruitEnd: 90,
    colors: {
      leafSpring: '#7d9a55',
      leafSummer: '#2f4f34',
      leafAutumn: '#4a5c3a',
      flower: '#c8c98a',
      fruit: '#1b1b22',
      bark: '#6b5a4a',
    },
    sun: ['full', 'dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['chalk', 'clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'large',
    flowerColour: 'greenish yellow',
    foliageColour: 'glossy dark green, pale-veined',
    notes:
      'The plant that answers deep dry shade against a north wall, and the only climber here that clings by its own aerial roots rather than needing a support. Its real interest is the calendar: it flowers in October, when almost nothing else does, and carries black berries through the winter, which is why it feeds more late insects and birds than anything else in this palette.',
    source: 'https://www.rhs.org.uk/plants/43091/hedera-helix/details',
  },
  {
    id: 'lonicera-japonica-halliana',
    common: 'Japanese honeysuckle',
    latin: "Lonicera japonica 'Halliana'",
    genus: 'Lonicera',
    family: 'Caprifoliaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'evergreen',
    plantedHeight: 1,
    plantedSpread: 0.4,
    matureHeight: 6,
    matureSpread: 1.5,
    yearsToMature: 8,
    budBurst: 85,
    fullLeaf: 130,
    autumnStart: 300,
    leafFall: 348,
    flowerStart: 135,
    flowerEnd: 270,
    colors: {
      leafSpring: '#8fae60',
      leafSummer: '#3d6140',
      leafAutumn: '#6e7444',
      flower: '#f7f2d8',
      flowerLate: '#e3c765',
      bark: '#7a6248',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['chalk', 'clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'large',
    flowerColour: 'white ageing to yellow',
    foliageColour: 'dark green, evergreen in mild winters',
    notes:
      'Flowers for four months rather than four weeks, opening white and ageing to deep yellow so a plant carries both colours at once, and scented strongly enough at dusk to be the reason people plant it by a door. Vigorous to the point of nuisance: it is listed on Schedule 9 in Northern Ireland, where planting it in the wild is an offence, and it will smother a small shrub given a season.',
    source: 'https://www.rhs.org.uk/plants/93277/lonicera-japonica-halliana/details',
  },
  {
    id: 'passiflora-caerulea',
    common: 'Blue passion flower',
    latin: 'Passiflora caerulea',
    genus: 'Passiflora',
    family: 'Passifloraceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'evergreen',
    plantedHeight: 1,
    plantedSpread: 0.4,
    matureHeight: 8,
    matureSpread: 3,
    yearsToMature: 8,
    budBurst: 100,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 350,
    flowerStart: 165,
    flowerEnd: 290,
    fruitStart: 240,
    fruitEnd: 330,
    colors: {
      leafSpring: '#8fae63',
      leafSummer: '#3f6a45',
      leafAutumn: '#7a7a48',
      flower: '#dcd8ec',
      fruit: '#e08a2e',
      bark: '#6f5c46',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['chalk', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H4',
    sizeClass: 'large',
    flowerColour: 'white with blue and purple filaments',
    foliageColour: 'deeply lobed, mid green',
    notes:
      'The most structurally odd flower anyone can grow outdoors in Britain, followed by egg-shaped orange fruits that hang on well after the flowers stop. At H4 it is cut to the ground by a hard winter and usually comes again from the base, so it behaves like a herbaceous plant in a cold garden and an evergreen one against a warm wall.',
    source: 'https://www.rhs.org.uk/plants/12356/passiflora-caerulea/details',
  },
  {
    id: 'lathyrus-odoratus',
    common: 'Sweet pea',
    latin: 'Lathyrus odoratus',
    genus: 'Lathyrus',
    family: 'Fabaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'herbaceous',
    lifecycle: 'annual',
    plantedHeight: 0.2,
    plantedSpread: 0.15,
    matureHeight: 2.0,
    matureSpread: 0.6,
    yearsToMature: 1,
    budBurst: 95,
    fullLeaf: 140,
    autumnStart: 250,
    leafFall: 288,
    flowerStart: 160,
    flowerEnd: 262,
    colors: {
      leafSpring: '#9ab86a',
      leafSummer: '#6f9a52',
      leafAutumn: '#a89860',
      flower: '#c46a9a',
      flowerLate: '#dca8c0',
      bark: '#6f9a52',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'pink and mauve, and the best scent in the garden',
    foliageColour: 'soft grey-green, climbing by tendrils',
    notes:
      'Grown for scent above everything, and the one flower where cutting it is the maintenance — stop picking, it sets seed and stops flowering within a fortnight. An annual climber, so it needs a wigwam or netting from scratch each year. Wants rich moist soil and constant water; it goes over fast in drought.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Lathyrus%20odoratus',
  },
  {
    id: 'wisteria-sinensis',
    common: 'Chinese wisteria',
    latin: 'Wisteria sinensis',
    genus: 'Wisteria',
    family: 'Fabaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 1.5,
    plantedSpread: 0.5,
    matureHeight: 9.0,
    matureSpread: 6.0,
    yearsToMature: 20,
    budBurst: 118,
    fullLeaf: 148,
    autumnStart: 272,
    leafFall: 312,
    flowerStart: 128,
    flowerEnd: 155,
    colors: {
      leafSpring: '#9ac462',
      leafSummer: '#4f7a44',
      leafAutumn: '#d8c04a',
      flower: '#9a90c8',
      flowerLate: '#b8b0d8',
      bark: '#6f5f50',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'large',
    flowerColour: 'long lilac racemes, scented, on bare wood',
    foliageColour: 'fresh pinnate green, clear yellow in autumn',
    notes:
      'Long scented lilac racemes hanging from bare branches in May, before the leaves — the most theatrical climber in this palette and the most demanding. It needs pruning twice a year, in July and February, or it makes wood instead of flowers. Buy a grafted named plant: a seedling can take twenty years to flower and may never do it well.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Wisteria%20sinensis',
  },
  {
    id: 'rosa-madame-alfred-carriere',
    common: 'Climbing rose',
    latin: "Rosa 'Madame Alfred Carrière'",
    genus: 'Rosa',
    family: 'Rosaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'deciduous',
    plantedHeight: 1.0,
    plantedSpread: 0.5,
    matureHeight: 5.0,
    matureSpread: 3.0,
    yearsToMature: 8,
    budBurst: 92,
    fullLeaf: 132,
    autumnStart: 278,
    leafFall: 322,
    flowerStart: 150,
    flowerEnd: 285,
    fruitStart: 265,
    fruitEnd: 330,
    colors: {
      leafSpring: '#8fb862',
      leafSummer: '#4a7444',
      leafAutumn: '#a89050',
      flower: '#f8f0ea',
      flowerLate: '#f0dcd8',
      fruit: '#b03a28',
      bark: '#6f5f4e',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'large',
    flowerColour: 'blush white, fading to cream, strongly scented',
    foliageColour: 'light green, nearly thornless stems',
    notes:
      'The climbing rose for a north wall, which almost no rose will take — blush-white scented flowers from June right through to November, on nearly thornless stems that make tying it in a pleasure rather than a fight. Vigorous enough to reach a first-floor window. Prune in winter to a permanent framework.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Rosa%20Madame%20Alfred%20Carriere',
  },
  {
    id: 'parthenocissus-tricuspidata',
    common: 'Boston ivy',
    latin: 'Parthenocissus tricuspidata',
    genus: 'Parthenocissus',
    family: 'Vitaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'deciduous',
    plantedHeight: 1.0,
    plantedSpread: 0.5,
    matureHeight: 12.0,
    matureSpread: 7.0,
    yearsToMature: 15,
    budBurst: 108,
    fullLeaf: 140,
    autumnStart: 258,
    leafFall: 310,
    flowerStart: 165,
    flowerEnd: 185,
    fruitStart: 265,
    fruitEnd: 330,
    colors: {
      leafSpring: '#8fbb58',
      leafSummer: '#3f6b3c',
      leafAutumn: '#b8281e',
      flower: '#a8b46a',
      fruit: '#2a3550',
      bark: '#6f6252',
    },
    sun: ['full', 'dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'large',
    flowerColour: 'insignificant green',
    foliageColour: 'glossy green, turning pure scarlet',
    notes:
      'Sticks itself flat to a wall with adhesive pads and needs no wires at all, then turns the whole elevation scarlet for three weeks in October. The best autumn colour available on a vertical surface. Very vigorous — it will reach the gutters and lift roof tiles, so it wants an annual cut back, not neglect.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Parthenocissus%20tricuspidata',
  },
  {
    id: 'hydrangea-petiolaris',
    common: 'Climbing hydrangea',
    latin: 'Hydrangea anomala subsp. petiolaris',
    genus: 'Hydrangea',
    family: 'Hydrangeaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'deciduous',
    plantedHeight: 0.8,
    plantedSpread: 0.4,
    matureHeight: 8.0,
    matureSpread: 5.0,
    yearsToMature: 18,
    budBurst: 102,
    fullLeaf: 138,
    autumnStart: 270,
    leafFall: 315,
    flowerStart: 155,
    flowerEnd: 195,
    colors: {
      leafSpring: '#8fbb5a',
      leafSummer: '#42703f',
      leafAutumn: '#d8c44a',
      flower: '#f6f4e8',
      bark: '#8a6a52',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive'],
    hardiness: 'H7',
    sizeClass: 'large',
    flowerColour: 'flat white lacecaps in June',
    foliageColour: 'heart-shaped green, clear yellow in autumn',
    notes:
      'The answer to a cold north wall: self-clinging, flowering freely in shade with flat white lacecaps in June, and clear yellow in autumn. Slow to start — expect two or three years of apparently nothing before it begins to climb — and then steady and long-lived. Cinnamon peeling bark in winter is a bonus.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Hydrangea%20anomala%20petiolaris',
  },
  {
    id: 'akebia-quinata',
    common: 'Chocolate vine',
    latin: 'Akebia quinata',
    genus: 'Akebia',
    family: 'Lardizabalaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'evergreen',
    plantedHeight: 1.0,
    plantedSpread: 0.4,
    matureHeight: 8.0,
    matureSpread: 4.0,
    yearsToMature: 12,
    budBurst: 88,
    fullLeaf: 132,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 96,
    flowerEnd: 130,
    colors: {
      leafSpring: '#8fb85e',
      leafSummer: '#456f44',
      leafAutumn: '#4d7749',
      flower: '#6a3a4a',
      bark: '#6f5a4a',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'large',
    flowerColour: 'dusky maroon-chocolate, vanilla-scented',
    foliageColour: 'neat five-fingered green, semi-evergreen',
    notes:
      'Small dusky chocolate-purple flowers in April that smell distinctly of vanilla, over neat five-fingered leaves that mostly hold through winter. Twining rather than self-clinging, so it needs wires. Vigorous once settled and will smother a small shrub, so give it a wall or a big pergola rather than a trellis panel.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Akebia%20quinata',
  },
  {
    id: 'campsis-radicans',
    common: 'Trumpet vine',
    latin: 'Campsis radicans',
    genus: 'Campsis',
    family: 'Bignoniaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'deciduous',
    plantedHeight: 1.0,
    plantedSpread: 0.4,
    matureHeight: 8.0,
    matureSpread: 4.0,
    yearsToMature: 14,
    budBurst: 125,
    fullLeaf: 155,
    autumnStart: 272,
    leafFall: 312,
    flowerStart: 205,
    flowerEnd: 258,
    colors: {
      leafSpring: '#8fb85a',
      leafSummer: '#42703f',
      leafAutumn: '#c8b44a',
      flower: '#e0561e',
      bark: '#7a6252',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'large',
    flowerColour: 'big orange-scarlet trumpets in late summer',
    foliageColour: 'pinnate dark green, very late to appear',
    notes:
      'Fat orange-scarlet trumpets in August and September, when almost nothing else is climbing a wall in flower. It needs a genuinely hot sunny wall to bloom at all — in a cool spot you get a vigorous green plant and no flowers, year after year. Alarmingly late into leaf; do not write it off until June.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Campsis%20radicans',
  },
  {
    id: 'humulus-lupulus-aureus',
    common: 'Golden hop',
    latin: "Humulus lupulus 'Aureus'",
    genus: 'Humulus',
    family: 'Cannabaceae',
    type: 'climber',
    habit: 'climber',
    foliage: 'herbaceous',
    plantedHeight: 0.5,
    plantedSpread: 0.3,
    matureHeight: 6.0,
    matureSpread: 3.0,
    yearsToMature: 4,
    budBurst: 95,
    fullLeaf: 140,
    autumnStart: 262,
    leafFall: 300,
    flowerStart: 215,
    flowerEnd: 255,
    colors: {
      leafSpring: '#e0dc5a',
      leafSummer: '#c4c84a',
      leafAutumn: '#c8a84a',
      flower: '#d8d4a0',
      bark: '#a89a5a',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'papery green-gold cones in late summer',
    foliageColour: 'bright acid yellow, vine-shaped',
    notes:
      'Dies to the ground every winter and climbs six metres again by July, in acid yellow — the fastest thing here by a distance, and the only climber that gives you a bare structure back every winter. Papery hop cones in August. Wants sun for the gold; in shade it turns lime green.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Humulus%20lupulus%20Aureus',
  },
];
