import type { Species } from '../types';

/** Conifers — 8 of them. Appending here adds the plant to the library. */
export const CONIFERS: Species[] = [
  {
    id: 'taxus-baccata',
    common: 'Yew (clipped)',
    latin: 'Taxus baccata',
    genus: 'Taxus',
    family: 'Taxaceae',
    type: 'conifer',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.3,
    plantedHeight: 0.8,
    plantedSpread: 0.5,
    matureHeight: 2.0,
    matureSpread: 0.9,
    yearsToMature: 6,
    budBurst: 110,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 330,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#6f9c4e',
      leafSummer: '#28442c',
      leafAutumn: '#28442c',
      flower: '#c23b22',
      bark: '#8a6650',
    },
    sun: ['full', 'dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'none (red arils on female plants)',
    foliageColour: 'very dark green',
    notes:
      'The workhorse of formal structure. Clipped as a column or hedge it puts on 20–40 cm a year until it reaches the height it is being held at, then stays there. The darkest green in the palette, and it will take deep shade. All parts are toxic.',
    source: 'https://www.rhs.org.uk/plants/18025/taxus-baccata/details',
  },
  {
    id: 'pinus-mugo',
    common: 'Dwarf mountain pine',
    latin: "Pinus mugo 'Mughus'",
    genus: 'Pinus',
    family: 'Pinaceae',
    type: 'conifer',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.4,
    plantedSpread: 0.5,
    matureHeight: 2.0,
    matureSpread: 3.0,
    yearsToMature: 22,
    budBurst: 120,
    fullLeaf: 168,
    autumnStart: 300,
    leafFall: 340,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#5c7a48',
      leafSummer: '#2f4a35',
      leafAutumn: '#2f4a35',
      flower: '#8a7d5a',
      bark: '#6b5a4a',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'none',
    foliageColour: 'dark green',
    notes:
      'Slow, tough and completely hardy — a low spreading dome of dark needles that eventually goes wider than it is tall. Useful evergreen weight at ground level where a yew would be too formal. The pale candles of new growth in May are worth watching for.',
    source: 'https://www.rhs.org.uk/plants/12784/pinus-mugo-mughus/details',
  },
  {
    id: 'cupressus-totem',
    common: 'Italian cypress',
    latin: "Cupressus sempervirens 'Totem'",
    genus: 'Cupressus',
    family: 'Cupressaceae',
    type: 'conifer',
    habit: 'columnar',
    foliage: 'evergreen',
    plantedHeight: 1.2,
    plantedSpread: 0.3,
    matureHeight: 4.5,
    matureSpread: 0.7,
    yearsToMature: 18,
    budBurst: 112,
    fullLeaf: 155,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#5f7f52',
      leafSummer: '#33513a',
      leafAutumn: '#3a583f',
      flower: '#8a9a6a',
      bark: '#6f5f4e',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'none worth drawing',
    foliageColour: 'very dark green, dense and fine',
    notes:
      'A dark green exclamation mark, and the quickest way to put Italy into an English garden. Narrower and more reliable than the species, holding a tight column without tying. H4 is the warning — a wet cold winter is more dangerous to it than a dry cold one, so it wants sharp drainage and sun. Snow can splay the column permanently.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Cupressus%20sempervirens%20Totem',
  },
  {
    id: 'thuja-smaragd',
    common: 'White cedar',
    latin: "Thuja occidentalis 'Smaragd'",
    genus: 'Thuja',
    family: 'Cupressaceae',
    type: 'conifer',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.2,
    plantedHeight: 0.8,
    plantedSpread: 0.4,
    matureHeight: 3.0,
    matureSpread: 1.0,
    yearsToMature: 14,
    budBurst: 110,
    fullLeaf: 152,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#7fa855',
      leafSummer: '#47764a',
      leafAutumn: '#4f7d50',
      flower: '#8a9a6a',
      bark: '#8a6a52',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'none worth drawing',
    foliageColour: 'bright emerald green, held in flat sprays',
    notes:
      'The conifer hedge that behaves — slow enough at 20 cm a year that it will not run away from you, unlike leylandii, and it holds its colour through winter instead of bronzing. Modelled here as a clipped subject, since that is how it is nearly always used: a row of narrow columns or a formal screen.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Thuja%20occidentalis%20Smaragd',
  },
  {
    id: 'juniperus-blue-star',
    common: 'Flaky juniper',
    latin: "Juniperus squamata 'Blue Star'",
    genus: 'Juniperus',
    family: 'Cupressaceae',
    type: 'conifer',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.15,
    plantedSpread: 0.25,
    matureHeight: 0.5,
    matureSpread: 1.0,
    yearsToMature: 12,
    budBurst: 112,
    fullLeaf: 155,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#9ab8c8',
      leafSummer: '#7a9cb4',
      leafAutumn: '#82a3ba',
      flower: '#8a9a6a',
      bark: '#7a6a58',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'none worth drawing',
    foliageColour: 'intense silver-blue, dense and prickly',
    notes:
      'The bluest thing in this palette by a distance, and low enough to sit at the front of a gravel bed or spill over a wall. Very slow — a plant a decade old is still only knee high and a metre across. Needs full sun to hold the colour; in shade it goes a dull grey-green and thins out from underneath.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Juniperus%20squamata%20Blue%20Star',
  },
  {
    id: 'chamaecyparis-ellwoodii',
    common: 'Lawson cypress',
    latin: "Chamaecyparis lawsoniana 'Ellwoodii'",
    genus: 'Chamaecyparis',
    family: 'Cupressaceae',
    type: 'conifer',
    habit: 'columnar',
    foliage: 'evergreen',
    plantedHeight: 0.6,
    plantedSpread: 0.3,
    matureHeight: 2.5,
    matureSpread: 1.0,
    yearsToMature: 18,
    budBurst: 110,
    fullLeaf: 152,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#8fb0b8',
      leafSummer: '#5f7f88',
      leafAutumn: '#67868f',
      flower: '#8a9a6a',
      bark: '#7a6250',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'none worth drawing',
    foliageColour: 'soft grey-blue, feathery',
    notes:
      'A slow soft-textured column in grey-blue, useful where a dark green cypress would be too heavy. Feathery juvenile foliage rather than the flat scale sprays of the species. Takes shade better than most conifers here, and will grow on chalk, which the Italian cypress dislikes.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Chamaecyparis%20lawsoniana%20Ellwoodii',
  },
  {
    id: 'cedrus-atlantica-glauca',
    common: 'Blue Atlas cedar',
    latin: 'Cedrus atlantica Glauca Group',
    genus: 'Cedrus',
    family: 'Pinaceae',
    type: 'conifer',
    habit: 'round',
    foliage: 'evergreen',
    plantedHeight: 2.0,
    plantedSpread: 1.2,
    matureHeight: 18.0,
    matureSpread: 10.0,
    yearsToMature: 45,
    budBurst: 112,
    fullLeaf: 155,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#a8bfcc',
      leafSummer: '#7f9db0',
      leafAutumn: '#87a4b6',
      flower: '#8a9a6a',
      bark: '#6f6258',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'large',
    flowerColour: 'none worth drawing',
    foliageColour: 'silver-blue needles in tufts',
    notes:
      'A parkland tree, and included as the honest warning it is: silver-blue and magnificent, and far too big for almost every garden it gets planted in. Reckon on eight metres in twenty years and eighteen eventually, with a spread to match. Worth having in the palette precisely so the shadow it throws can be seen before it is planted rather than after.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Cedrus%20atlantica%20Glauca',
  },
  {
    id: 'cryptomeria-elegans-compacta',
    common: 'Japanese cedar',
    latin: "Cryptomeria japonica 'Elegans Compacta'",
    genus: 'Cryptomeria',
    family: 'Cupressaceae',
    type: 'conifer',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.6,
    plantedSpread: 0.5,
    matureHeight: 2.5,
    matureSpread: 1.8,
    yearsToMature: 18,
    budBurst: 110,
    fullLeaf: 152,
    autumnStart: 285,
    leafFall: 345,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#8fb45e',
      leafSummer: '#5f8a4e',
      leafAutumn: '#a8683f',
      flower: '#8a9a6a',
      bark: '#8a5f48',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'none worth drawing',
    foliageColour: 'soft feathery green, turning bronze-purple in winter',
    notes:
      'Soft to the point of being woolly, and one of the few conifers that changes colour with the season: fresh green all summer, then a deep bronze-purple through the cold months that comes back to green in spring. That colour shift is a feature, not stress. Dislikes chalk and dries out badly in a hot exposed spot.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Cryptomeria%20japonica%20Elegans%20Compacta',
  },
];
