import type { Species } from '../types';

/** Ferns — 7 of them. Appending here adds the plant to the library. */
export const FERNS: Species[] = [
  {
    id: 'dryopteris-filix-mas',
    common: 'Male fern',
    latin: 'Dryopteris filix-mas',
    genus: 'Dryopteris',
    family: 'Dryopteridaceae',
    type: 'fern',
    habit: 'fern',
    foliage: 'herbaceous',
    plantedHeight: 0.4,
    plantedSpread: 0.4,
    matureHeight: 1.2,
    matureSpread: 1.0,
    yearsToMature: 6,
    budBurst: 96,
    fullLeaf: 138,
    autumnStart: 296,
    leafFall: 340,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#4f7844',
      leafAutumn: '#9a8a52',
      flower: '#4f7844',
      bark: '#6b5a3a',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive', 'free'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'none — a fern, so no flower at all',
    foliageColour: 'fresh green croziers to deep green fronds',
    notes:
      'The native fern of British woodland, and about as tough as a shade plant gets — it will take dry shade under trees once established, which almost nothing else will. Unrolling croziers in April are one of the better moments in the spring garden. Semi-evergreen: it holds on into December in a mild winter and is cut back in February.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Dryopteris%20filix-mas',
  },
  {
    id: 'dicksonia-antarctica',
    common: 'Soft tree fern',
    latin: 'Dicksonia antarctica',
    genus: 'Dicksonia',
    family: 'Dicksoniaceae',
    type: 'fern',
    habit: 'treefern',
    foliage: 'evergreen',
    plantedHeight: 1.2,
    plantedSpread: 1.6,
    matureHeight: 2.6,
    matureSpread: 3.5,
    yearsToMature: 45,
    budBurst: 112,
    fullLeaf: 160,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#8fb066',
      leafSummer: '#46704a',
      leafAutumn: '#8a7a52',
      flower: '#46704a',
      bark: '#6b4f3a',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam'],
    drainage: ['retentive'],
    hardiness: 'H3',
    sizeClass: 'medium',
    flowerColour: 'none — a fern, so no flower at all',
    foliageColour: 'arching deep green fronds on a fibrous trunk',
    notes:
      'Sold by trunk height because the trunk grows only two or three centimetres a year — buying a taller one is buying decades. H3, so it needs a sheltered spot and the crown stuffed with straw in winter over most of the country; the trunk must be kept damp, since the roots are in it rather than the ground.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Dicksonia%20antarctica',
  },
  {
    id: 'polystichum-setiferum',
    common: 'Soft shield fern',
    latin: 'Polystichum setiferum',
    genus: 'Polystichum',
    family: 'Dryopteridaceae',
    type: 'fern',
    habit: 'fern',
    foliage: 'evergreen',
    plantedHeight: 0.2,
    plantedSpread: 0.25,
    matureHeight: 0.8,
    matureSpread: 1.0,
    yearsToMature: 6,
    budBurst: 96,
    fullLeaf: 145,
    autumnStart: 295,
    leafFall: 342,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#8fbb5e',
      leafSummer: '#4a7444',
      leafAutumn: '#547c4a',
      flower: '#4a7444',
      bark: '#7a6a4a',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'none — ferns do not flower',
    foliageColour: 'soft, finely divided, matt green',
    notes:
      'The best evergreen fern for a British garden: soft lacy fronds that stay through winter, unlike the male fern beside it, and unfurl a fresh set of pale croziers in April. Takes dry shade better than most ferns and will grow on chalk. Cut the old fronds off in March just as the new ones rise.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Polystichum%20setiferum',
  },
  {
    id: 'asplenium-scolopendrium',
    common: "Hart's tongue fern",
    latin: 'Asplenium scolopendrium',
    genus: 'Asplenium',
    family: 'Aspleniaceae',
    type: 'fern',
    habit: 'fern',
    foliage: 'evergreen',
    plantedHeight: 0.15,
    plantedSpread: 0.2,
    matureHeight: 0.5,
    matureSpread: 0.6,
    yearsToMature: 6,
    budBurst: 100,
    fullLeaf: 148,
    autumnStart: 295,
    leafFall: 342,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#8fc45a',
      leafSummer: '#3f7040',
      leafAutumn: '#477846',
      flower: '#3f7040',
      bark: '#6a5f42',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'none — ferns do not flower',
    foliageColour: 'undivided glossy strap-shaped green',
    notes:
      'The odd one out among ferns — plain glossy straps rather than lacy fronds, which is exactly why it works next to them. Evergreen, and one of very few ferns that actively likes lime, so it is the fern for a chalk garden or the foot of a mortared wall. Deep shade and damp are what it wants.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Asplenium%20scolopendrium',
  },
  {
    id: 'athyrium-niponicum-pictum',
    common: 'Japanese painted fern',
    latin: 'Athyrium niponicum var. pictum',
    genus: 'Athyrium',
    family: 'Athyriaceae',
    type: 'fern',
    habit: 'fern',
    foliage: 'herbaceous',
    plantedHeight: 0.1,
    plantedSpread: 0.15,
    matureHeight: 0.4,
    matureSpread: 0.5,
    yearsToMature: 5,
    budBurst: 108,
    fullLeaf: 152,
    autumnStart: 272,
    leafFall: 318,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#b8b0c0',
      leafSummer: '#9aa4b0',
      leafAutumn: '#a89a88',
      flower: '#9aa4b0',
      bark: '#8a5a6a',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam'],
    drainage: ['retentive'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'none — ferns do not flower',
    foliageColour: 'silver-grey flushed maroon, on wine-red stems',
    notes:
      'Metallic silver fronds shot through with maroon on wine-red midribs — the only fern here that is grown for colour rather than form, and it lifts a dark corner the way a variegated shrub would. Dies back completely in winter, unlike the evergreen ferns. Wants shade, shelter and soil that stays damp.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Athyrium%20niponicum%20pictum',
  },
  {
    id: 'matteuccia-struthiopteris',
    common: 'Shuttlecock fern',
    latin: 'Matteuccia struthiopteris',
    genus: 'Matteuccia',
    family: 'Onocleaceae',
    type: 'fern',
    habit: 'fern',
    foliage: 'herbaceous',
    standing: { from: 280, to: 60 },
    plantedHeight: 0.25,
    plantedSpread: 0.25,
    matureHeight: 1.2,
    matureSpread: 0.8,
    yearsToMature: 5,
    budBurst: 104,
    fullLeaf: 145,
    autumnStart: 262,
    leafFall: 305,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#a8d46a',
      leafSummer: '#4f8248',
      leafAutumn: '#b09a52',
      flower: '#4f8248',
      bark: '#6a5a3a',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam'],
    drainage: ['retentive', 'waterlogged'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'none — ferns do not flower',
    foliageColour: 'bright fresh green, held as a perfect vase',
    notes:
      'A precise upright vase of pale green fronds, and the most sculptural fern here — a group of them beside water is one of the reliable pictures in British gardening. Dark fertile fronds stand through winter after the green ones collapse. Runs underground into a colony where the ground stays wet, which is usually welcome.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Matteuccia%20struthiopteris',
  },
  {
    id: 'polypodium-vulgare',
    common: 'Common polypody',
    latin: 'Polypodium vulgare',
    genus: 'Polypodium',
    family: 'Polypodiaceae',
    type: 'fern',
    habit: 'fern',
    foliage: 'evergreen',
    plantedHeight: 0.1,
    plantedSpread: 0.15,
    matureHeight: 0.3,
    matureSpread: 0.6,
    yearsToMature: 6,
    budBurst: 180,
    fullLeaf: 225,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#7fae4a',
      leafSummer: '#456f3f',
      leafAutumn: '#4d7746',
      flower: '#456f3f',
      bark: '#6a5f42',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'none — ferns do not flower',
    foliageColour: 'simple, leathery, deep green combs',
    notes:
      'Runs slowly sideways into a low mat of leathery combs, and grows where no other fern will — on top of a wall, in the fork of a tree, in almost no soil at all. Its year is upside down: new fronds appear in midsummer and stand all winter, so it is at its best in January.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Polypodium%20vulgare',
  },
];
