import type { Species } from '../types';

/** Grasses — 23 of them. Appending here adds the plant to the library. */
export const GRASSES: Species[] = [
  {
    id: 'calamagrostis-karl-foerster',
    common: 'Feather reed grass',
    latin: "Calamagrostis × acutiflora 'Karl Foerster'",
    genus: 'Calamagrostis',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    standing: { from: 250, to: 70 },
    plantedHeight: 0.4,
    plantedSpread: 0.3,
    matureHeight: 1.7,
    matureSpread: 0.6,
    yearsToMature: 3,
    budBurst: 78,
    fullLeaf: 132,
    autumnStart: 250,
    leafFall: 330,
    flowerStart: 175,
    flowerEnd: 232,
    colors: {
      leafSpring: '#7fa354',
      leafSummer: '#4f7d42',
      leafAutumn: '#c2a35f',
      flower: '#e8d9b0',
      flowerLate: '#c9a961',
      bark: '#b39a66',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive', 'waterlogged'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'creamy pink ageing to gold',
    foliageColour: 'deep green',
    notes:
      'Stiffly upright clump about 60 cm of foliage with flower stems to 1.7 m. Flowers open creamy white tinged pink in midsummer and age to narrow golden plumes that stand right through winter until they are cut back in February — the only thing in this palette with real January structure.',
    source: 'https://www.rhs.org.uk/plants/72074/calamagrostis-x-acutiflora-karl-foerster/details',
  },
  {
    id: 'stipa-gigantea',
    common: 'Giant oat grass',
    latin: 'Stipa gigantea',
    genus: 'Stipa',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'evergreen',
    standing: { from: 195, to: 40 },
    plantedHeight: 0.5,
    plantedSpread: 0.5,
    matureHeight: 2.4,
    matureSpread: 1.2,
    yearsToMature: 5,
    budBurst: 90,
    fullLeaf: 140,
    autumnStart: 300,
    leafFall: 340,
    flowerStart: 158,
    flowerEnd: 212,
    colors: {
      leafSpring: '#7fa354',
      leafSummer: '#5c7a49',
      leafAutumn: '#c9a961',
      flower: '#e8dcb8',
      flowerLate: '#d6b56a',
      bark: '#b39a66',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'silvery gold oats',
    foliageColour: 'evergreen mid green',
    notes:
      'An evergreen knee-high clump that throws 2 m stems of golden oat panicles in June and holds them, catching low light, until they are cut in late winter. Transparent enough to plant in front of things. RHS Award of Garden Merit.',
    source: 'https://www.rhs.org.uk/plants/17827/stipa-gigantea/details',
  },
  {
    id: 'miscanthus-gracillimus',
    common: 'Maiden grass',
    latin: "Miscanthus sinensis 'Gracillimus'",
    genus: 'Miscanthus',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    standing: { from: 265, to: 70 },
    plantedHeight: 0.6,
    plantedSpread: 0.4,
    matureHeight: 1.8,
    matureSpread: 1.2,
    yearsToMature: 4,
    budBurst: 108,
    fullLeaf: 162,
    autumnStart: 265,
    leafFall: 340,
    flowerStart: 248,
    flowerEnd: 302,
    colors: {
      leafSpring: '#7fa354',
      leafSummer: '#5f8248',
      leafAutumn: '#c9a05a',
      flower: '#e6dcd2',
      flowerLate: '#d8c4b0',
      bark: '#b39a66',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive', 'waterlogged'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'silvery bronze plumes',
    foliageColour: 'fine arching green',
    notes:
      'Narrow arching leaves with a white midrib, in a fountain about 1.5 m across, topped with silvery plumes very late — often not until late September. Everything goes buff and stands right through winter until a February cut-back.',
    source: 'https://www.rhs.org.uk/plants/11431/miscanthus-sinensis-gracillimus/details',
  },
  {
    id: 'miscanthus-morning-light',
    common: "Maiden grass 'Morning Light'",
    latin: "Miscanthus sinensis 'Morning Light'",
    genus: 'Miscanthus',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    standing: { from: 276, to: 45 },
    plantedHeight: 0.49,
    plantedSpread: 0.4,
    matureHeight: 1.4,
    matureSpread: 1.0,
    yearsToMature: 5,
    budBurst: 102,
    fullLeaf: 158,
    autumnStart: 276,
    leafFall: 318,
    flowerStart: 262,
    flowerEnd: 302,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#7f9a6a',
      leafAutumn: '#c8a860',
      flower: '#b06a5c',
      flowerLate: '#e0d2c0',
      bark: '#8a9a5c',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'coppery plumes fading to silver',
    foliageColour: 'very fine green, each blade white-edged',
    notes:
      'The finest-leaved miscanthus, each blade edged with a thin white line so the whole clump reads as a silver haze rather than as green. Flowers late — often not until October in a cool summer — and stands right through winter until it is cut to the ground in February.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Miscanthus%20sinensis%20Morning%20Light',
  },
  {
    id: 'miscanthus-flamingo',
    common: "Maiden grass 'Flamingo'",
    latin: "Miscanthus sinensis 'Flamingo'",
    genus: 'Miscanthus',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    standing: { from: 240, to: 45 },
    plantedHeight: 0.63,
    plantedSpread: 0.44,
    matureHeight: 1.8,
    matureSpread: 1.1,
    yearsToMature: 5,
    budBurst: 102,
    fullLeaf: 158,
    autumnStart: 276,
    leafFall: 318,
    flowerStart: 224,
    flowerEnd: 272,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#6f9a5c',
      leafAutumn: '#c8a45c',
      flower: '#d090a0',
      flowerLate: '#e8dcc8',
      bark: '#8a9a5c',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'pink-flushed pendulous plumes',
    foliageColour: 'narrow arching mid green',
    notes:
      'Among the earliest miscanthus to flower, in August rather than October, which matters in a cold garden where the late ones never quite make it. The plumes hang and nod rather than standing stiffly, and open a distinct pink before bleaching.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Miscanthus%20sinensis%20Flamingo',
  },
  {
    id: 'miscanthus-indianerin',
    common: "Maiden grass 'Indianerin'",
    latin: "Miscanthus sinensis 'Indianerin'",
    genus: 'Miscanthus',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    standing: { from: 254, to: 45 },
    plantedHeight: 0.56,
    plantedSpread: 0.4,
    matureHeight: 1.6,
    matureSpread: 1.0,
    yearsToMature: 5,
    budBurst: 102,
    fullLeaf: 158,
    autumnStart: 276,
    leafFall: 318,
    flowerStart: 240,
    flowerEnd: 288,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#6f9a5c',
      leafAutumn: '#d0863a',
      flower: '#8a4438',
      flowerLate: '#dcc8b4',
      bark: '#8a9a5c',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'deep red-bronze plumes',
    foliageColour: 'mid green turning orange in autumn',
    notes:
      'Red-bronze flowerheads and unusually good orange autumn foliage, so the whole plant colours rather than just the plumes. Reliably flowers in a British summer, which several of the taller Chinese silver grasses do not.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Miscanthus%20sinensis%20Indianerin',
  },
  {
    id: 'miscanthus-zebrinus',
    common: "Zebra grass",
    latin: "Miscanthus sinensis 'Zebrinus'",
    genus: 'Miscanthus',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    standing: { from: 278, to: 45 },
    plantedHeight: 0.63,
    plantedSpread: 0.48,
    matureHeight: 1.8,
    matureSpread: 1.2,
    yearsToMature: 5,
    budBurst: 102,
    fullLeaf: 158,
    autumnStart: 276,
    leafFall: 318,
    flowerStart: 264,
    flowerEnd: 304,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#7fa055',
      leafAutumn: '#c8b062',
      flower: '#b47a68',
      flowerLate: '#e4d8c4',
      bark: '#8a9a5c',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'coppery plumes over banded foliage',
    foliageColour: 'green banded horizontally with butter yellow',
    notes:
      'Banded horizontally with butter-yellow across the blade rather than striped along it, which is genuinely unusual and reads well at a distance. Looser and more arching than the upright cultivars, and inclined to flop on rich soil.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Miscanthus%20sinensis%20Zebrinus',
  },
  {
    id: 'deschampsia-cespitosa',
    common: 'Tufted hair grass',
    latin: 'Deschampsia cespitosa',
    genus: 'Deschampsia',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'evergreen',
    standing: { from: 200, to: 30 },
    plantedHeight: 0.4,
    plantedSpread: 0.3,
    matureHeight: 1.2,
    matureSpread: 0.9,
    yearsToMature: 4,
    budBurst: 96,
    fullLeaf: 150,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 166,
    flowerEnd: 226,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#4f7048',
      leafAutumn: '#c0b478',
      flower: '#d8cfa8',
      flowerLate: '#e8e2cc',
      bark: '#7f9a5c',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam'],
    drainage: ['retentive', 'waterlogged'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'a cloud of tiny green-gold spikelets',
    foliageColour: 'dark green evergreen tuft',
    notes:
      'A native of damp woodland and rough grass, and one of the very few good grasses for partial shade — most want open sun. The flowers are a haze rather than a plume, catching low light spectacularly in June. Evergreen base, so it never leaves a hole; comb the dead material out rather than cutting it down.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Deschampsia%20cespitosa',
  },
  {
    id: 'molinia-caerulea',
    common: 'Purple moor grass',
    latin: 'Molinia caerulea',
    genus: 'Molinia',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    standing: { from: 244, to: 336 },
    plantedHeight: 0.4,
    plantedSpread: 0.3,
    matureHeight: 1.2,
    matureSpread: 0.6,
    yearsToMature: 5,
    budBurst: 108,
    fullLeaf: 162,
    autumnStart: 268,
    leafFall: 302,
    flowerStart: 190,
    flowerEnd: 252,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#5f8a50',
      leafAutumn: '#d8a83a',
      flower: '#6b5a6a',
      flowerLate: '#c0b49a',
      bark: '#8a9a5c',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['retentive', 'waterlogged'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'purple-black spikelets on wiry stems',
    foliageColour: 'mid green turning clear gold',
    notes:
      'Native to wet acid moorland, and one of the few good grasses for ground that stays wet in winter. Turns a strong gold in October — and then, unusually, the whole plant abscises and collapses in one go around the turn of the year, so unlike miscanthus it gives you autumn but not February.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Molinia%20caerulea',
  },
  {
    id: 'molinia-transparent',
    common: "Moor grass 'Transparent'",
    latin: "Molinia caerulea subsp. arundinacea 'Transparent'",
    genus: 'Molinia',
    family: 'Poaceae',
    type: 'grass',
    habit: 'airy',
    foliage: 'herbaceous',
    standing: { from: 248, to: 332 },
    plantedHeight: 0.6,
    plantedSpread: 0.4,
    matureHeight: 2.0,
    matureSpread: 0.9,
    yearsToMature: 6,
    budBurst: 108,
    fullLeaf: 164,
    autumnStart: 268,
    leafFall: 302,
    flowerStart: 200,
    flowerEnd: 262,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#5f8a50',
      leafAutumn: '#d8a83a',
      flower: '#7a6a72',
      flowerLate: '#c8bca4',
      bark: '#8a9a5c',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['retentive', 'waterlogged'],
    hardiness: 'H7',
    sizeClass: 'large',
    flowerColour: 'fine dark spikelets on near-invisible stems',
    foliageColour: 'low green mound under a two-metre veil',
    notes:
      'Named exactly right: a knee-high clump of leaves throwing flower stems to two metres so fine that you look straight through them. Meant to be planted at the front of a border and seen past, not behind everything — one of the few plants where putting the tallest thing in front is the correct decision.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Molinia%20arundinacea%20Transparent',
  },
  {
    id: 'molinia-moorhexe',
    common: "Moor grass 'Moorhexe'",
    latin: "Molinia caerulea subsp. caerulea 'Moorhexe'",
    genus: 'Molinia',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    standing: { from: 242, to: 334 },
    plantedHeight: 0.35,
    plantedSpread: 0.2,
    matureHeight: 0.9,
    matureSpread: 0.45,
    yearsToMature: 5,
    budBurst: 108,
    fullLeaf: 162,
    autumnStart: 268,
    leafFall: 302,
    flowerStart: 190,
    flowerEnd: 250,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#5f8a50',
      leafAutumn: '#d4a442',
      flower: '#4f4250',
      flowerLate: '#b8ac92',
      bark: '#8a9a5c',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['retentive', 'waterlogged'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'very dark, almost black spikelets',
    foliageColour: 'neat green, gold in autumn',
    notes:
      'Strictly, stiffly vertical — a narrow exclamation mark of a grass that holds its shape without staking and never flops, which is why it is used in repeated rhythms through a planting. Small enough for a modest border, unlike most molinias.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Molinia%20caerulea%20Moorhexe',
  },
  {
    id: 'molinia-edith-dudszus',
    common: "Moor grass 'Edith Dudszus'",
    latin: "Molinia caerulea subsp. caerulea 'Edith Dudszus'",
    genus: 'Molinia',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    standing: { from: 242, to: 334 },
    plantedHeight: 0.35,
    plantedSpread: 0.2,
    matureHeight: 0.9,
    matureSpread: 0.5,
    yearsToMature: 5,
    budBurst: 108,
    fullLeaf: 162,
    autumnStart: 268,
    leafFall: 302,
    flowerStart: 190,
    flowerEnd: 250,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#5f8a50',
      leafAutumn: '#d4a442',
      flower: '#332b38',
      flowerLate: '#b4a890',
      bark: '#5a4a52',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['retentive', 'waterlogged'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'near-black spikelets on dark stems',
    foliageColour: 'green with purple-black flower stems',
    notes:
      'The darkest of the moor grasses — the stems themselves are purple-black, not just the spikelets, so the whole flowering structure reads as a dark vertical line. Best with low sun behind it, where the dark stems silhouette.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Molinia%20caerulea%20Edith%20Dudszus',
  },
  {
    id: 'pennisetum-hameln',
    common: 'Chinese fountain grass',
    latin: "Pennisetum alopecuroides 'Hameln'",
    genus: 'Pennisetum',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    plantedHeight: 0.25,
    plantedSpread: 0.3,
    matureHeight: 0.8,
    matureSpread: 0.8,
    yearsToMature: 4,
    budBurst: 112,
    fullLeaf: 162,
    autumnStart: 275,
    leafFall: 330,
    flowerStart: 220,
    flowerEnd: 288,
    standing: { from: 250, to: 60 },
    colors: {
      leafSpring: '#8fae63',
      leafSummer: '#5d8148',
      leafAutumn: '#c2a05c',
      flower: '#c9b8a8',
      bark: '#8a7a5e',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['chalk', 'loam', 'sand'],
    drainage: ['free'],
    hardiness: 'H3',
    sizeClass: 'small',
    flowerColour: 'buff, bottlebrush plumes',
    foliageColour: 'fresh green, tawny in autumn',
    notes:
      'Soft bottlebrush plumes from August, held over a neat tussock, catching low autumn light better than almost anything else this size. Modelled as dying back rather than evergreen: the RHS lists it as evergreen, but in a British winter it browns off completely and is cut to the ground in spring, which is what a designer plans around. At H3 a cold wet winter on heavy ground will kill it.',
    source: 'https://www.rhs.org.uk/plants/43921/pennisetum-alopecuroides-hameln/details',
  },
  {
    id: 'nassella-tenuissima',
    common: 'Mexican feather grass',
    latin: 'Nassella tenuissima (syn. Stipa tenuissima)',
    genus: 'Nassella',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    plantedHeight: 0.2,
    plantedSpread: 0.2,
    matureHeight: 0.6,
    matureSpread: 0.45,
    yearsToMature: 3,
    budBurst: 100,
    fullLeaf: 150,
    autumnStart: 265,
    leafFall: 330,
    flowerStart: 165,
    flowerEnd: 232,
    standing: { from: 180, to: 60 },
    colors: {
      leafSpring: '#a8bd76',
      leafSummer: '#8fa464',
      leafAutumn: '#cbb98a',
      flower: '#e6dcc0',
      bark: '#a89a78',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['chalk', 'clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H4',
    sizeClass: 'small',
    flowerColour: 'silvery buff, fading blond',
    foliageColour: 'very fine, bright green to blond',
    notes:
      'The finest-textured grass in this palette and the one that moves most in wind, which is most of the reason to use it. It seeds itself with real determination — enough that it is banned from sale in parts of Australia and becomes a weeding job in a gravel garden — so plant it where seedlings are welcome. Combed through by hand rather than cut back.',
    source: 'https://www.rhs.org.uk/plants/202303/nassella-tenuissima/details',
  },
  {
    id: 'fargesia-murielae',
    common: 'Umbrella bamboo',
    latin: 'Fargesia murielae',
    genus: 'Fargesia',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'evergreen',
    plantedHeight: 1.0,
    plantedSpread: 0.6,
    matureHeight: 3.5,
    matureSpread: 2.0,
    yearsToMature: 10,
    budBurst: 118,
    fullLeaf: 160,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 0,
    flowerEnd: 0,
    colors: {
      leafSpring: '#9dc169',
      leafSummer: '#5f8f4f',
      leafAutumn: '#6a9757',
      flower: '#c8cc9a',
      bark: '#b0a878',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'none — bamboos flower once in decades',
    foliageColour: 'fine, arching, fresh green',
    notes:
      'The bamboo it is safe to plant. Fargesia clumps where the running bamboos invade, so it screens without a root barrier and without a lawsuit from next door. Arching canes to about three and a half metres, evergreen, and it moves in the smallest breeze, which is half the reason to use it. Drawn with no flower at all, which is right: bamboos flower once in several decades and then usually die.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Fargesia%20murielae',
  },
  {
    id: 'hakonechloa-macra',
    common: 'Japanese forest grass',
    latin: 'Hakonechloa macra',
    genus: 'Hakonechloa',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'herbaceous',
    standing: { from: 300, to: 70 },
    plantedHeight: 0.15,
    plantedSpread: 0.2,
    matureHeight: 0.45,
    matureSpread: 0.8,
    yearsToMature: 5,
    budBurst: 108,
    fullLeaf: 152,
    autumnStart: 276,
    leafFall: 330,
    flowerStart: 225,
    flowerEnd: 265,
    colors: {
      leafSpring: '#a8c86a',
      leafSummer: '#6f9a50',
      leafAutumn: '#c8944a',
      flower: '#c8c49a',
      bark: '#6f9a50',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam'],
    drainage: ['retentive'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'fine airy panicles, barely noticed',
    foliageColour: 'bright green, flowing all one way',
    notes:
      'All the leaves lean the same way, so a clump looks like water pouring over a rock — the most graceful thing here and the one grass that genuinely prefers shade. Turns copper-orange in autumn and holds that colour into winter. Slow to build up, so buy it bigger than feels sensible.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Hakonechloa%20macra',
  },
  {
    id: 'carex-testacea',
    common: 'Orange sedge',
    latin: 'Carex testacea',
    genus: 'Carex',
    family: 'Cyperaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'evergreen',
    plantedHeight: 0.2,
    plantedSpread: 0.2,
    matureHeight: 0.5,
    matureSpread: 0.6,
    yearsToMature: 4,
    budBurst: 100,
    fullLeaf: 145,
    autumnStart: 295,
    leafFall: 340,
    flowerStart: 155,
    flowerEnd: 195,
    colors: {
      leafSpring: '#a8a05a',
      leafSummer: '#b0894a',
      leafAutumn: '#c07a3a',
      flower: '#a89a72',
      bark: '#b0894a',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'insignificant brown spikelets',
    foliageColour: 'olive-bronze, turning burnt orange in sun',
    notes:
      'Evergreen and genuinely orange, which is rare — a fine arching tussock that goes from olive in shade to burnt copper in full sun, and holds it all winter when everything else has been cut down. Comb the dead leaves out with your fingers in spring rather than cutting it back.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Carex%20testacea',
  },
  {
    id: 'panicum-heavy-metal',
    common: 'Switch grass',
    latin: "Panicum virgatum 'Heavy Metal'",
    genus: 'Panicum',
    family: 'Poaceae',
    type: 'grass',
    habit: 'airy',
    foliage: 'herbaceous',
    standing: { from: 265, to: 70 },
    plantedHeight: 0.3,
    plantedSpread: 0.25,
    matureHeight: 1.4,
    matureSpread: 0.7,
    yearsToMature: 4,
    budBurst: 118,
    fullLeaf: 165,
    autumnStart: 268,
    leafFall: 335,
    flowerStart: 215,
    flowerEnd: 268,
    colors: {
      leafSpring: '#8fa8b0',
      leafSummer: '#7f9aa8',
      leafAutumn: '#d8b862',
      flower: '#c8a8b0',
      bark: '#7f9aa8',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'a pink-brown mist above the leaves',
    foliageColour: 'stiff steel-blue, gold in autumn',
    notes:
      'Stiffly upright steel-blue leaves — it does not flop, which sets it apart from most grasses this tall — topped in August by a haze of tiny flowers so fine the plant seems to be surrounded by smoke. Clear gold in autumn, then a buff skeleton that stands until you cut it in February.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Panicum%20virgatum%20Heavy%20Metal',
  },
  {
    id: 'sesleria-autumnalis',
    common: 'Autumn moor grass',
    latin: 'Sesleria autumnalis',
    genus: 'Sesleria',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'evergreen',
    plantedHeight: 0.15,
    plantedSpread: 0.15,
    matureHeight: 0.45,
    matureSpread: 0.45,
    yearsToMature: 3,
    budBurst: 92,
    fullLeaf: 138,
    autumnStart: 295,
    leafFall: 340,
    flowerStart: 218,
    flowerEnd: 262,
    colors: {
      leafSpring: '#c4d47a',
      leafSummer: '#a8c46a',
      leafAutumn: '#b0c070',
      flower: '#d8d4c0',
      bark: '#a8c46a',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'narrow silvery-white spikes',
    foliageColour: 'soft yellow-green, almost lime',
    notes:
      'An unusually light yellow-green that stays evergreen and takes both sun and dry shade, which makes it the most useful matrix grass here — plant it in quantity as a green floor and let perennials come up through it. Silvery spikes in late summer. Tolerates chalk and drought once established.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Sesleria%20autumnalis',
  },
  {
    id: 'anemanthele-lessoniana',
    common: "Pheasant's tail grass",
    latin: 'Anemanthele lessoniana',
    genus: 'Anemanthele',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'evergreen',
    plantedHeight: 0.2,
    plantedSpread: 0.25,
    matureHeight: 0.9,
    matureSpread: 1.0,
    yearsToMature: 3,
    budBurst: 96,
    fullLeaf: 142,
    autumnStart: 268,
    leafFall: 340,
    flowerStart: 195,
    flowerEnd: 250,
    colors: {
      leafSpring: '#8fb058',
      leafSummer: '#7f9a4a',
      leafAutumn: '#c07a34',
      flower: '#c8a48a',
      bark: '#7f9a4a',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'a fine bronze-pink shower',
    foliageColour: 'green, streaking to orange, copper and rust',
    notes:
      'Changes colour through the year rather than at one moment — green in spring, then streaked orange, copper and rust from midsummer onward, all shades present at once on the same plant. Evergreen. Seeds itself about generously, which is either free plants or a weeding job depending on the garden.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Anemanthele%20lessoniana',
  },
  {
    id: 'festuca-glauca',
    common: 'Blue fescue',
    latin: "Festuca glauca 'Elijah Blue'",
    genus: 'Festuca',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'evergreen',
    plantedHeight: 0.1,
    plantedSpread: 0.1,
    matureHeight: 0.3,
    matureSpread: 0.3,
    yearsToMature: 3,
    budBurst: 92,
    fullLeaf: 138,
    autumnStart: 295,
    leafFall: 340,
    flowerStart: 155,
    flowerEnd: 195,
    colors: {
      leafSpring: '#a8c0cc',
      leafSummer: '#8aa8bc',
      leafAutumn: '#93b0c0',
      flower: '#c8c0a0',
      bark: '#8aa8bc',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'thin buff spikelets',
    foliageColour: 'steel blue, needle fine',
    notes:
      'A tight blue hedgehog, small enough for a gravel garden or the front of a dry bed, and the best blue at ground level. Wants poor sharp-drained soil and full sun — on rich damp ground it goes green and rots out in the middle. Replace every three or four years rather than trying to rescue it.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Festuca%20glauca%20Elijah%20Blue',
  },
  {
    id: 'luzula-nivea',
    common: 'Snowy woodrush',
    latin: 'Luzula nivea',
    genus: 'Luzula',
    family: 'Juncaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'evergreen',
    plantedHeight: 0.15,
    plantedSpread: 0.2,
    matureHeight: 0.6,
    matureSpread: 0.5,
    yearsToMature: 3,
    budBurst: 92,
    fullLeaf: 138,
    autumnStart: 295,
    leafFall: 340,
    flowerStart: 150,
    flowerEnd: 190,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#5f8a50',
      leafAutumn: '#688f57',
      flower: '#f4f2e6',
      bark: '#5f8a50',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'clusters of small white stars',
    foliageColour: 'mid green, edged with fine white hairs',
    notes:
      'One of the few grassy things that flowers whitely enough to notice, in loose clusters in June, and it does it in dry shade under trees where most grasses give up. The leaf edges carry fine white hairs that catch the light. Evergreen, tough, and a good knitting plant between shade perennials.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Luzula%20nivea',
  },
  {
    id: 'helictotrichon-sempervirens',
    common: 'Blue oat grass',
    latin: 'Helictotrichon sempervirens',
    genus: 'Helictotrichon',
    family: 'Poaceae',
    type: 'grass',
    habit: 'tussock',
    foliage: 'evergreen',
    standing: { from: 240, to: 60 },
    plantedHeight: 0.2,
    plantedSpread: 0.25,
    matureHeight: 0.9,
    matureSpread: 0.6,
    yearsToMature: 4,
    budBurst: 92,
    fullLeaf: 138,
    autumnStart: 295,
    leafFall: 340,
    flowerStart: 155,
    flowerEnd: 200,
    colors: {
      leafSpring: '#a8bfd0',
      leafSummer: '#87a4bc',
      leafAutumn: '#90aac0',
      flower: '#c8bfa0',
      bark: '#87a4bc',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'buff oat-like sprays arching well clear',
    foliageColour: 'steel blue, stiff and radiating',
    notes:
      'A blue hemisphere of stiff radiating leaves with oat-like flowers arching a long way clear of it — bigger and more architectural than blue fescue, and it holds its shape rather than collapsing. Evergreen. Sharp drainage and full sun are not negotiable; on damp clay it goes brown from the middle.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Helictotrichon%20sempervirens',
  },
];
