import type { Species } from '../types';

/** Shrubs — 64 of them. Appending here adds the plant to the library. */
export const SHRUBS: Species[] = [
  {
    id: 'hydrangea-limelight',
    common: 'Panicle hydrangea',
    latin: "Hydrangea paniculata 'Limelight'",
    genus: 'Hydrangea',
    family: 'Hydrangeaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    plantedHeight: 0.5,
    plantedSpread: 0.4,
    matureHeight: 2.2,
    matureSpread: 2.2,
    yearsToMature: 8,
    budBurst: 108,
    fullLeaf: 138,
    autumnStart: 280,
    leafFall: 320,
    flowerStart: 178,
    flowerEnd: 273,
    colors: {
      leafSpring: '#7fa356',
      leafSummer: '#4a7a3c',
      leafAutumn: '#c9b95f',
      flower: '#e2edbb',
      flowerLate: '#d8a3ac',
      bark: '#7d6a58',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'lime to cream to pink',
    foliageColour: 'mid green',
    notes:
      'Upright deciduous shrub reaching full size in five to ten years. Big conical heads open pale lime from late June, fade through creamy white, then flush pink into autumn — so the flower colour changes as you move the season slider, not just its presence.',
    source: 'https://www.rhs.org.uk/plants/154246/hydrangea-paniculata-limelight/details',
  },
  {
    id: 'lavandula-hidcote',
    common: 'English lavender',
    latin: "Lavandula angustifolia 'Hidcote'",
    genus: 'Lavandula',
    family: 'Lamiaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.25,
    plantedSpread: 0.25,
    matureHeight: 0.6,
    matureSpread: 0.75,
    yearsToMature: 4,
    budBurst: 95,
    fullLeaf: 130,
    autumnStart: 290,
    leafFall: 330,
    flowerStart: 160,
    flowerEnd: 250,
    colors: {
      leafSpring: '#a8b294',
      leafSummer: '#8f9a7e',
      leafAutumn: '#8f9a7e',
      flower: '#5d4a9c',
      bark: '#8a7d68',
    },
    sun: ['full'],
    soilPh: ['neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'deep violet',
    foliageColour: 'silver-grey',
    notes:
      'Bushy dwarf evergreen shrub, 60 × 75 cm, with narrow silvery-grey leaves and deep violet-purple flower spikes from June. Needs full sun and sharp drainage — the one plant here that will sulk anywhere shaded.',
    source: 'https://www.rhs.org.uk/plants/96353/lavandula-angustifolia-hidcote/details',
  },
  {
    id: 'leptospermum-scoparium',
    common: 'Mānuka',
    latin: 'Leptospermum scoparium',
    genus: 'Leptospermum',
    family: 'Myrtaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.4,
    plantedSpread: 0.35,
    matureHeight: 2.0,
    matureSpread: 1.6,
    yearsToMature: 8,
    budBurst: 105,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 340,
    flowerStart: 132,
    flowerEnd: 192,
    colors: {
      leafSpring: '#6f7f52',
      leafSummer: '#4a5c3f',
      leafAutumn: '#4a5c3f',
      flower: '#e089a6',
      bark: '#7a6250',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['loam', 'sand'],
    drainage: ['free'],
    hardiness: 'H3',
    sizeClass: 'small',
    flowerColour: 'pink',
    foliageColour: 'fine dark green',
    notes:
      'Dense, fine-textured evergreen smothered in small flat flowers in late spring. The least hardy plant here — H3 means it needs a sheltered, sunny, well-drained spot and will not survive a hard winter inland. Worth the risk in a mild coastal garden.',
    source: 'https://www.rhs.org.uk/plants/10038/leptospermum-scoparium/details',
  },
  {
    id: 'cornus-midwinter-fire',
    common: 'Dogwood',
    latin: "Cornus sanguinea 'Midwinter Fire'",
    genus: 'Cornus',
    family: 'Cornaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    plantedHeight: 0.5,
    plantedSpread: 0.5,
    matureHeight: 2.0,
    matureSpread: 2.5,
    yearsToMature: 7,
    budBurst: 105,
    fullLeaf: 138,
    autumnStart: 268,
    leafFall: 305,
    flowerStart: 145,
    flowerEnd: 172,
    colors: {
      leafSpring: '#84a85e',
      leafSummer: '#5b8248',
      leafAutumn: '#e0a63c',
      flower: '#f4f0e4',
      bark: '#e2622a',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive', 'waterlogged'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'small creamy white',
    foliageColour: 'mid green, butter yellow in autumn',
    notes:
      'The one plant here that is at its best with no leaves on it. Bare young stems run from yellow through orange to red, so a group lights up from November to March — then you cut a third of it hard back in early spring to keep the new wood coming.',
    source: 'https://www.rhs.org.uk/plants/97993/cornus-sanguinea-midwinter-fire/details',
  },
  {
    id: 'viburnum-tinus',
    common: 'Laurustinus',
    latin: 'Viburnum tinus',
    genus: 'Viburnum',
    family: 'Adoxaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.6,
    plantedSpread: 0.5,
    matureHeight: 3.0,
    matureSpread: 3.0,
    yearsToMature: 10,
    budBurst: 110,
    fullLeaf: 150,
    autumnStart: 300,
    leafFall: 340,
    flowerStart: 305,
    flowerEnd: 110,
    fruitStart: 150,
    fruitEnd: 250,
    colors: {
      leafSpring: '#5c8a52',
      leafSummer: '#2f5138',
      leafAutumn: '#2f5138',
      flower: '#f4ece8',
      flowerLate: '#f7f2ef',
      fruit: '#2b3a5c',
      bark: '#6b6255',
    },
    sun: ['full', 'dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'pink buds opening white',
    foliageColour: 'dark green',
    notes:
      'Flowers right through the winter — pink buds opening white from November to April, when almost nothing else is out — then metallic blue-black berries in summer. Dense, evergreen, takes shade and clipping. Unglamorous and extremely useful.',
    source: 'https://www.rhs.org.uk/plants/18627/viburnum-tinus/details',
  },
  {
    id: 'rosa-gertrude-jekyll',
    common: 'English shrub rose',
    latin: "Rosa Gertrude Jekyll ('Ausbord')",
    genus: 'Rosa',
    family: 'Rosaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    plantedHeight: 0.5,
    plantedSpread: 0.4,
    matureHeight: 1.5,
    matureSpread: 1.2,
    yearsToMature: 5,
    budBurst: 100,
    fullLeaf: 138,
    autumnStart: 280,
    leafFall: 322,
    flowerStart: 150,
    flowerEnd: 292,
    fruitStart: 288,
    fruitEnd: 345,
    colors: {
      leafSpring: '#6f8f4a',
      leafSummer: '#3f6b3a',
      leafAutumn: '#c9a24a',
      flower: '#e0839c',
      flowerLate: '#e8a8b8',
      fruit: '#b8302a',
      bark: '#6b5a44',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'rich pink',
    foliageColour: 'mid green',
    notes:
      'Repeat-flowering from June until the frosts, with the strongest old-rose scent of any modern shrub rose, then hips if you stop deadheading in autumn. Wants feeding and an open position; it goes bare and twiggy in winter and is not trying to hide it.',
    source: 'https://www.rhs.org.uk/plants/95996/rosa-gertrude-jekyll-ausbord-(s)/details',
  },
  {
    id: 'choisya-sundance',
    common: 'Mexican orange blossom',
    latin: "Choisya ternata 'Sundance'",
    genus: 'Choisya',
    family: 'Rutaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.5,
    plantedSpread: 0.5,
    matureHeight: 2.2,
    matureSpread: 2.2,
    yearsToMature: 8,
    budBurst: 105,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 340,
    flowerStart: 122,
    flowerEnd: 165,
    colors: {
      leafSpring: '#dfe574',
      leafSummer: '#c2c94f',
      leafAutumn: '#c2c94f',
      flower: '#fbf8f2',
      bark: '#7d7052',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'white, strongly scented',
    foliageColour: 'bright gold',
    notes:
      'A rounded evergreen dome of aromatic gold foliage that holds its colour all winter and lifts a dull corner, with scented white flowers in May. The gold scorches in full midday sun and goes lime in deep shade, so it wants somewhere in between.',
    source: 'https://www.rhs.org.uk/plants/3641/choisya-ternata-sundance-(v)/details',
  },
  {
    id: 'rosa-sceptred-isle',
    common: "English rose 'Scepter'd Isle'",
    latin: "Rosa 'Ausland'",
    genus: 'Rosa',
    family: 'Rosaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    plantedHeight: 0.6,
    plantedSpread: 0.4,
    matureHeight: 1.2,
    matureSpread: 1.0,
    yearsToMature: 5,
    budBurst: 92,
    fullLeaf: 132,
    autumnStart: 282,
    leafFall: 320,
    flowerStart: 158,
    flowerEnd: 288,
    fruitStart: 274,
    fruitEnd: 330,
    colors: {
      leafSpring: '#8fa860',
      leafSummer: '#4f6f46',
      leafAutumn: '#a89a5c',
      flower: '#f2c3d2',
      flowerLate: '#f8e0e6',
      fruit: '#a83a2a',
      bark: '#6b5a42',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive', 'free'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'soft pink cups',
    foliageColour: 'mid green',
    notes:
      'A David Austin English rose with an unusually strong myrrh scent and one of the longest seasons of any of them, repeating from June until the frosts. Compact enough for a small garden, unlike most of the family.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Rosa%20Sceptred%20Isle%20Ausland',
  },
  {
    id: 'rosa-bring-me-sunshine',
    common: "Rose 'Bring Me Sunshine'",
    latin: "Rosa 'Bring Me Sunshine'",
    genus: 'Rosa',
    family: 'Rosaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    plantedHeight: 0.5,
    plantedSpread: 0.4,
    matureHeight: 1.0,
    matureSpread: 0.7,
    yearsToMature: 5,
    budBurst: 92,
    fullLeaf: 132,
    autumnStart: 282,
    leafFall: 320,
    flowerStart: 160,
    flowerEnd: 292,
    colors: {
      leafSpring: '#8fa860',
      leafSummer: '#4f6f46',
      leafAutumn: '#a89a5c',
      flower: '#f5c542',
      flowerLate: '#f8dc8a',
      bark: '#6b5a42',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive', 'free'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'warm yellow',
    foliageColour: 'glossy mid green',
    notes:
      'A compact yellow bush rose, repeat-flowering from June to the first frosts and healthy enough not to need spraying. Yellow roses fade as they age, so a bush carries several shades at once.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Rosa%20Bring%20Me%20Sunshine',
  },
  {
    id: 'rosa-glauca',
    common: 'Red-leaved rose',
    latin: 'Rosa glauca',
    genus: 'Rosa',
    family: 'Rosaceae',
    type: 'shrub',
    habit: 'multistem',
    foliage: 'deciduous',
    plantedHeight: 0.8,
    plantedSpread: 0.5,
    matureHeight: 2.5,
    matureSpread: 2.0,
    yearsToMature: 8,
    budBurst: 88,
    fullLeaf: 126,
    autumnStart: 268,
    leafFall: 306,
    flowerStart: 160,
    flowerEnd: 186,
    fruitStart: 232,
    fruitEnd: 350,
    colors: {
      leafSpring: '#9a8fa0',
      leafSummer: '#7f7f92',
      leafAutumn: '#b08a6a',
      flower: '#e8899f',
      fruit: '#9e2f2a',
      bark: '#8a5a4a',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'single mid pink with a white eye',
    foliageColour: 'grey-purple, glaucous',
    notes:
      'Grown for the foliage rather than the flower — dusky purple-grey leaves on plum-coloured stems, which is why it earns border space next to plants it would otherwise clash with. Single flowers for a fortnight in June, then heavy bunches of red hips that hold into winter.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Rosa%20glauca',
  },
  {
    id: 'rosa-canina',
    common: 'Dog rose',
    latin: 'Rosa canina',
    genus: 'Rosa',
    family: 'Rosaceae',
    type: 'shrub',
    habit: 'multistem',
    foliage: 'deciduous',
    plantedHeight: 0.8,
    plantedSpread: 0.6,
    matureHeight: 3.0,
    matureSpread: 3.0,
    yearsToMature: 9,
    budBurst: 92,
    fullLeaf: 128,
    autumnStart: 270,
    leafFall: 310,
    flowerStart: 158,
    flowerEnd: 188,
    fruitStart: 236,
    fruitEnd: 356,
    colors: {
      leafSpring: '#8fa860',
      leafSummer: '#54704a',
      leafAutumn: '#a8964f',
      flower: '#f4d6dc',
      fruit: '#c0392b',
      bark: '#7a6248',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'blush pink singles',
    foliageColour: 'mid green',
    notes:
      'The native hedgerow rose: arching, thorny and completely indestructible, for a boundary or a wild hedge rather than a border. Scented single flowers in June, then scarlet hips that feed birds through the winter.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Rosa%20canina',
  },
  {
    id: 'sarcococca-confusa',
    common: 'Christmas box',
    latin: 'Sarcococca confusa',
    genus: 'Sarcococca',
    family: 'Buxaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.4,
    plantedSpread: 0.4,
    matureHeight: 1.5,
    matureSpread: 1.5,
    yearsToMature: 12,
    budBurst: 110,
    fullLeaf: 150,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 338,
    flowerEnd: 76,
    fruitStart: 120,
    fruitEnd: 336,
    colors: {
      leafSpring: '#7fa860',
      leafSummer: '#2f5238',
      leafAutumn: '#3f5f42',
      flower: '#f8f6ea',
      fruit: '#241f26',
      bark: '#4f6642',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive', 'free'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'tiny cream tufts',
    foliageColour: 'glossy dark green',
    notes:
      'The flowers are almost invisible and the scent carries across a garden — vanilla, in January, from a shrub that also happens to be one of the few good evergreens for deep shade. Plant it by a door or a path, where somebody will walk past it in winter, or the whole point is wasted.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Sarcococca%20confusa',
  },
  {
    id: 'photinia-red-robin',
    common: "Photinia 'Red Robin'",
    latin: "Photinia x fraseri 'Red Robin'",
    genus: 'Photinia',
    family: 'Rosaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 1.0,
    plantedSpread: 0.6,
    matureHeight: 4,
    matureSpread: 3,
    yearsToMature: 12,
    budBurst: 88,
    fullLeaf: 140,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 128,
    flowerEnd: 156,
    colors: {
      leafSpring: '#c0392b',
      leafSummer: '#2f5a3a',
      leafAutumn: '#4a6b42',
      flower: '#f6f2e6',
      bark: '#7a6248',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'flat heads of small white flowers',
    foliageColour: 'brilliant red new growth over dark green',
    notes:
      'Grown for the scarlet flush of new leaves, which is why it is usually clipped — every cut produces another flush, and an unclipped plant does it once in April and then goes plain green. Ubiquitous as a screening hedge, and prone to leaf spot where air movement is poor.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Photinia%20fraseri%20Red%20Robin',
  },
  {
    id: 'elaeagnus-submacrophylla',
    common: 'Oleaster',
    latin: 'Elaeagnus x submacrophylla',
    genus: 'Elaeagnus',
    family: 'Elaeagnaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.8,
    plantedSpread: 0.6,
    matureHeight: 3.5,
    matureSpread: 3.5,
    yearsToMature: 12,
    budBurst: 105,
    fullLeaf: 150,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 286,
    flowerEnd: 330,
    colors: {
      leafSpring: '#a8b58a',
      leafSummer: '#4f6b50',
      leafAutumn: '#5f7a58',
      flower: '#f2ead2',
      bark: '#7a6a52',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'tiny cream bells, hidden under the leaves',
    foliageColour: 'leathery green, silver-scaled beneath',
    notes:
      'Still sold almost everywhere as Elaeagnus x ebbingei. A workhorse screening shrub that shrugs off salt wind and poor dry soil, and then produces an astonishing scent in late October from flowers nobody ever notices. Variegated forms revert; cut green shoots out as they appear.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Elaeagnus%20submacrophylla',
  },
  {
    id: 'garrya-james-roof',
    common: "Silk tassel bush 'James Roof'",
    latin: "Garrya elliptica 'James Roof'",
    genus: 'Garrya',
    family: 'Garryaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 1.0,
    plantedSpread: 0.7,
    matureHeight: 4,
    matureSpread: 3,
    yearsToMature: 14,
    budBurst: 108,
    fullLeaf: 152,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 4,
    flowerEnd: 72,
    colors: {
      leafSpring: '#7f9a5f',
      leafSummer: '#3f5a42',
      leafAutumn: '#4f6b48',
      flower: '#c9c6a2',
      bark: '#6b5a48',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'grey-green catkins to 20 cm',
    foliageColour: 'dull leathery dark green',
    notes:
      "A dull shrub for ten months and remarkable for two: 'James Roof' carries the longest catkins of any form, hanging in grey curtains through January and February. Male plants have the good tassels. Wants a wall, and resents being moved once settled.",
    source: 'https://www.rhs.org.uk/plants/search-results?query=Garrya%20elliptica%20James%20Roof',
  },
  {
    id: 'mahonia-charity',
    common: "Mahonia 'Charity'",
    latin: "Mahonia x media 'Charity'",
    genus: 'Mahonia',
    family: 'Berberidaceae',
    type: 'shrub',
    habit: 'multistem',
    foliage: 'evergreen',
    plantedHeight: 0.8,
    plantedSpread: 0.6,
    matureHeight: 3.5,
    matureSpread: 3,
    yearsToMature: 12,
    budBurst: 110,
    fullLeaf: 155,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 302,
    flowerEnd: 24,
    fruitStart: 60,
    fruitEnd: 150,
    colors: {
      leafSpring: '#8fa855',
      leafSummer: '#33513a',
      leafAutumn: '#5a3f38',
      flower: '#f0c73a',
      fruit: '#4a5a86',
      bark: '#8a7250',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive', 'free'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'yellow racemes, lily-of-the-valley scented',
    foliageColour: 'architectural spiny dark green',
    notes:
      'Upright, gaunt and useful: yellow spires from November to January in shade, followed by blue-bloomed berries. Goes leggy with age, and the cure is to cut whole stems to 30 cm in spring — it breaks readily from old wood. The leaf spines are genuinely vicious, so keep it off a path edge.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Mahonia%20media%20Charity',
  },
  {
    id: 'griselinia-littoralis',
    common: 'New Zealand broadleaf',
    latin: 'Griselinia littoralis',
    genus: 'Griselinia',
    family: 'Griseliniaceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.3,
    plantedHeight: 0.8,
    plantedSpread: 0.5,
    matureHeight: 2.5,
    matureSpread: 1.2,
    yearsToMature: 10,
    budBurst: 108,
    fullLeaf: 152,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 138,
    flowerEnd: 160,
    colors: {
      leafSpring: '#a8c46a',
      leafSummer: '#6f9a52',
      leafAutumn: '#7fa05c',
      flower: '#c8cc9a',
      bark: '#7a6a52',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'insignificant yellow-green',
    foliageColour: 'glossy apple green',
    notes:
      'The standard evergreen hedge for a seaside garden — it takes salt wind better than almost anything and clips to a clean apple-green wall. Inland and in a cold winter it can be cut back hard by frost, which is what the H4 rating is warning about. Modelled here as a clipped hedge rather than the eight-metre tree it becomes if left alone.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Griselinia%20littoralis',
  },
  {
    id: 'buxus-sempervirens',
    common: 'Common box',
    latin: 'Buxus sempervirens',
    genus: 'Buxus',
    family: 'Buxaceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.1,
    plantedHeight: 0.25,
    plantedSpread: 0.25,
    matureHeight: 1.0,
    matureSpread: 0.8,
    yearsToMature: 12,
    budBurst: 105,
    fullLeaf: 148,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 92,
    flowerEnd: 118,
    colors: {
      leafSpring: '#9ab85f',
      leafSummer: '#3f5f3a',
      leafAutumn: '#4f6b42',
      flower: '#d8d8a8',
      bark: '#8a7f66',
    },
    sun: ['full', 'dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'insignificant',
    foliageColour: 'small, dense, dark green',
    notes:
      'The classic clipped edging, at ten centimetres of growth a year — which is why a low box hedge is a decade of patience and not a season. Box blight and box tree moth have both made it a far riskier choice than it was twenty years ago; Ilex crenata is the usual substitute.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Buxus%20sempervirens',
  },
  {
    id: 'pyracantha-coccinea',
    common: 'Firethorn',
    latin: 'Pyracantha coccinea',
    genus: 'Pyracantha',
    family: 'Rosaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.8,
    plantedSpread: 0.6,
    matureHeight: 3.5,
    matureSpread: 3,
    yearsToMature: 10,
    budBurst: 100,
    fullLeaf: 142,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 140,
    flowerEnd: 172,
    fruitStart: 248,
    fruitEnd: 52,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#3f6042',
      leafAutumn: '#4f6b48',
      flower: '#f4f0e0',
      fruit: '#e2571f',
      bark: '#7a6248',
    },
    sun: ['full', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'dense heads of small white flowers',
    foliageColour: 'glossy dark green on thorny stems',
    notes:
      'Will flower and fruit on a north wall, which very little else does, and the berry display from September onwards is as strong as anything in the garden. The thorns are serious — excellent against an intruder, unpleasant against a washing line. Prune in late summer so you can see which shoots carry the berries.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Pyracantha%20coccinea',
  },
  {
    id: 'cistus-purpureus',
    common: 'Purple rock rose',
    latin: 'Cistus x purpureus',
    genus: 'Cistus',
    family: 'Cistaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.4,
    plantedSpread: 0.4,
    matureHeight: 1.0,
    matureSpread: 1.2,
    yearsToMature: 6,
    budBurst: 100,
    fullLeaf: 142,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 156,
    flowerEnd: 198,
    colors: {
      leafSpring: '#8a9a72',
      leafSummer: '#5a6b55',
      leafAutumn: '#6b7a5f',
      flower: '#d1508f',
      bark: '#7a6450',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'small',
    flowerColour: 'magenta with a maroon blotch',
    foliageColour: 'grey-green, resinous',
    notes:
      'Each flower lasts a single morning and the bush is covered again the next day for six weeks — a plant that has to be watched rather than kept. Wants sharp drainage, full sun and no kindness whatsoever; it rots in a wet winter on clay and cannot be pruned back into old wood.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Cistus%20purpureus',
  },
  {
    id: 'cistus-argenteus',
    common: "Rock rose 'Silver Pink'",
    latin: "Cistus x argenteus 'Silver Pink'",
    genus: 'Cistus',
    family: 'Cistaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.35,
    plantedSpread: 0.4,
    matureHeight: 0.8,
    matureSpread: 1.0,
    yearsToMature: 6,
    budBurst: 100,
    fullLeaf: 142,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 152,
    flowerEnd: 192,
    colors: {
      leafSpring: '#a0ab8f',
      leafSummer: '#6f7f68',
      leafAutumn: '#7a8a70',
      flower: '#f0a8bc',
      bark: '#7a6450',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'small',
    flowerColour: 'clear silvery pink',
    foliageColour: 'soft grey-green',
    notes:
      'Lower and greyer than the purple form, and hardier than most cistus — one of the more reliable choices for a hot dry bank or the edge of a gravel garden. Same rules: full sun, sharp drainage, no hard pruning.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Cistus%20argenteus%20Silver%20Pink',
  },
  {
    id: 'helianthemum-nummularium',
    common: 'Rock rose',
    latin: 'Helianthemum nummularium',
    genus: 'Helianthemum',
    family: 'Cistaceae',
    type: 'shrub',
    habit: 'clump',
    foliage: 'evergreen',
    plantedHeight: 0.12,
    plantedSpread: 0.2,
    matureHeight: 0.25,
    matureSpread: 0.6,
    yearsToMature: 4,
    budBurst: 98,
    fullLeaf: 138,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 136,
    flowerEnd: 200,
    colors: {
      leafSpring: '#9aab7a',
      leafSummer: '#6b7f5f',
      leafAutumn: '#7a8a66',
      flower: '#f2b02a',
      bark: '#7a6a52',
    },
    sun: ['full'],
    soilPh: ['neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'yellow, orange or pink singles',
    foliageColour: 'small grey-green',
    notes:
      'The other plant called rock rose — a native chalk-downland sub-shrub making a low evergreen mat, not to be confused with Cistus, which is larger and shrubbier. Smothers itself in flower through June, and responds to a shear straight afterwards with a second flush.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Helianthemum%20nummularium',
  },
  {
    id: 'convolvulus-cneorum',
    common: 'Silverbush',
    latin: 'Convolvulus cneorum',
    genus: 'Convolvulus',
    family: 'Convolvulaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.25,
    plantedSpread: 0.3,
    matureHeight: 0.7,
    matureSpread: 0.9,
    yearsToMature: 5,
    budBurst: 100,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 132,
    flowerEnd: 252,
    colors: {
      leafSpring: '#d2d6c2',
      leafSummer: '#b8bfa8',
      leafAutumn: '#c0c6b0',
      flower: '#fdfbf4',
      bark: '#8a8570',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'small',
    flowerColour: 'white funnels from pink buds',
    foliageColour: 'silky silver, almost metallic',
    notes:
      'Grown as much for the foliage as the flower — silver leaves with a satin sheen that hold their colour all winter. Absolutely intolerant of wet feet; on heavy ground it wants a raised bed or a pot. Short-lived, and worth taking cuttings from.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Convolvulus%20cneorum',
  },
  {
    id: 'santolina-chamaecyparissus',
    common: 'Cotton lavender',
    latin: 'Santolina chamaecyparissus',
    genus: 'Santolina',
    family: 'Asteraceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.2,
    plantedSpread: 0.25,
    matureHeight: 0.5,
    matureSpread: 0.9,
    yearsToMature: 5,
    budBurst: 98,
    fullLeaf: 140,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 182,
    flowerEnd: 226,
    colors: {
      leafSpring: '#cfd3bc',
      leafSummer: '#adb59a',
      leafAutumn: '#b8bfa4',
      flower: '#f0c828',
      bark: '#8a8266',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'hard yellow buttons',
    foliageColour: 'finely cut silver-white',
    notes:
      'A dense silver cushion that clips into a low hedge as readily as box, and is aromatic when brushed. Many gardeners shear the flowers off before they open, on the grounds that the yellow fights the silver. Cut it back into the grey each spring or it goes woody and splits open.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Santolina%20chamaecyparissus',
  },
  {
    id: 'santolina-lemon-fizz',
    common: "Cotton lavender 'Lemon Fizz'",
    latin: "Santolina chamaecyparissus 'Lemon Fizz'",
    genus: 'Santolina',
    family: 'Asteraceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.18,
    plantedSpread: 0.22,
    matureHeight: 0.4,
    matureSpread: 0.7,
    yearsToMature: 5,
    budBurst: 98,
    fullLeaf: 140,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 182,
    flowerEnd: 224,
    colors: {
      leafSpring: '#dbe86a',
      leafSummer: '#c2d24a',
      leafAutumn: '#c8d45c',
      flower: '#f6e07a',
      bark: '#8a8a52',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'pale lemon buttons',
    foliageColour: 'acid yellow-green, feathery',
    notes:
      'The same plant as the silver cotton lavender with the colour turned up: acid-yellow foliage that reads as a light source in a dark planting. Keeps its colour best in full sun on poor soil; feed it and it goes green and floppy.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Santolina%20Lemon%20Fizz',
  },
  {
    id: 'salvia-rosmarinus',
    common: 'Rosemary',
    latin: 'Salvia rosmarinus',
    genus: 'Salvia',
    family: 'Lamiaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.4,
    plantedSpread: 0.3,
    matureHeight: 1.5,
    matureSpread: 1.2,
    yearsToMature: 8,
    budBurst: 96,
    fullLeaf: 140,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 78,
    flowerEnd: 142,
    colors: {
      leafSpring: '#8fa878',
      leafSummer: '#4f6b52',
      leafAutumn: '#5f7a5c',
      flower: '#8fa8d6',
      bark: '#7a6a54',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'pale blue',
    foliageColour: 'dark needle green, silver beneath',
    notes:
      'Renamed from Rosmarinus officinalis, to general irritation. Flowers from March, earlier than almost any other shrub, and again in autumn in a mild year — which makes it one of the better early sources of nectar. Wants poor sharp drainage; it dies of wet and cold together, not cold alone.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Salvia%20rosmarinus',
  },
  {
    id: 'rosemary-foxtail',
    common: "Rosemary 'Foxtail'",
    latin: "Salvia rosmarinus 'Foxtail'",
    genus: 'Salvia',
    family: 'Lamiaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.3,
    plantedSpread: 0.35,
    matureHeight: 0.8,
    matureSpread: 1.5,
    yearsToMature: 7,
    budBurst: 96,
    fullLeaf: 140,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 80,
    flowerEnd: 140,
    colors: {
      leafSpring: '#8fa878',
      leafSummer: '#52705a',
      leafAutumn: '#5f7a5c',
      flower: '#9ab0d8',
      bark: '#7a6a54',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'small',
    flowerColour: 'pale blue',
    foliageColour: 'dense bright green, brush-like shoots',
    notes:
      'A trailing rosemary with unusually thick bottlebrush shoots, for spilling over a wall or the edge of a raised bed rather than standing up in a border. Same conditions as the upright form and the same intolerance of a wet winter.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Salvia%20rosmarinus%20Foxtail',
  },
  {
    id: 'erica-carnea',
    common: 'Winter heath',
    latin: 'Erica carnea',
    genus: 'Erica',
    family: 'Ericaceae',
    type: 'shrub',
    habit: 'clump',
    foliage: 'evergreen',
    plantedHeight: 0.12,
    plantedSpread: 0.2,
    matureHeight: 0.25,
    matureSpread: 0.55,
    yearsToMature: 5,
    budBurst: 100,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 334,
    flowerEnd: 108,
    colors: {
      leafSpring: '#8fb05c',
      leafSummer: '#4f6b46',
      leafAutumn: '#5f7a4f',
      flower: '#d2588f',
      flowerLate: '#e0a0bc',
      bark: '#6b5a48',
    },
    sun: ['full', 'dappled'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'rose pink to magenta',
    foliageColour: 'fine needle green',
    notes:
      'The one heather that will grow on chalk — every other garden heath needs acid soil, which is why this species turns up in so many planting plans that have no business containing heathers at all. Flowers from December to April, and is one of the few reliable winter nectar sources for early bees.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Erica%20carnea',
  },
  {
    id: 'hamamelis-intermedia',
    common: "Witch hazel 'Pallida'",
    latin: "Hamamelis x intermedia 'Pallida'",
    genus: 'Hamamelis',
    family: 'Hamamelidaceae',
    type: 'shrub',
    habit: 'multistem',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 1.0,
    plantedSpread: 0.8,
    matureHeight: 4,
    matureSpread: 4,
    yearsToMature: 22,
    budBurst: 104,
    fullLeaf: 146,
    autumnStart: 272,
    leafFall: 316,
    flowerStart: 8,
    flowerEnd: 58,
    colors: {
      leafSpring: '#9ab060',
      leafSummer: '#587a4a',
      leafAutumn: '#e8b93a',
      flower: '#f2d24a',
      bark: '#6b5645',
    },
    sun: ['full', 'dappled'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam'],
    drainage: ['retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'spidery sulphur yellow',
    foliageColour: 'broad mid green, clear yellow in autumn',
    notes:
      'Spidery scented flowers clinging to bare branches through January and February, and then butter-yellow autumn colour — two seasons from one slow, expensive shrub. Will not have lime: on chalk it yellows and sulks whatever you feed it. Nearly all plants are grafted, so pull off any suckers from below the union.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Hamamelis%20intermedia%20Pallida',
  },
  {
    id: 'chimonanthus-praecox',
    common: 'Wintersweet',
    latin: 'Chimonanthus praecox',
    genus: 'Chimonanthus',
    family: 'Calycanthaceae',
    type: 'shrub',
    habit: 'multistem',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 1.0,
    plantedSpread: 0.7,
    matureHeight: 3.5,
    matureSpread: 3,
    yearsToMature: 22,
    budBurst: 106,
    fullLeaf: 146,
    autumnStart: 276,
    leafFall: 316,
    flowerStart: 340,
    flowerEnd: 56,
    colors: {
      leafSpring: '#9ab05c',
      leafSummer: '#587a4a',
      leafAutumn: '#d2c052',
      flower: '#f4e6a8',
      bark: '#75604a',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'waxy translucent pale yellow',
    foliageColour: 'coarse mid green',
    notes:
      'The strongest winter scent of any hardy shrub, from small waxy flowers hanging on bare wood in the darkest weeks. The catch is patience: a young plant may take five to eight years before it flowers at all. Dull the rest of the year, so put it where it is passed in winter and forgotten in summer.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Chimonanthus%20praecox',
  },
  {
    id: 'corylopsis-sinensis',
    common: 'Chinese winter hazel',
    latin: 'Corylopsis sinensis',
    genus: 'Corylopsis',
    family: 'Hamamelidaceae',
    type: 'shrub',
    habit: 'multistem',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 0.8,
    plantedSpread: 0.7,
    matureHeight: 3.5,
    matureSpread: 3.5,
    yearsToMature: 20,
    budBurst: 108,
    fullLeaf: 146,
    autumnStart: 274,
    leafFall: 314,
    flowerStart: 66,
    flowerEnd: 108,
    colors: {
      leafSpring: '#a8ba68',
      leafSummer: '#5f7f4f',
      leafAutumn: '#d8c055',
      flower: '#f4ea9a',
      bark: '#6b5a48',
    },
    sun: ['dappled', 'partial'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam'],
    drainage: ['retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'pale primrose, in hanging tassels',
    foliageColour: 'soft mid green',
    notes:
      'Racemes of cowslip-scented primrose flowers dangling from bare branches in March, before the leaves. Another lime-hater from the witch hazel family, and like them it wants shelter from a late frost that would brown the flowers overnight.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Corylopsis%20sinensis',
  },
  {
    id: 'daphne-odora',
    common: 'Winter daphne',
    latin: 'Daphne odora',
    genus: 'Daphne',
    family: 'Thymelaeaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.4,
    plantedSpread: 0.4,
    matureHeight: 1.2,
    matureSpread: 1.5,
    yearsToMature: 10,
    budBurst: 108,
    fullLeaf: 150,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 20,
    flowerEnd: 92,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#3f6042',
      leafAutumn: '#4f6b48',
      flower: '#f2c8d2',
      flowerLate: '#faeef0',
      bark: '#6b5a48',
    },
    sun: ['dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam'],
    drainage: ['free', 'retentive'],
    hardiness: 'H4',
    sizeClass: 'small',
    flowerColour: 'purple-pink buds opening white',
    foliageColour: 'glossy dark green, often cream-edged',
    notes:
      'One of the great scents of the garden year, in February, from a neat evergreen dome. Daphnes are famously capricious: they hate being moved, hate having their roots disturbed by weeding, and have a habit of dying suddenly and completely for no visible reason after eight or ten good years. Plant it once, in the right place, and leave it entirely alone.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Daphne%20odora',
  },
  {
    id: 'viburnum-bodnantense-dawn',
    common: "Viburnum 'Dawn'",
    latin: "Viburnum x bodnantense 'Dawn'",
    genus: 'Viburnum',
    family: 'Adoxaceae',
    type: 'shrub',
    habit: 'multistem',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 0.8,
    plantedSpread: 0.6,
    matureHeight: 3,
    matureSpread: 2,
    yearsToMature: 12,
    budBurst: 100,
    fullLeaf: 142,
    autumnStart: 274,
    leafFall: 312,
    flowerStart: 304,
    flowerEnd: 82,
    colors: {
      leafSpring: '#9a8a6a',
      leafSummer: '#5f7a52',
      leafAutumn: '#a8703f',
      flower: '#f0c2ce',
      flowerLate: '#f8e4ea',
      bark: '#6b5a48',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'pink fading to white',
    foliageColour: 'bronze-tinted mid green',
    notes:
      'Flowers in flushes on bare stems from November to March, taking whatever the weather gives and starting again after each frost — the most dependable winter-flowering shrub there is. Stiff, upright and frankly graceless in summer, so plant it behind something.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Viburnum%20bodnantense%20Dawn',
  },
  {
    id: 'forsythia-intermedia',
    common: "Forsythia 'Lynwood Variety'",
    latin: "Forsythia x intermedia 'Lynwood Variety'",
    genus: 'Forsythia',
    family: 'Oleaceae',
    type: 'shrub',
    habit: 'multistem',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 0.8,
    plantedSpread: 0.6,
    matureHeight: 3,
    matureSpread: 2.5,
    yearsToMature: 10,
    budBurst: 100,
    fullLeaf: 138,
    autumnStart: 276,
    leafFall: 314,
    flowerStart: 68,
    flowerEnd: 106,
    colors: {
      leafSpring: '#9ab05f',
      leafSummer: '#5a7a4a',
      leafAutumn: '#b8a05a',
      flower: '#f4c81e',
      bark: '#6b5a48',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'strident egg-yolk yellow',
    foliageColour: 'plain mid green',
    notes:
      'Utterly reliable and utterly unfashionable — a fortnight of hard yellow on bare stems in late March and nothing whatever for the other fifty weeks. Prune immediately after flowering, taking a third of the oldest stems out at the base; clipping it into a bun, which is what usually happens, removes next year\'s flower.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Forsythia%20intermedia%20Lynwood',
  },
  {
    id: 'hydrangea-quercifolia',
    common: 'Oak-leaved hydrangea',
    latin: 'Hydrangea quercifolia',
    genus: 'Hydrangea',
    family: 'Hydrangeaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    standing: { from: 268, to: 40 },
    plantedHeight: 0.6,
    plantedSpread: 0.6,
    matureHeight: 2,
    matureSpread: 2.5,
    yearsToMature: 12,
    budBurst: 104,
    fullLeaf: 145,
    autumnStart: 268,
    leafFall: 322,
    flowerStart: 168,
    flowerEnd: 252,
    colors: {
      leafSpring: '#8fa860',
      leafSummer: '#4f6f46',
      leafAutumn: '#8e2f3a',
      flower: '#fbf7ea',
      flowerLate: '#e8bcbe',
      bark: '#8a6a4a',
    },
    sun: ['dappled', 'partial'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam'],
    drainage: ['retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'white cones ageing to dusty pink',
    foliageColour: 'big oak-shaped leaves, deep burgundy in autumn',
    notes:
      'The only hydrangea grown as much for its leaves as its flowers: large lobed leaves turning wine-red and holding into December, over peeling cinnamon bark. White cones from July age through pink and then dry on the plant, so it carries structure into the new year.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Hydrangea%20quercifolia',
  },
  {
    id: 'hydrangea-serrata',
    common: 'Mountain hydrangea',
    latin: 'Hydrangea serrata',
    genus: 'Hydrangea',
    family: 'Hydrangeaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    plantedHeight: 0.4,
    plantedSpread: 0.4,
    matureHeight: 1.2,
    matureSpread: 1.2,
    yearsToMature: 8,
    budBurst: 102,
    fullLeaf: 142,
    autumnStart: 272,
    leafFall: 316,
    flowerStart: 166,
    flowerEnd: 256,
    colors: {
      leafSpring: '#8fa860',
      leafSummer: '#4f6f4a',
      leafAutumn: '#a04a3f',
      flower: '#7f9fd2',
      flowerLate: '#c2a8cc',
      bark: '#7a6248',
    },
    sun: ['dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam'],
    drainage: ['retentive'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'lacecaps, blue on acid soil and pink on lime',
    foliageColour: 'neat mid green, red-tinted in autumn',
    notes:
      'A smaller, finer-boned lacecap than the mophead — better in a small garden and better in a mixed border, where the flat flowerheads sit among other things instead of shouting over them. Flowers on old wood, so cutting it back in spring removes the whole season.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Hydrangea%20serrata',
  },
  {
    id: 'hydrangea-macrophylla',
    common: 'Mophead hydrangea',
    latin: 'Hydrangea macrophylla',
    genus: 'Hydrangea',
    family: 'Hydrangeaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    standing: { from: 272, to: 60 },
    plantedHeight: 0.5,
    plantedSpread: 0.5,
    matureHeight: 1.5,
    matureSpread: 1.8,
    yearsToMature: 8,
    budBurst: 102,
    fullLeaf: 142,
    autumnStart: 274,
    leafFall: 318,
    flowerStart: 168,
    flowerEnd: 258,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#4a7048',
      leafAutumn: '#a8703f',
      flower: '#6f8fca',
      flowerLate: '#a88fb8',
      bark: '#7a6248',
    },
    sun: ['dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam'],
    drainage: ['retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'blue on acid soil, pink on alkaline',
    foliageColour: 'coarse glossy mid green',
    notes:
      'The one plant everybody knows changes colour with soil pH: blue where aluminium is available in acid ground, pink where lime locks it up, and a muddy mauve in between. White cultivars stay white whatever you do. Leave the dead heads on over winter — they protect the buds beneath and look better than the alternative.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Hydrangea%20macrophylla',
  },
  {
    id: 'paeonia-suffruticosa',
    common: 'Tree peony',
    latin: 'Paeonia x suffruticosa',
    genus: 'Paeonia',
    family: 'Paeoniaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    plantedHeight: 0.5,
    plantedSpread: 0.4,
    matureHeight: 1.6,
    matureSpread: 1.5,
    yearsToMature: 12,
    budBurst: 84,
    fullLeaf: 130,
    autumnStart: 268,
    leafFall: 304,
    flowerStart: 130,
    flowerEnd: 158,
    colors: {
      leafSpring: '#9a7a5c',
      leafSummer: '#5f7f5c',
      leafAutumn: '#a87a4a',
      flower: '#f0c2d2',
      flowerLate: '#f8e2e8',
      bark: '#8a7258',
    },
    sun: ['full', 'dappled'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive', 'free'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'enormous silk-textured pink, white or maroon',
    foliageColour: 'grey-green, deeply divided',
    notes:
      'Woody, so it does not die back — a permanent framework of stems carrying flowers the size of a saucer in May. It breaks into growth very early and the flowers are easily ruined by a late frost, so avoid an east-facing spot where morning sun hits frozen buds. Almost always grafted onto a herbaceous rootstock; remove suckers.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Paeonia%20suffruticosa',
  },
  {
    id: 'rhododendron-yakushimanum',
    common: 'Yakushima rhododendron',
    latin: 'Rhododendron yakushimanum',
    genus: 'Rhododendron',
    family: 'Ericaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.4,
    plantedSpread: 0.4,
    matureHeight: 1.3,
    matureSpread: 1.4,
    yearsToMature: 18,
    budBurst: 100,
    fullLeaf: 150,
    autumnStart: 300,
    leafFall: 350,
    flowerStart: 120,
    flowerEnd: 148,
    colors: {
      leafSpring: '#9fb583',
      leafSummer: '#2f5238',
      leafAutumn: '#3f5a3c',
      flower: '#f0c4d4',
      flowerLate: '#faf3f4',
      bark: '#5f4c3e',
    },
    sun: ['dappled', 'partial'],
    soilPh: ['acidic'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'pink buds opening white',
    foliageColour: 'dark green, silver-felted when young',
    notes:
      'The strictest lime-hater in this palette: acid soil or nothing, and no amount of good planting rescues one on chalk. Worth the trouble for a dense low dome that needs no pruning, silvery new growth, and trusses that open from bright pink buds to pure white, so a plant carries both at once in May.',
    source: 'https://www.rhs.org.uk/plants/15799/rhododendron-yakushimanum/details',
  },
  {
    id: 'tamarix-tetrandra',
    common: 'Four-stamen tamarisk',
    latin: 'Tamarix tetrandra',
    genus: 'Tamarix',
    family: 'Tamaricaceae',
    type: 'shrub',
    habit: 'airy',
    foliage: 'deciduous',
    plantedHeight: 0.8,
    plantedSpread: 0.6,
    matureHeight: 3.2,
    matureSpread: 3.2,
    yearsToMature: 15,
    budBurst: 95,
    fullLeaf: 140,
    autumnStart: 285,
    leafFall: 325,
    flowerStart: 135,
    flowerEnd: 162,
    colors: {
      leafSpring: '#a8c483',
      leafSummer: '#8fae7a',
      leafAutumn: '#c8b26a',
      flower: '#e9a8bd',
      bark: '#3a3230',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'large',
    flowerColour: 'light pink plumes',
    foliageColour: 'minute, blue-green, feathery',
    notes:
      'Almost black arching stems carrying clouds of tiny pink flowers in May, on foliage so fine the whole shrub reads as a haze rather than a mass. The classic seaside shrub: it takes salt wind and poor sandy ground where little else stands up. Prune hard straight after flowering, or it goes top-heavy and bare at the base within a few years.',
    source: 'https://www.rhs.org.uk/plants/58409/tamarix-tetrandra/details',
  },
  {
    id: 'rosa-spinosissima',
    common: 'Burnet rose',
    latin: 'Rosa spinosissima',
    genus: 'Rosa',
    family: 'Rosaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    plantedHeight: 0.3,
    plantedSpread: 0.3,
    matureHeight: 0.9,
    matureSpread: 1.3,
    yearsToMature: 5,
    budBurst: 85,
    fullLeaf: 125,
    autumnStart: 280,
    leafFall: 320,
    flowerStart: 145,
    flowerEnd: 178,
    fruitStart: 215,
    fruitEnd: 310,
    colors: {
      leafSpring: '#8fae63',
      leafSummer: '#48663f',
      leafAutumn: '#9a7a3a',
      flower: '#faf5e6',
      fruit: '#1c1a1e',
      bark: '#6b5240',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['chalk', 'loam', 'sand'],
    drainage: ['free'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'creamy white',
    foliageColour: 'small, fern-like, dark green',
    notes:
      'A native rose that suckers into a low prickly thicket rather than making a bush, with fine ferny foliage quite unlike a garden rose. Creamy single flowers all at once in June, then black hips, which nearly no other rose produces. Takes thin sandy soil, sea wind and hard cold — H7, the toughest rose here — but will run where it is happy.',
    source: 'https://www.rhs.org.uk/plants/39326/rosa-spinosissima/details',
  },
  {
    id: 'ligustrum-ovalifolium',
    common: 'Privet hedge',
    latin: 'Ligustrum ovalifolium',
    genus: 'Ligustrum',
    family: 'Oleaceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.45,
    plantedHeight: 0.6,
    plantedSpread: 0.35,
    matureHeight: 2.0,
    matureSpread: 0.8,
    yearsToMature: 8,
    budBurst: 95,
    fullLeaf: 135,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 188,
    flowerEnd: 214,
    colors: {
      leafSpring: '#8fb95e',
      leafSummer: '#4a7040',
      leafAutumn: '#55764a',
      flower: '#f2f0dc',
      bark: '#8a8070',
    },
    sun: ['full', 'dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'creamy white, mostly lost to clipping',
    foliageColour: 'glossy mid green',
    notes:
      'The fastest hedge here at nearly half a metre a year, which is both why it is everywhere and why it is disliked: it wants cutting two or three times a season and its roots strip the ground either side for a metre. Semi-evergreen in a hard winter. Clipping removes the midsummer flower, so a privet hedge and a flowering privet are two different plants.',
    source: 'https://www.rhs.org.uk/plants/91966/ligustrum-ovalifolium/details',
  },
  {
    id: 'prunus-lusitanica',
    common: 'Portugal laurel',
    latin: 'Prunus lusitanica',
    genus: 'Prunus',
    family: 'Rosaceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.3,
    plantedHeight: 0.8,
    plantedSpread: 0.5,
    matureHeight: 2.5,
    matureSpread: 1.2,
    yearsToMature: 10,
    budBurst: 105,
    fullLeaf: 150,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 158,
    flowerEnd: 182,
    fruitStart: 240,
    fruitEnd: 305,
    colors: {
      leafSpring: '#8fb060',
      leafSummer: '#2f5236',
      leafAutumn: '#35583c',
      flower: '#f4f1e4',
      fruit: '#2e1a35',
      bark: '#7d3f38',
    },
    sun: ['full', 'dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'white, scented, in June',
    foliageColour: 'glossy dark green on red stalks',
    notes:
      'The laurel worth specifying. Smaller, neater leaves than cherry laurel, so clipping does not leave the half-cut leaves that make a shorn cherry laurel look mutilated, and the dark red leaf stalks give it a warmth the other has not got. Takes shallow chalk, which most evergreens will not. Slower, at about 30 cm a year.',
    source: 'https://www.rhs.org.uk/plants/14003/prunus-lusitanica/details',
  },
  {
    id: 'ilex-crenata-dark-green',
    common: 'Japanese holly',
    latin: "Ilex crenata Dark Green ('Icoprins11')",
    genus: 'Ilex',
    family: 'Aquifoliaceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.12,
    plantedHeight: 0.3,
    plantedSpread: 0.3,
    matureHeight: 1.0,
    matureSpread: 0.8,
    yearsToMature: 12,
    budBurst: 108,
    fullLeaf: 150,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 130,
    flowerEnd: 150,
    colors: {
      leafSpring: '#7fa84e',
      leafSummer: '#2f5133',
      leafAutumn: '#365a39',
      flower: '#eceee0',
      bark: '#6f6a5c',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'insignificant white',
    foliageColour: 'small, glossy, very dark green',
    notes:
      'The standard substitute for box now that blight and box tree moth have made box a gamble, and close enough at a glance that most people do not notice the swap. Same slow ten to twelve centimetres a year, so it is the same decade of patience. The catch is soil: it wants neutral to slightly acid ground and sulks on chalk, exactly where box is happiest.',
    source: 'https://www.rhs.org.uk/plants/325173/ilex-crenata-dark-green-icoprins11-pbr/details',
  },
  {
    id: 'euonymus-green-rocket',
    common: 'Japanese spindle',
    latin: "Euonymus japonicus 'Green Rocket'",
    genus: 'Euonymus',
    family: 'Celastraceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.18,
    plantedHeight: 0.4,
    plantedSpread: 0.25,
    matureHeight: 1.2,
    matureSpread: 0.5,
    yearsToMature: 6,
    budBurst: 105,
    fullLeaf: 148,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 165,
    flowerEnd: 190,
    colors: {
      leafSpring: '#95bb5c',
      leafSummer: '#37613a',
      leafAutumn: '#3e6a3f',
      flower: '#dfe4c8',
      bark: '#7f7a68',
    },
    sun: ['full', 'dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'insignificant green-white',
    foliageColour: 'glossy dark green, leathery',
    notes:
      'Naturally narrow and upright, so it makes a low hedge without much help and holds a crisp edge with one cut a year. Tough about salt wind, city air and shade, which is why it turns up in car parks. Watch for euonymus scale, which coats the stems in what looks like white scurf and is very hard to shift once established.',
    source: 'https://www.rhs.org.uk/plants/252158/euonymus-japonicus-green-rocket/details',
  },
  {
    id: 'osmanthus-burkwoodii',
    common: 'Burkwood osmanthus',
    latin: 'Osmanthus × burkwoodii',
    genus: 'Osmanthus',
    family: 'Oleaceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.2,
    plantedHeight: 0.6,
    plantedSpread: 0.5,
    matureHeight: 2.0,
    matureSpread: 1.5,
    yearsToMature: 12,
    budBurst: 105,
    fullLeaf: 150,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 105,
    flowerEnd: 132,
    colors: {
      leafSpring: '#88ac58',
      leafSummer: '#33573a',
      leafAutumn: '#3a5f3f',
      flower: '#f6f4e8',
      bark: '#7a7060',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'white, powerfully scented, in April',
    foliageColour: 'small, dark, faintly toothed green',
    notes:
      'A hedge worth walking past in April, when the scent carries further than the plant is tall. Slow and dense, and it clips as tightly as box at four times the leaf size. The one rule is to cut it straight after flowering — a spring trim takes off the buds and wastes the entire point of growing it.',
    source: 'https://www.rhs.org.uk/plants/89015/burkwood-osmanthus/details',
  },
  {
    id: 'pittosporum-silver-queen',
    common: 'Tawhiwhi',
    latin: "Pittosporum tenuifolium 'Silver Queen'",
    genus: 'Pittosporum',
    family: 'Pittosporaceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.25,
    plantedHeight: 0.7,
    plantedSpread: 0.4,
    matureHeight: 2.2,
    matureSpread: 1.2,
    yearsToMature: 12,
    budBurst: 108,
    fullLeaf: 152,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 150,
    flowerEnd: 175,
    colors: {
      leafSpring: '#c6d3b4',
      leafSummer: '#9db08e',
      leafAutumn: '#a3b394',
      flower: '#3a2338',
      bark: '#2f2a2a',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'tiny dark purple, scented at night',
    foliageColour: 'wavy grey-green edged cream',
    notes:
      'Grown for the contrast between near-black stems and pale wavy leaves, which is why florists strip it and why it lifts a dark corner. The flowers are almost invisible but scent the garden after dark in June. H4 is the warning: a cold dry east wind can brown the whole plant, so it wants shelter inland and is happiest near the coast.',
    source: 'https://www.rhs.org.uk/plants/46330/pittosporum-tenuifolium-silver-queen-fv/details',
  },
  {
    id: 'lonicera-nitida-baggesens-gold',
    common: 'Shrubby honeysuckle',
    latin: "Lonicera nitida 'Baggesen's Gold'",
    genus: 'Lonicera',
    family: 'Caprifoliaceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.35,
    plantedHeight: 0.3,
    plantedSpread: 0.3,
    matureHeight: 1.2,
    matureSpread: 0.9,
    yearsToMature: 6,
    budBurst: 95,
    fullLeaf: 140,
    autumnStart: 295,
    leafFall: 340,
    flowerStart: 115,
    flowerEnd: 140,
    colors: {
      leafSpring: '#d8dc72',
      leafSummer: '#c2cc5c',
      leafAutumn: '#a8b45e',
      flower: '#f0eedc',
      bark: '#6f6450',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'tiny cream, easily missed',
    foliageColour: 'tiny golden-yellow',
    notes:
      'The fast answer to a low hedge: box leaf size, box density, at three times box speed. That speed is the drawback — it needs two or three cuts a season or it goes shaggy, and an unfed plant flops open in the middle and never really closes again. The gold holds best in full sun and goes lime-green in shade.',
    source: 'https://www.rhs.org.uk/plants/78340/i-lonicera-nitida-i-baggesen-s-gold/details',
  },
  {
    id: 'escallonia-apple-blossom',
    common: 'Escallonia',
    latin: "Escallonia 'Apple Blossom'",
    genus: 'Escallonia',
    family: 'Escalloniaceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.3,
    plantedHeight: 0.6,
    plantedSpread: 0.4,
    matureHeight: 2.0,
    matureSpread: 1.2,
    yearsToMature: 8,
    budBurst: 100,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 165,
    flowerEnd: 228,
    colors: {
      leafSpring: '#8fb857',
      leafSummer: '#3e6a3d',
      leafAutumn: '#457043',
      flower: '#f0b7c2',
      flowerLate: '#e8d6d8',
      bark: '#7a6a58',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'pale apple-blossom pink',
    foliageColour: 'small, glossy, dark green',
    notes:
      'Nearly the only evergreen hedge that flowers properly, and it carries the pale pink for two months from June. Built for the coast — it shrugs off salt wind that scorches everything else. Two things against it inland: H4 means a hard winter can cut it back, and escallonia leaf spot has become common enough that a clipped hedge sometimes thins from the base up.',
    source: 'https://www.rhs.org.uk/plants/96211/escallonia-apple-blossom/details',
  },
  {
    id: 'berberis-darwinii',
    common: "Darwin's barberry",
    latin: 'Berberis darwinii',
    genus: 'Berberis',
    family: 'Berberidaceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.25,
    plantedHeight: 0.5,
    plantedSpread: 0.4,
    matureHeight: 1.8,
    matureSpread: 1.2,
    yearsToMature: 10,
    budBurst: 100,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 100,
    flowerEnd: 140,
    fruitStart: 228,
    fruitEnd: 292,
    colors: {
      leafSpring: '#7ea84c',
      leafSummer: '#2f5433',
      leafAutumn: '#365a3a',
      flower: '#e8871e',
      fruit: '#2b3555',
      bark: '#6f5a44',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'rich orange, red in bud',
    foliageColour: 'small, glossy, spined dark green',
    notes:
      'The only hedge in this palette that is genuinely impenetrable — small holly-like leaves on spined shoots, and nothing walks through it twice. Hung with orange flowers in April, which is an unusual colour to have at that height and season, then blue-black berries the birds strip by September. Clip after flowering; it resents hard cutting into old wood.',
    source: 'https://www.rhs.org.uk/plants/2105/berberis-darwinii/details',
  },
  {
    id: 'berberis-thunbergii-atropurpurea',
    common: 'Purple Japanese barberry',
    latin: 'Berberis thunbergii f. atropurpurea',
    genus: 'Berberis',
    family: 'Berberidaceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'deciduous',
    clipped: true,
    annualGrowth: 0.2,
    plantedHeight: 0.3,
    plantedSpread: 0.3,
    matureHeight: 1.0,
    matureSpread: 0.9,
    yearsToMature: 8,
    budBurst: 92,
    fullLeaf: 125,
    autumnStart: 275,
    leafFall: 320,
    flowerStart: 118,
    flowerEnd: 140,
    fruitStart: 255,
    fruitEnd: 342,
    colors: {
      leafSpring: '#8a4a5c',
      leafSummer: '#5e2b3f',
      leafAutumn: '#b93a25',
      flower: '#e8dc7a',
      fruit: '#c22a1e',
      bark: '#7a5a48',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'pale yellow, red-tinged',
    foliageColour: 'dark reddish-purple, scarlet in autumn',
    notes:
      'A low barrier hedge that earns its place three times over: purple all summer, scarlet in October, then glossy red berries held on bare thorny twigs into January. The purple needs full sun and goes muddy green in shade. Thorny enough to be unpleasant to weed around, which is worth knowing before edging a path with it.',
    source: 'https://www.rhs.org.uk/plants/99268/berberis-thunbergii-f-atropurpurea/details',
  },
  {
    id: 'sarcococca-hedge',
    common: 'Christmas box edging',
    latin: 'Sarcococca confusa',
    genus: 'Sarcococca',
    family: 'Buxaceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'evergreen',
    clipped: true,
    annualGrowth: 0.12,
    plantedHeight: 0.3,
    plantedSpread: 0.3,
    matureHeight: 0.7,
    matureSpread: 0.6,
    yearsToMature: 8,
    budBurst: 110,
    fullLeaf: 150,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 338,
    flowerEnd: 76,
    fruitStart: 120,
    fruitEnd: 336,
    colors: {
      leafSpring: '#7fa860',
      leafSummer: '#2f5238',
      leafAutumn: '#3f5f42',
      flower: '#f8f6ea',
      fruit: '#241f26',
      bark: '#4f6642',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'insignificant cream, but scented in January',
    foliageColour: 'narrow, glossy, very dark green',
    notes:
      'Kept as a separate entry from the loose shrub because a clipped 70 cm edging and a 1.5 m mound do quite different jobs. The reason to use it rather than box is the scent: nothing to look at, but in January it carries across a garden from a plant you cannot see. Slow, shade-tolerant to the point of preferring it, and untroubled by the blight that is ruining box.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Sarcococca%20confusa',
  },
  {
    id: 'callicarpa-profusion',
    common: 'Beautyberry',
    latin: "Callicarpa bodinieri var. giraldii 'Profusion'",
    genus: 'Callicarpa',
    family: 'Lamiaceae',
    type: 'shrub',
    habit: 'multistem',
    foliage: 'deciduous',
    plantedHeight: 0.6,
    plantedSpread: 0.4,
    matureHeight: 2.5,
    matureSpread: 2.0,
    yearsToMature: 10,
    budBurst: 105,
    fullLeaf: 140,
    autumnStart: 272,
    leafFall: 315,
    flowerStart: 190,
    flowerEnd: 215,
    fruitStart: 270,
    fruitEnd: 355,
    colors: {
      leafSpring: '#9a7f8c',
      leafSummer: '#5c7a4e',
      leafAutumn: '#c98aa0',
      flower: '#c4a4d4',
      fruit: '#8a4fbe',
      bark: '#7a6b5e',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'small lilac, insignificant',
    foliageColour: 'purplish young, rosy pink in autumn',
    notes:
      'Grown for one thing: tight clusters of violet berries in a colour nothing else in a garden produces, held on bare stems from October into December. Deliberately not modelled as a clipped subject — it fruits on the previous season’s wood, so a clipped plant gives no berries at all. Plant three or more together; a lone one sets almost nothing.',
    source: 'https://www.rhs.org.uk/plants/96060/callicarpa-bodinieri-var-giraldii-profusion/details',
  },
  {
    id: 'fatsia-japonica',
    common: 'Japanese aralia',
    latin: 'Fatsia japonica',
    genus: 'Fatsia',
    family: 'Araliaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.6,
    plantedSpread: 0.5,
    matureHeight: 2.5,
    matureSpread: 2.5,
    yearsToMature: 10,
    budBurst: 108,
    fullLeaf: 150,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 288,
    flowerEnd: 325,
    fruitStart: 330,
    fruitEnd: 60,
    colors: {
      leafSpring: '#7fae52',
      leafSummer: '#2f5a38',
      leafAutumn: '#375f3d',
      flower: '#f2efdc',
      fruit: '#20242e',
      bark: '#8a8272',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'creamy white drumsticks in late autumn',
    foliageColour: 'huge, glossy, hand-shaped dark green',
    notes:
      'The best big evergreen for a dark corner, with leaves up to 45 cm across that read as tropical in a garden that is anything but. Flowers in November when almost nothing else does, in creamy spheres on branched stalks, then black fruit. Sun scorches it and cold dry wind browns it, so a sheltered north or east wall is where it does its best work.',
    source: 'https://www.rhs.org.uk/plants/7147/fatsia-japonica/details',
  },
  {
    id: 'viburnum-davidii',
    common: "David's viburnum",
    latin: 'Viburnum davidii',
    genus: 'Viburnum',
    family: 'Viburnaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.3,
    plantedSpread: 0.4,
    matureHeight: 1.0,
    matureSpread: 1.5,
    yearsToMature: 10,
    budBurst: 106,
    fullLeaf: 148,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 135,
    flowerEnd: 165,
    fruitStart: 250,
    fruitEnd: 40,
    colors: {
      leafSpring: '#7ba854',
      leafSummer: '#2f5738',
      leafAutumn: '#37603e',
      flower: '#f4f2e6',
      fruit: '#3f6fa8',
      bark: '#7a7264',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'dull white, insignificant',
    foliageColour: 'deeply veined, leathery dark green',
    notes:
      'A low dome of ribbed leathery leaves that does the job of ground cover without looking like ground cover — the most useful evergreen filler here for a shaded bed. The metallic blue fruit is the reason people plant it and the reason they are disappointed: you need a male and a female plant, and most gardens have one.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Viburnum%20davidii',
  },
  {
    id: 'hebe-rakaiensis',
    common: 'Shrubby veronica',
    latin: 'Hebe rakaiensis',
    genus: 'Hebe',
    family: 'Plantaginaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.25,
    plantedSpread: 0.3,
    matureHeight: 0.9,
    matureSpread: 1.2,
    yearsToMature: 8,
    budBurst: 100,
    fullLeaf: 142,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 172,
    flowerEnd: 205,
    colors: {
      leafSpring: '#a8c96a',
      leafSummer: '#6f9a55',
      leafAutumn: '#79a05d',
      flower: '#f6f4ea',
      bark: '#7f7a66',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'white spikes in July',
    foliageColour: 'small, bright apple green',
    notes:
      'Makes a tight bright-green bun entirely on its own, with no clipping at all, which is why it turns up wherever a designer wants the look of topiary without the maintenance. The white July flowers are a bonus rather than the point. Short-lived by shrub standards — reckon on ten to fifteen years before it goes woody and gappy and wants replacing.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Hebe%20rakaiensis',
  },
  {
    id: 'skimmia-rubella',
    common: 'Skimmia',
    latin: "Skimmia japonica 'Rubella'",
    genus: 'Skimmia',
    family: 'Rutaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.3,
    plantedSpread: 0.3,
    matureHeight: 1.2,
    matureSpread: 1.2,
    yearsToMature: 10,
    budBurst: 106,
    fullLeaf: 148,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 300,
    flowerEnd: 130,
    colors: {
      leafSpring: '#7fa855',
      leafSummer: '#31563a',
      leafAutumn: '#39603f',
      flower: '#a8203c',
      flowerLate: '#f2ece0',
      bark: '#6f6a58',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'small',
    flowerColour: 'deep red buds all winter, opening white in April',
    foliageColour: 'aromatic, glossy dark green',
    notes:
      'Grown for the buds, not the flowers: tight heads of dark red stay closed from October right through to April, so it carries a shaded bed through the whole winter, then opens to scented white. This one is male, which is worth knowing — it will never carry berries, and it exists to pollinate the females that do. Yellows badly on chalk.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Skimmia%20japonica%20Rubella',
  },
  {
    id: 'pieris-katsura',
    common: 'Lily-of-the-valley bush',
    latin: "Pieris japonica 'Katsura'",
    genus: 'Pieris',
    family: 'Ericaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'evergreen',
    plantedHeight: 0.4,
    plantedSpread: 0.4,
    matureHeight: 1.8,
    matureSpread: 1.5,
    yearsToMature: 12,
    budBurst: 96,
    fullLeaf: 140,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 82,
    flowerEnd: 122,
    colors: {
      leafSpring: '#9c3f52',
      leafSummer: '#375c3c',
      leafAutumn: '#3f6442',
      flower: '#c46a90',
      flowerLate: '#e8c2cf',
      bark: '#6f5f50',
    },
    sun: ['dappled', 'partial'],
    soilPh: ['acidic'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'dark rose-pink bells in spring',
    foliageColour: 'wine-red young growth over dark green',
    notes:
      'Two shows in one plant: drooping strings of rose bells in March, then a flush of wine-red new leaves that reads from across a garden as though it is flowering twice. Strictly for acid soil — on anything limy the leaves go yellow between the veins and it never recovers. Late frost catches the flowers, so keep it off an east-facing spot that thaws fast.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Pieris%20japonica%20Katsura',
  },
  {
    id: 'camellia-donation',
    common: 'Camellia',
    latin: "Camellia × williamsii 'Donation'",
    genus: 'Camellia',
    family: 'Theaceae',
    type: 'shrub',
    habit: 'columnar',
    foliage: 'evergreen',
    plantedHeight: 0.6,
    plantedSpread: 0.4,
    matureHeight: 3.0,
    matureSpread: 1.8,
    yearsToMature: 15,
    budBurst: 104,
    fullLeaf: 146,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 55,
    flowerEnd: 118,
    colors: {
      leafSpring: '#7fa851',
      leafSummer: '#2a4f33',
      leafAutumn: '#31573a',
      flower: '#e88bab',
      flowerLate: '#f0b8c8',
      bark: '#6f6252',
    },
    sun: ['dappled', 'partial'],
    soilPh: ['acidic'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'clear semi-double pink, February to April',
    foliageColour: 'glossy dark green',
    notes:
      'The camellia to plant if you plant only one: free with its clear pink semi-doubles from late February, and unlike most it drops its dead flowers cleanly instead of hanging onto brown rags. Acid soil only. Never plant it facing east — a night frost on frozen buds followed by early sun turns the whole display brown by lunchtime.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Camellia%20williamsii%20Donation',
  },
  {
    id: 'yucca-filamentosa',
    common: "Adam's needle",
    latin: 'Yucca filamentosa',
    genus: 'Yucca',
    family: 'Asparagaceae',
    type: 'shrub',
    habit: 'spire',
    foliage: 'evergreen',
    plantedHeight: 0.4,
    plantedSpread: 0.5,
    matureHeight: 1.6,
    matureSpread: 1.2,
    yearsToMature: 8,
    budBurst: 110,
    fullLeaf: 152,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 196,
    flowerEnd: 232,
    standing: { from: 232, to: 60 },
    colors: {
      leafSpring: '#9ab288',
      leafSummer: '#7d9a70',
      leafAutumn: '#84a077',
      flower: '#f4f0dc',
      bark: '#8a8270',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'ivory bells on a two-metre spike',
    foliageColour: 'stiff blue-green swords with curling white threads',
    notes:
      'A rosette of rigid swords that holds its shape all year and reads as architecture rather than planting — the strongest full stop in this palette. Every few years it throws a two-metre panicle of ivory bells in high summer, and the dead spike stands well into winter. Wants sharp drainage and full sun; on wet clay the crown rots.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Yucca%20filamentosa',
  },
  {
    id: 'corylus-maxima-purpurea',
    common: 'Purple filbert',
    latin: "Corylus maxima 'Purpurea'",
    genus: 'Corylus',
    family: 'Betulaceae',
    type: 'shrub',
    habit: 'multistem',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 1.0,
    plantedSpread: 0.8,
    matureHeight: 4.5,
    matureSpread: 4.0,
    yearsToMature: 15,
    budBurst: 92,
    fullLeaf: 128,
    autumnStart: 268,
    leafFall: 310,
    flowerStart: 20,
    flowerEnd: 60,
    fruitStart: 240,
    fruitEnd: 285,
    colors: {
      leafSpring: '#6a2f42',
      leafSummer: '#4a2033',
      leafAutumn: '#8a5a3a',
      flower: '#9a5a6a',
      fruit: '#9a7a4a',
      bark: '#6f5a4e',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'purple-flushed catkins in February',
    foliageColour: 'deep beetroot-purple, huge and rounded',
    notes:
      'Purple catkins on bare stems in February, then enormous rounded beetroot-purple leaves — heavier and darker than a purple beech, and useful as a screen that is not a hedge. Coppice it every few years to keep it in bounds and get bigger leaves. Purple-shelled cobnuts follow if squirrels leave any.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Corylus%20maxima%20Purpurea',
  },
  {
    id: 'cotoneaster-horizontalis',
    common: 'Wall spray',
    latin: 'Cotoneaster horizontalis',
    genus: 'Cotoneaster',
    family: 'Rosaceae',
    type: 'shrub',
    habit: 'mound',
    foliage: 'deciduous',
    plantedHeight: 0.3,
    plantedSpread: 0.4,
    matureHeight: 1.0,
    matureSpread: 2.0,
    yearsToMature: 10,
    budBurst: 88,
    fullLeaf: 128,
    autumnStart: 272,
    leafFall: 330,
    flowerStart: 132,
    flowerEnd: 158,
    fruitStart: 250,
    fruitEnd: 30,
    colors: {
      leafSpring: '#7fa855',
      leafSummer: '#3f6b3f',
      leafAutumn: '#b8341e',
      flower: '#e8c0c4',
      fruit: '#c4241a',
      bark: '#6f5f52',
    },
    sun: ['full', 'dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'small',
    flowerColour: 'tiny pink stars, alive with bees in May',
    foliageColour: 'small glossy green, scarlet in autumn',
    notes:
      'Branches arranged in a flat herringbone that presses itself against a wall or spreads over a bank — a genuinely distinctive structure, visible all winter once the leaves drop. Scarlet leaves and red berries together in October. Bees work the tiny pink flowers so hard in May that the whole plant hums.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Cotoneaster%20horizontalis',
  },
  {
    id: 'nandina-domestica',
    common: 'Heavenly bamboo',
    latin: 'Nandina domestica',
    genus: 'Nandina',
    family: 'Berberidaceae',
    type: 'shrub',
    habit: 'multistem',
    foliage: 'evergreen',
    plantedHeight: 0.4,
    plantedSpread: 0.3,
    matureHeight: 1.8,
    matureSpread: 1.2,
    yearsToMature: 10,
    budBurst: 100,
    fullLeaf: 145,
    autumnStart: 285,
    leafFall: 345,
    flowerStart: 172,
    flowerEnd: 205,
    fruitStart: 275,
    fruitEnd: 60,
    colors: {
      leafSpring: '#b04a3a',
      leafSummer: '#4a7048',
      leafAutumn: '#b03a2a',
      flower: '#f4f0e4',
      fruit: '#c8201e',
      bark: '#8a7458',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'sprays of small white stars in midsummer',
    foliageColour: 'red new growth, green summer, crimson winter',
    notes:
      'Not a bamboo at all, though the upright canes and fine divided leaves make the name obvious. Three colours a year on the same plant: red new growth, green through summer, crimson from October, plus white flowers and red berries. Upright and narrow, so it suits a tight space or a pot by a door.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Nandina%20domestica',
  },
  {
    id: 'salix-britzensis',
    common: 'Scarlet willow',
    latin: "Salix alba var. vitellina 'Britzensis'",
    genus: 'Salix',
    family: 'Salicaceae',
    type: 'shrub',
    habit: 'multistem',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 1.0,
    plantedSpread: 0.6,
    matureHeight: 3.5,
    matureSpread: 2.5,
    yearsToMature: 6,
    budBurst: 82,
    fullLeaf: 122,
    autumnStart: 270,
    leafFall: 312,
    flowerStart: 68,
    flowerEnd: 98,
    colors: {
      leafSpring: '#a8c46a',
      leafSummer: '#6f9060',
      leafAutumn: '#d8c04a',
      flower: '#d8d49a',
      bark: '#e0621e',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['retentive', 'waterlogged', 'bog'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'silver catkins on bare orange stems',
    foliageColour: 'narrow grey-green, yellow in autumn',
    notes:
      'Grown entirely for the winter stems, which burn orange-scarlet from November to March and are brightest on wood grown the previous season — so coppice it hard every year or two in early spring, exactly as you would a dogwood. Will grow in ground too wet for almost anything else. Roots are invasive near drains.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Salix%20alba%20vitellina%20Britzensis',
  },
];
