import type { Species } from '../types';

/** Trees — 37 of them. Appending here adds the plant to the library. */
export const TREES: Species[] = [
  {
    id: 'betula-jacquemontii',
    common: 'West Himalayan birch',
    latin: 'Betula utilis var. jacquemontii',
    genus: 'Betula',
    family: 'Betulaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 3.0,
    plantedSpread: 1.2,
    matureHeight: 14,
    matureSpread: 6.5,
    yearsToMature: 32,
    budBurst: 95,
    fullLeaf: 125,
    autumnStart: 274,
    leafFall: 320,
    flowerStart: 85,
    flowerEnd: 112,
    colors: {
      leafSpring: '#a8c96b',
      leafSummer: '#5d8c47',
      leafAutumn: '#e3bb45',
      flower: '#c2bd6d',
      bark: '#f4f2ea',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'large',
    flowerColour: 'green-yellow catkins',
    foliageColour: 'mid green',
    notes:
      'Vigorous, with brilliant white bark on trunk and larger branches; clear yellow in autumn. Reaches roughly 10–12 m in twenty years, well over 12 m eventually. Casts light, dappled shade rather than dense.',
    source: 'https://www.rhs.org.uk/plants/94928/betula-utilis-var-jacquemontii/details',
  },
  {
    id: 'amelanchier-lamarckii',
    common: 'Snowy mespilus',
    latin: 'Amelanchier lamarckii',
    genus: 'Amelanchier',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'multistem',
    foliage: 'deciduous',
    plantedHeight: 2.2,
    plantedSpread: 1.0,
    matureHeight: 7,
    matureSpread: 5,
    yearsToMature: 45,
    budBurst: 90,
    fullLeaf: 118,
    autumnStart: 266,
    leafFall: 310,
    flowerStart: 96,
    flowerEnd: 118,
    colors: {
      leafSpring: '#b08a63',
      leafSummer: '#5f8f52',
      leafAutumn: '#d4562e',
      flower: '#fbf7f0',
      bark: '#6f5a4a',
    },
    sun: ['full', 'partial', 'dappled'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'white',
    foliageColour: 'mid green, bronze when young',
    notes:
      'Multi-stemmed small tree. A profusion of star-shaped white flowers in April with bronze-tinged young leaves, then orange to red autumn colour. About 4–5 m in twenty years despite a larger ultimate size. RHS Award of Garden Merit.',
    source: 'https://www.rhs.org.uk/plants/26602/amelanchier-lamarckii/details',
  },
  {
    id: 'acer-osakazuki',
    common: 'Japanese maple',
    latin: "Acer palmatum 'Ōsakazuki'",
    genus: 'Acer',
    family: 'Sapindaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 1.5,
    plantedSpread: 1.0,
    matureHeight: 6,
    matureSpread: 5,
    yearsToMature: 45,
    budBurst: 100,
    fullLeaf: 130,
    autumnStart: 272,
    leafFall: 318,
    flowerStart: 125,
    flowerEnd: 142,
    colors: {
      leafSpring: '#7fa055',
      leafSummer: '#4f7f3f',
      leafAutumn: '#d92b1f',
      flower: '#8c2f39',
      bark: '#7a6154',
    },
    sun: ['dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'small red',
    foliageColour: 'green, scarlet in autumn',
    notes:
      'Large rounded deciduous shrub or small tree, about 4 × 3 m over twenty years. Seven-lobed leaves turn a brilliant orange-scarlet in autumn — among the most reliable of any Japanese maple. Wants shelter from cold wind and hot afternoon sun.',
    source: 'https://www.rhs.org.uk/plants/235/acer-palmatum-(elegans-group)-osakazuki-/details',
  },
  {
    id: 'eucalyptus-gunnii',
    common: 'Cider gum',
    latin: 'Eucalyptus gunnii',
    genus: 'Eucalyptus',
    family: 'Myrtaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'evergreen',
    plantedHeight: 2.0,
    plantedSpread: 0.8,
    matureHeight: 18,
    matureSpread: 7,
    yearsToMature: 30,
    budBurst: 100,
    fullLeaf: 145,
    autumnStart: 300,
    leafFall: 340,
    flowerStart: 190,
    flowerEnd: 262,
    colors: {
      leafSpring: '#b3c4b6',
      leafSummer: '#8fa89a',
      leafAutumn: '#8fa89a',
      flower: '#eef0e2',
      bark: '#cbc0b0',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H5',
    sizeClass: 'large',
    flowerColour: 'creamy white',
    foliageColour: 'silver blue-grey',
    notes:
      'By some distance the fastest thing here — a metre or more a year while young, and 15 m within twenty years if left alone. Rounded silver-blue juvenile leaves give way to longer grey-green adult ones unless you coppice it hard each spring to keep the juvenile foliage. Evergreen, so it shades in winter too.',
    source: 'https://www.rhs.org.uk/plants/7141/eucalyptus-gunnii/details',
  },
  {
    id: 'magnolia-soulangeana',
    common: 'Saucer magnolia',
    latin: 'Magnolia × soulangeana',
    genus: 'Magnolia',
    family: 'Magnoliaceae',
    type: 'tree',
    habit: 'multistem',
    foliage: 'deciduous',
    plantedHeight: 1.8,
    plantedSpread: 1.2,
    matureHeight: 7,
    matureSpread: 7,
    yearsToMature: 40,
    budBurst: 118,
    fullLeaf: 148,
    autumnStart: 275,
    leafFall: 315,
    flowerStart: 78,
    flowerEnd: 116,
    flowersOnBareWood: true,
    colors: {
      leafSpring: '#6f8f52',
      leafSummer: '#4e7a45',
      leafAutumn: '#c9b46a',
      flower: '#f4e2ea',
      flowerLate: '#e2b6c8',
      bark: '#8a8378',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'white flushed pink-purple',
    foliageColour: 'mid green',
    notes:
      'Big goblet flowers open on completely bare branches in March and April, weeks before a leaf shows — the reason it is worth the space. Wide-spreading and slow, roughly as broad as it is tall. Late frosts brown the flowers, so it wants shelter.',
    source: 'https://www.rhs.org.uk/plants/11116/magnolia-x-soulangeana/details',
  },
  {
    id: 'malus-evereste',
    common: 'Crab apple',
    latin: "Malus 'Evereste'",
    genus: 'Malus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.0,
    plantedSpread: 1.0,
    matureHeight: 7,
    matureSpread: 6,
    yearsToMature: 35,
    budBurst: 98,
    fullLeaf: 128,
    autumnStart: 272,
    leafFall: 315,
    flowerStart: 112,
    flowerEnd: 142,
    fruitStart: 240,
    fruitEnd: 358,
    colors: {
      leafSpring: '#7fa356',
      leafSummer: '#4f7c40',
      leafAutumn: '#d1a03e',
      flower: '#faf0ea',
      flowerLate: '#f2d6da',
      fruit: '#d9541f',
      bark: '#6f5f4e',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'red buds opening white',
    foliageColour: 'mid green',
    notes:
      'Conical small tree that earns its place twice: red-budded white blossom in late April, then orange-red fruit from September that hangs on well past leaf fall. Reliable and disease-resistant. RHS Award of Garden Merit.',
    source: 'https://www.rhs.org.uk/plants/58567/malus-evereste/details',
  },
  {
    id: 'prunus-serrula',
    common: 'Tibetan cherry',
    latin: 'Prunus serrula',
    genus: 'Prunus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.5,
    plantedSpread: 1.2,
    matureHeight: 9,
    matureSpread: 8,
    yearsToMature: 35,
    budBurst: 100,
    fullLeaf: 128,
    autumnStart: 268,
    leafFall: 312,
    flowerStart: 108,
    flowerEnd: 130,
    colors: {
      leafSpring: '#7fa356',
      leafSummer: '#4a7440',
      leafAutumn: '#d3a747',
      flower: '#fbf6f2',
      bark: '#8c3a20',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'small white',
    foliageColour: 'mid green, yellow in autumn',
    notes:
      'Grown for its bark: a glossy mahogany-red trunk that peels in bands and looks polished, at its best in winter when there is nothing else to look at. The white blossom is modest by cherry standards. Lift the crown so the trunk shows.',
    source: 'https://www.rhs.org.uk/plants/13584/prunus-serrula/details',
  },
  {
    id: 'sorbus-aucuparia',
    common: 'Rowan',
    latin: 'Sorbus aucuparia',
    genus: 'Sorbus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.5,
    plantedSpread: 1.0,
    matureHeight: 12,
    matureSpread: 7,
    yearsToMature: 30,
    budBurst: 96,
    fullLeaf: 124,
    autumnStart: 262,
    leafFall: 305,
    flowerStart: 130,
    flowerEnd: 156,
    fruitStart: 215,
    fruitEnd: 320,
    colors: {
      leafSpring: '#8fb05e',
      leafSummer: '#4f7844',
      leafAutumn: '#d4552e',
      flower: '#f6f2e6',
      fruit: '#d93b1c',
      bark: '#8a8a80',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'large',
    flowerColour: 'creamy white',
    foliageColour: 'fine pinnate green',
    notes:
      'Light, airy and upright, with fine pinnate leaves that cast much less shade than the canopy size suggests. Flat heads of cream flowers in May, then heavy bunches of orange-red berries from August — usually stripped by blackbirds well before Christmas.',
    source: 'https://www.rhs.org.uk/plants/17368/sorbus-aucuparia/details',
  },
  {
    id: 'ilex-aquifolium',
    common: 'English holly',
    latin: 'Ilex aquifolium',
    genus: 'Ilex',
    family: 'Aquifoliaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'evergreen',
    plantedHeight: 1.5,
    plantedSpread: 0.8,
    matureHeight: 8,
    matureSpread: 4,
    yearsToMature: 45,
    budBurst: 118,
    fullLeaf: 158,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 140,
    flowerEnd: 168,
    fruitStart: 276,
    fruitEnd: 62,
    colors: {
      leafSpring: '#8fb055',
      leafSummer: '#2c4d33',
      leafAutumn: '#3a5a3f',
      flower: '#f4f0e2',
      fruit: '#c0271e',
      bark: '#8a8578',
    },
    sun: ['full', 'dappled', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'large',
    flowerColour: 'small white, easily missed',
    foliageColour: 'very dark glossy green',
    notes:
      'Slow, dense and permanent — the darkest evergreen in the British flora, and the best thing there is for winter structure in shade. Holly is dioecious: only female plants carry berries, and only with a male somewhere nearby, which is the single most common reason a holly never fruits.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Ilex%20aquifolium',
  },
  {
    id: 'magnolia-black-tulip',
    common: "Magnolia 'Black Tulip'",
    latin: "Magnolia 'Black Tulip'",
    genus: 'Magnolia',
    family: 'Magnoliaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 1.8,
    plantedSpread: 0.8,
    matureHeight: 5,
    matureSpread: 3,
    yearsToMature: 22,
    budBurst: 108,
    fullLeaf: 146,
    autumnStart: 272,
    leafFall: 312,
    flowerStart: 80,
    flowerEnd: 116,
    colors: {
      leafSpring: '#9ab060',
      leafSummer: '#4f7048',
      leafAutumn: '#c0a04a',
      flower: '#5a1f2e',
      flowerLate: '#7a3a48',
      bark: '#8a8378',
    },
    sun: ['full', 'dappled'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam'],
    drainage: ['retentive'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'deep burgundy, almost black',
    foliageColour: 'plain mid green',
    notes:
      'The darkest magnolia commonly available: six or eight big tulip-shaped flowers of burgundy so deep it reads black against a grey March sky, all on bare wood. Narrower and more upright than the saucer magnolia, so it fits a garden that could not take one. Like all of them it hates shallow chalk and resents root disturbance.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Magnolia%20Black%20Tulip',
  },
  {
    id: 'malus-red-sentinel',
    common: "Crab apple 'Red Sentinel'",
    latin: "Malus 'Red Sentinel'",
    genus: 'Malus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.2,
    plantedSpread: 1.0,
    matureHeight: 6,
    matureSpread: 5,
    yearsToMature: 22,
    budBurst: 92,
    fullLeaf: 128,
    autumnStart: 272,
    leafFall: 314,
    flowerStart: 116,
    flowerEnd: 142,
    fruitStart: 248,
    fruitEnd: 58,
    colors: {
      leafSpring: '#8fa860',
      leafSummer: '#4f7046',
      leafAutumn: '#d0a83a',
      flower: '#fbf4f0',
      fruit: '#a8161c',
      bark: '#6b5a48',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'white from pink buds',
    foliageColour: 'mid green, yellow in autumn',
    notes:
      'The best of the crabs for winter fruit: glossy deep red apples in dense bunches that hang on well past Christmas, often into February, because the birds leave them until everything else is gone. Blossom in May and a good pollinator for eating apples.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Malus%20Red%20Sentinel',
  },
  {
    id: 'malus-golden-hornet',
    common: "Crab apple 'Golden Hornet'",
    latin: "Malus x zumi 'Golden Hornet'",
    genus: 'Malus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.2,
    plantedSpread: 1.0,
    matureHeight: 6,
    matureSpread: 5,
    yearsToMature: 22,
    budBurst: 92,
    fullLeaf: 128,
    autumnStart: 272,
    leafFall: 314,
    flowerStart: 114,
    flowerEnd: 140,
    fruitStart: 246,
    fruitEnd: 40,
    colors: {
      leafSpring: '#8fa860',
      leafSummer: '#4f7046',
      leafAutumn: '#d0a83a',
      flower: '#fdfaf4',
      fruit: '#f0c22a',
      bark: '#6b5a48',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'white',
    foliageColour: 'mid green, yellow in autumn',
    notes:
      'Bright yellow crabs held in quantity from September, lighting up a bare tree through November and December. Less persistent than the red forms — birds take these earlier — but the colour against a low winter sun is worth it. Good for jelly.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Malus%20Golden%20Hornet',
  },
  {
    id: 'prunus-blireana',
    common: 'Double pink flowering plum',
    latin: 'Prunus x blireana',
    genus: 'Prunus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 1.8,
    plantedSpread: 0.9,
    matureHeight: 4,
    matureSpread: 3.5,
    yearsToMature: 18,
    budBurst: 96,
    fullLeaf: 132,
    autumnStart: 270,
    leafFall: 308,
    flowerStart: 76,
    flowerEnd: 108,
    colors: {
      leafSpring: '#8a4f5c',
      leafSummer: '#6b3f4f',
      leafAutumn: '#a8603a',
      flower: '#eda6bd',
      bark: '#5f4a42',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'double rose pink',
    foliageColour: 'coppery purple all summer',
    notes:
      'Fully double pink flowers smothering bare branches in late March, followed by purple-bronze leaves that hold their colour all season — two effects from a tree small enough for an ordinary garden. Rarely sets fruit.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Prunus%20blireana',
  },
  {
    id: 'prunus-avium',
    common: 'Wild cherry',
    latin: 'Prunus avium',
    genus: 'Prunus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.5,
    plantedSpread: 1.0,
    matureHeight: 16,
    matureSpread: 9,
    yearsToMature: 35,
    budBurst: 96,
    fullLeaf: 130,
    autumnStart: 262,
    leafFall: 304,
    flowerStart: 104,
    flowerEnd: 126,
    fruitStart: 182,
    fruitEnd: 218,
    colors: {
      leafSpring: '#a8b064',
      leafSummer: '#4f7046',
      leafAutumn: '#c85a2a',
      flower: '#fdfbf4',
      fruit: '#8a1a24',
      bark: '#7a4f42',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'large',
    flowerColour: 'white, in hanging clusters',
    foliageColour: 'mid green, orange-red in autumn',
    notes:
      'The native gean, and a full-sized forest tree — sixteen metres and more, so it belongs in a large garden or a boundary rather than a border. Sheets of white blossom in April, small dark cherries the birds strip in July, and reliable orange-scarlet autumn colour. Suckers freely from the roots.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Prunus%20avium',
  },
  {
    id: 'prunus-cerasus',
    common: 'Morello cherry',
    latin: 'Prunus cerasus',
    genus: 'Prunus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 1.6,
    plantedSpread: 0.9,
    matureHeight: 5,
    matureSpread: 4,
    yearsToMature: 18,
    budBurst: 98,
    fullLeaf: 132,
    autumnStart: 268,
    leafFall: 308,
    flowerStart: 106,
    flowerEnd: 130,
    fruitStart: 196,
    fruitEnd: 234,
    colors: {
      leafSpring: '#9ab064',
      leafSummer: '#4f7046',
      leafAutumn: '#c07a3a',
      flower: '#fdfbf4',
      fruit: '#5a1218',
      bark: '#7a5448',
    },
    sun: ['full', 'partial', 'shade'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'white',
    foliageColour: 'mid green',
    notes:
      'The acid cooking cherry, and the one fruit tree that genuinely crops on a north wall — self-fertile, and it fruits on the previous season\'s wood, so it is fan-trained and pruned quite differently from a sweet cherry. Too sour to eat raw, which is also why the birds leave some for you.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Prunus%20cerasus',
  },
  {
    id: 'prunus-merryweather',
    common: "Damson 'Merryweather'",
    latin: "Prunus domestica 'Merryweather'",
    genus: 'Prunus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 1.6,
    plantedSpread: 0.8,
    matureHeight: 4,
    matureSpread: 3.5,
    yearsToMature: 16,
    budBurst: 94,
    fullLeaf: 130,
    autumnStart: 268,
    leafFall: 306,
    flowerStart: 94,
    flowerEnd: 120,
    fruitStart: 232,
    fruitEnd: 272,
    colors: {
      leafSpring: '#9ab064',
      leafSummer: '#4f7046',
      leafAutumn: '#c8a03a',
      flower: '#fdfbf4',
      fruit: '#2f2a44',
      bark: '#6b5548',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive', 'free'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'white, early',
    foliageColour: 'mid green',
    notes:
      'A large-fruited damson, self-fertile and heavy-cropping, with blue-black plums in September that are far too sharp raw and excellent cooked. Blossoms early enough to be caught by a late frost in an exposed spot. On St Julien A rootstock it stays about four metres.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Prunus%20domestica%20Merryweather',
  },
  {
    id: 'carpinus-betulus',
    common: 'Hornbeam hedge',
    latin: 'Carpinus betulus',
    genus: 'Carpinus',
    family: 'Betulaceae',
    type: 'tree',
    habit: 'columnar',
    foliage: 'deciduous',
    clipped: true,
    annualGrowth: 0.35,
    plantedHeight: 1.0,
    plantedSpread: 0.4,
    matureHeight: 2.5,
    matureSpread: 1.0,
    yearsToMature: 12,
    budBurst: 104,
    fullLeaf: 138,
    autumnStart: 278,
    leafFall: 356,
    flowerStart: 108,
    flowerEnd: 130,
    colors: {
      leafSpring: '#a8c46a',
      leafSummer: '#4f7046',
      leafAutumn: '#b08a4a',
      flower: '#c0c47a',
      bark: '#8a8578',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'chalk'],
    drainage: ['retentive', 'waterlogged'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'green catkins',
    foliageColour: 'ribbed green, russet-brown all winter',
    notes:
      'Marcescent when clipped: the leaves die in October but stay on the plant until the new ones push them off in April, so a hornbeam hedge is a russet-brown screen all winter rather than a row of bare twigs. Preferred over beech on heavy or wet ground, where beech simply fails.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Carpinus%20betulus',
  },
  {
    id: 'fagus-sylvatica',
    common: 'Common beech',
    latin: 'Fagus sylvatica',
    genus: 'Fagus',
    family: 'Fagaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.5,
    plantedSpread: 1.0,
    matureHeight: 20,
    matureSpread: 15,
    yearsToMature: 60,
    budBurst: 110,
    fullLeaf: 138,
    autumnStart: 280,
    leafFall: 330,
    flowerStart: 112,
    flowerEnd: 132,
    fruitStart: 250,
    fruitEnd: 300,
    colors: {
      leafSpring: '#a8ce6a',
      leafSummer: '#3f6b3f',
      leafAutumn: '#b06a2a',
      flower: '#c0c47a',
      fruit: '#8a6a42',
      bark: '#9a978e',
    },
    sun: ['full', 'dappled'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'large',
    flowerColour: 'inconspicuous',
    foliageColour: 'silky lime green in spring, copper in autumn',
    notes:
      'A chalk-country tree, and one of the few big trees that is genuinely happier on thin alkaline soil than on rich ground — but it will not tolerate waterlogging at all, and dies slowly on heavy wet clay. Casts the densest shade of any British tree, so nothing much grows beneath it. As a clipped hedge it holds its brown leaves all winter.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Fagus%20sylvatica',
  },
  {
    id: 'fagus-sylvatica-purpurea',
    common: 'Copper beech',
    latin: "Fagus sylvatica f. purpurea",
    genus: 'Fagus',
    family: 'Fagaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.5,
    plantedSpread: 1.0,
    matureHeight: 20,
    matureSpread: 15,
    yearsToMature: 60,
    budBurst: 110,
    fullLeaf: 138,
    autumnStart: 280,
    leafFall: 330,
    flowerStart: 112,
    flowerEnd: 132,
    fruitStart: 250,
    fruitEnd: 300,
    colors: {
      leafSpring: '#8a4a4a',
      leafSummer: '#4f2632',
      leafAutumn: '#a0522a',
      flower: '#b8a87a',
      fruit: '#8a6a42',
      bark: '#9a978e',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'large',
    flowerColour: 'inconspicuous',
    foliageColour: 'deep purple-bronze all summer',
    notes:
      'The same enormous tree with dark purple leaves, and a decision that cannot be undone in a lifetime — a mature copper beech is a heavy, absorbing presence that dominates everything around it and casts shade the colour of a wet slate roof. Needs full sun to keep the colour; in shade it goes a muddy green-bronze.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Fagus%20sylvatica%20purpurea',
  },
  {
    id: 'malus-domestica-sunset',
    common: 'Apple',
    latin: "Malus domestica 'Sunset'",
    genus: 'Malus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2,
    plantedSpread: 1,
    matureHeight: 4.5,
    matureSpread: 4.5,
    yearsToMature: 12,
    budBurst: 95,
    fullLeaf: 130,
    autumnStart: 285,
    leafFall: 325,
    flowerStart: 110,
    flowerEnd: 136,
    fruitStart: 258,
    fruitEnd: 340,
    colors: {
      leafSpring: '#9dbd63',
      leafSummer: '#4f7a44',
      leafAutumn: '#c9a44a',
      flower: '#f6dfe4',
      fruit: '#d4543a',
      bark: '#6a5340',
    },
    sun: ['full', 'partial'],
    soilPh: ['neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'large',
    flowerColour: 'white flushed pink',
    foliageColour: 'mid green',
    notes:
      'The size given here is a garden tree on a semi-dwarfing rootstock, not the species figure — an apple is grafted, and the rootstock rather than the variety decides whether it finishes at three metres or twelve, which is the single most consequential thing to know before planting one. Blossom in late April and fruit hanging into November. Needs a pollination partner nearby, and will not thrive on very acid soil or shallow chalk.',
    source: 'https://www.rhs.org.uk/plants/56317/malus-domestica-sunset-d/details',
  },
  {
    id: 'crataegus-monogyna',
    common: 'Hawthorn hedge',
    latin: 'Crataegus monogyna',
    genus: 'Crataegus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'columnar',
    foliage: 'deciduous',
    clipped: true,
    annualGrowth: 0.4,
    plantedHeight: 0.6,
    plantedSpread: 0.3,
    matureHeight: 2.0,
    matureSpread: 0.9,
    yearsToMature: 8,
    budBurst: 88,
    fullLeaf: 120,
    autumnStart: 285,
    leafFall: 322,
    flowerStart: 130,
    flowerEnd: 152,
    fruitStart: 250,
    fruitEnd: 350,
    colors: {
      leafSpring: '#9dbf5c',
      leafSummer: '#4f7342',
      leafAutumn: '#b09050',
      flower: '#fbf6ec',
      fruit: '#a8231f',
      bark: '#7a6b5c',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'small',
    flowerColour: 'white, heavily scented, in May',
    foliageColour: 'small lobed mid green',
    notes:
      'The native field hedge, and the best thing here for wildlife — nesting cover, May blossom, and haws that carry into January. First into leaf of any hedge in this palette, often in March. The tension is that a hedge cut twice a year never flowers or fruits: cut it once, in late winter, and you get both.',
    source: 'https://www.rhs.org.uk/plants/4775/crataegus-monogyna/details',
  },
  {
    id: 'fagus-sylvatica-hedge',
    common: 'Beech hedge',
    latin: 'Fagus sylvatica',
    genus: 'Fagus',
    family: 'Fagaceae',
    type: 'tree',
    habit: 'columnar',
    foliage: 'deciduous',
    clipped: true,
    annualGrowth: 0.35,
    plantedHeight: 1.0,
    plantedSpread: 0.4,
    matureHeight: 2.5,
    matureSpread: 1.0,
    yearsToMature: 12,
    budBurst: 110,
    fullLeaf: 138,
    autumnStart: 280,
    leafFall: 356,
    flowerStart: 112,
    flowerEnd: 132,
    colors: {
      leafSpring: '#a8ce6a',
      leafSummer: '#3f6b3f',
      leafAutumn: '#b06a2a',
      flower: '#c0c47a',
      bark: '#9a978e',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'green catkins, lost to clipping',
    foliageColour: 'silky green, copper-brown all winter',
    notes:
      'Marcescent when clipped, like hornbeam: October leaves go copper and hang on until April pushes them off, so the hedge is a warm brown screen through winter rather than bare twigs. Kept as a separate entry from the beech tree because a 2.5 m hedge and a 20 m forest tree are not the same plant to design with. Needs drained ground — it fails on heavy wet clay where hornbeam thrives.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Fagus%20sylvatica',
  },
  {
    id: 'fagus-sylvatica-purpurea-hedge',
    common: 'Copper beech hedge',
    latin: 'Fagus sylvatica f. purpurea',
    genus: 'Fagus',
    family: 'Fagaceae',
    type: 'tree',
    habit: 'columnar',
    foliage: 'deciduous',
    clipped: true,
    annualGrowth: 0.32,
    plantedHeight: 1.0,
    plantedSpread: 0.4,
    matureHeight: 2.5,
    matureSpread: 1.0,
    yearsToMature: 12,
    budBurst: 110,
    fullLeaf: 138,
    autumnStart: 280,
    leafFall: 356,
    flowerStart: 112,
    flowerEnd: 132,
    colors: {
      leafSpring: '#8a4a4a',
      leafSummer: '#4f2632',
      leafAutumn: '#a0522a',
      flower: '#b8a87a',
      bark: '#9a978e',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'green catkins, lost to clipping',
    foliageColour: 'deep purple, copper-brown all winter',
    notes:
      'The same hedge as green beech and the same winter copper, but the summer is deep purple rather than green — heavy enough that a long run of it can dominate a garden, and best used where something needs stopping rather than continuing. Slightly slower than the green form. Wants sun to hold the colour, and drained ground like its parent.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Fagus%20sylvatica%20purpurea',
  },
  {
    id: 'trachycarpus-fortunei',
    common: 'Chusan palm',
    latin: 'Trachycarpus fortunei',
    genus: 'Trachycarpus',
    family: 'Arecaceae',
    type: 'tree',
    habit: 'treefern',
    foliage: 'evergreen',
    plantedHeight: 1.2,
    plantedSpread: 1.0,
    matureHeight: 6.0,
    matureSpread: 2.5,
    yearsToMature: 30,
    budBurst: 110,
    fullLeaf: 155,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 140,
    flowerEnd: 170,
    colors: {
      leafSpring: '#7fa860',
      leafSummer: '#3f6b46',
      leafAutumn: '#48744d',
      flower: '#e6d874',
      bark: '#8a7258',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'large yellow sprays in early summer',
    foliageColour: 'stiff, pleated, fan-shaped green',
    notes:
      'The one palm that is genuinely hardy across most of Britain, and the fastest way to make a garden not look British. Slow — a metre of trunk takes several years — with a fibrous brown trunk that stays shaggy unless you strip it. The leaves shred in wind, which is cosmetic rather than fatal, but a windy site will keep it looking tattered.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Trachycarpus%20fortunei',
  },
  {
    id: 'quercus-robur',
    common: 'English oak',
    latin: 'Quercus robur',
    genus: 'Quercus',
    family: 'Fagaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.5,
    plantedSpread: 1.2,
    matureHeight: 22.0,
    matureSpread: 18.0,
    yearsToMature: 60,
    budBurst: 118,
    fullLeaf: 145,
    autumnStart: 285,
    leafFall: 335,
    flowerStart: 120,
    flowerEnd: 140,
    fruitStart: 250,
    fruitEnd: 300,
    colors: {
      leafSpring: '#b8c46a',
      leafSummer: '#4f6f3f',
      leafAutumn: '#9a7f42',
      flower: '#c4c47a',
      fruit: '#8a6a3a',
      bark: '#6f6558',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'large',
    flowerColour: 'green catkins',
    foliageColour: 'lobed mid green, dull yellow-brown in autumn',
    notes:
      'The native oak, and another honest warning: only for a garden measured in acres. Late into leaf — often not until mid-May — and it casts the heaviest shade of any tree here, with a root plate to match. Supports more wildlife than any other British tree by a wide margin. Autumn colour is a dull yellow-brown, not a display.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Quercus%20robur',
  },
  {
    id: 'tilia-cordata',
    common: 'Small-leaved lime',
    latin: 'Tilia cordata',
    genus: 'Tilia',
    family: 'Malvaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    clipped: true,
    annualGrowth: 0.45,
    plantedHeight: 2.5,
    plantedSpread: 1.0,
    matureHeight: 5.0,
    matureSpread: 3.0,
    yearsToMature: 15,
    budBurst: 100,
    fullLeaf: 132,
    autumnStart: 270,
    leafFall: 315,
    flowerStart: 180,
    flowerEnd: 200,
    colors: {
      leafSpring: '#a8ce62',
      leafSummer: '#4a7040',
      leafAutumn: '#d8c04a',
      flower: '#e2dc9a',
      bark: '#7a7266',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'pale yellow, heavily scented in July',
    foliageColour: 'neat heart-shaped green, clear yellow in autumn',
    notes:
      'Modelled as a pleached tree rather than the forty-metre forest species, because that is what a garden designer specifies: a clear stem with a clipped rectangle of foliage on top, used as a hedge on legs to screen at first-floor height. Chosen over the common lime because it does not produce the sticky aphid honeydew that makes limes notorious over a parking space.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Tilia%20cordata',
  },
  {
    id: 'pyrus-chanticleer',
    common: 'Ornamental pear',
    latin: "Pyrus calleryana 'Chanticleer'",
    genus: 'Pyrus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'columnar',
    foliage: 'deciduous',
    plantedHeight: 2.5,
    plantedSpread: 0.8,
    matureHeight: 9.0,
    matureSpread: 4.0,
    yearsToMature: 25,
    budBurst: 88,
    fullLeaf: 118,
    autumnStart: 285,
    leafFall: 340,
    flowerStart: 100,
    flowerEnd: 122,
    colors: {
      leafSpring: '#8fc05a',
      leafSummer: '#39633c',
      leafAutumn: '#a83a52',
      flower: '#fbfaf2',
      bark: '#6f6558',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'white blossom in April',
    foliageColour: 'glossy green, plum-red very late in autumn',
    notes:
      'The standard tree for a difficult urban site: narrow, tolerant of pollution, wind and compacted ground, and neat enough for a front garden or a street. White blossom in April, then glossy leaves that hang on until December and turn plum-red weeks after everything else has finished. No useful fruit, which is the point.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Pyrus%20calleryana%20Chanticleer',
  },
  {
    id: 'cercis-forest-pansy',
    common: 'Eastern redbud',
    latin: "Cercis canadensis 'Forest Pansy'",
    genus: 'Cercis',
    family: 'Fabaceae',
    type: 'tree',
    habit: 'multistem',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 1.5,
    plantedSpread: 1.0,
    matureHeight: 6.0,
    matureSpread: 5.0,
    yearsToMature: 20,
    budBurst: 112,
    fullLeaf: 140,
    autumnStart: 268,
    leafFall: 310,
    flowerStart: 96,
    flowerEnd: 120,
    colors: {
      leafSpring: '#7a2a4a',
      leafSummer: '#5a2440',
      leafAutumn: '#c8663a',
      flower: '#c8508a',
      bark: '#6f5a4e',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'magenta-pink, straight out of the bare bark',
    foliageColour: 'deep wine-purple hearts, scarlet-orange in autumn',
    notes:
      'Flowers directly out of the bare branches and even the trunk in April, before any leaf, then opens huge heart-shaped leaves of deep wine-purple that go orange-scarlet in October. Best as a multistem. Hates being moved and resents cold wet feet, so plant it small, in a sheltered spot, and leave it alone.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Cercis%20canadensis%20Forest%20Pansy',
  },
  {
    id: 'parrotia-persica',
    common: 'Persian ironwood',
    latin: 'Parrotia persica',
    genus: 'Parrotia',
    family: 'Hamamelidaceae',
    type: 'tree',
    habit: 'multistem',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 1.8,
    plantedSpread: 1.2,
    matureHeight: 8.0,
    matureSpread: 8.0,
    yearsToMature: 30,
    budBurst: 105,
    fullLeaf: 135,
    autumnStart: 262,
    leafFall: 320,
    flowerStart: 32,
    flowerEnd: 68,
    colors: {
      leafSpring: '#8fbb58',
      leafSummer: '#42703f',
      leafAutumn: '#c8442a',
      flower: '#a82a24',
      bark: '#9a8e80',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'large',
    flowerColour: 'small crimson tufts on bare wood in February',
    foliageColour: 'green, then crimson, orange and gold together',
    notes:
      'The best autumn colour of any tree here, and it does not do it all at once — crimson, orange and gold appear on the same tree for weeks. Small red tufts on bare branches in February are a quiet bonus. Wider than it is tall in the end, and the flaking grey, fawn and green bark is worth the space on its own.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Parrotia%20persica',
  },
  {
    id: 'liquidambar-worplesdon',
    common: 'Sweet gum',
    latin: "Liquidambar styraciflua 'Worplesdon'",
    genus: 'Liquidambar',
    family: 'Altingiaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.5,
    plantedSpread: 1.0,
    matureHeight: 15.0,
    matureSpread: 8.0,
    yearsToMature: 35,
    budBurst: 108,
    fullLeaf: 140,
    autumnStart: 268,
    leafFall: 330,
    flowerStart: 118,
    flowerEnd: 138,
    colors: {
      leafSpring: '#8fc05e',
      leafSummer: '#3a6b3c',
      leafAutumn: '#8a2a5a',
      flower: '#a8b46a',
      bark: '#6f6558',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'large',
    flowerColour: 'insignificant green',
    foliageColour: 'maple-like glossy green, purple and orange in autumn',
    notes:
      'Leaves like a maple and colour like nothing else — purple, plum and orange all at once, and this cultivar is the one chosen because it colours reliably in a British autumn where seedlings often just go brown. Needs neutral to acid soil; on chalk it yellows and sulks. Big eventually, and upright while young.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Liquidambar%20styraciflua%20Worplesdon',
  },
  {
    id: 'gleditsia-sunburst',
    common: 'Honey locust',
    latin: "Gleditsia triacanthos 'Sunburst'",
    genus: 'Gleditsia',
    family: 'Fabaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    plantedHeight: 2.5,
    plantedSpread: 1.2,
    matureHeight: 10.0,
    matureSpread: 8.0,
    yearsToMature: 28,
    budBurst: 122,
    fullLeaf: 148,
    autumnStart: 272,
    leafFall: 310,
    flowerStart: 150,
    flowerEnd: 170,
    colors: {
      leafSpring: '#e2d84a',
      leafSummer: '#a8be52',
      leafAutumn: '#e8c840',
      flower: '#d8dca8',
      bark: '#6f6052',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H6',
    sizeClass: 'large',
    flowerColour: 'insignificant green-white',
    foliageColour: 'bright gold in spring, cooling to lime',
    notes:
      'Golden in spring, lime through summer, gold again in autumn, and the whole thing so finely divided that it casts almost no shade — you can plant underneath it, which is true of nothing else this size. Thornless and pod-free, unlike the species. Very late into leaf, so it looks dead until the end of May.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Gleditsia%20triacanthos%20Sunburst',
  },
  {
    id: 'cornus-kousa-chinensis',
    common: 'Chinese dogwood',
    latin: 'Cornus kousa var. chinensis',
    genus: 'Cornus',
    family: 'Cornaceae',
    type: 'tree',
    habit: 'multistem',
    foliage: 'deciduous',
    plantedHeight: 1.5,
    plantedSpread: 1.0,
    matureHeight: 6.0,
    matureSpread: 5.0,
    yearsToMature: 25,
    budBurst: 108,
    fullLeaf: 138,
    autumnStart: 266,
    leafFall: 312,
    flowerStart: 152,
    flowerEnd: 190,
    fruitStart: 250,
    fruitEnd: 292,
    colors: {
      leafSpring: '#8fbb5a',
      leafSummer: '#3f6b40',
      leafAutumn: '#b03a2e',
      flower: '#f8f6ea',
      flowerLate: '#f0d8d8',
      fruit: '#c8402a',
      bark: '#8a7a68',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral'],
    soilType: ['clay', 'loam', 'sand'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'white bracts in June, ageing pink',
    foliageColour: 'green, deep crimson in autumn',
    notes:
      'Held in tiers, and covered in June with white bracts that sit on top of the branches so the whole tree reads as a layered white cloud from above. The bracts age pink over several weeks. Strawberry-like red fruit follows, then crimson autumn colour. Wants neutral to acid soil and shelter from cold wind while young.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Cornus%20kousa%20chinensis',
  },
  {
    id: 'prunus-cerasifera-nigra',
    common: 'Purple-leaf cherry plum',
    latin: "Prunus cerasifera 'Nigra'",
    genus: 'Prunus',
    family: 'Rosaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    flowersOnBareWood: true,
    plantedHeight: 2.0,
    plantedSpread: 1.0,
    matureHeight: 8.0,
    matureSpread: 7.0,
    yearsToMature: 22,
    budBurst: 78,
    fullLeaf: 112,
    autumnStart: 276,
    leafFall: 318,
    flowerStart: 58,
    flowerEnd: 88,
    colors: {
      leafSpring: '#8a3a52',
      leafSummer: '#4a2030',
      leafAutumn: '#8a4030',
      flower: '#f0b0c4',
      bark: '#5f4a44',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'medium',
    flowerColour: 'soft pink, on bare black twigs in late February',
    foliageColour: 'deep blackish-purple all summer',
    notes:
      'The first tree of the year in most streets: pale pink blossom on bare black twigs in late February, weeks before anything else. Then deep purple leaves right through to leaf fall, which is either the point of it or too much, depending on the garden. Also used clipped as a purple hedge. Tolerant of almost any soil.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Prunus%20cerasifera%20Nigra',
  },
  {
    id: 'arbutus-unedo',
    common: 'Strawberry tree',
    latin: 'Arbutus unedo',
    genus: 'Arbutus',
    family: 'Ericaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'evergreen',
    plantedHeight: 1.2,
    plantedSpread: 0.8,
    matureHeight: 6.0,
    matureSpread: 5.0,
    yearsToMature: 30,
    budBurst: 108,
    fullLeaf: 152,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 288,
    flowerEnd: 335,
    fruitStart: 288,
    fruitEnd: 340,
    colors: {
      leafSpring: '#7fa855',
      leafSummer: '#31563a',
      leafAutumn: '#395e40',
      flower: '#f4f0e6',
      fruit: '#d8481e',
      bark: '#a04a32',
    },
    sun: ['full', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H5',
    sizeClass: 'medium',
    flowerColour: 'ivory bells in autumn, alongside the fruit',
    foliageColour: 'glossy dark green on shredding red bark',
    notes:
      'Carries flowers and fruit at the same time, in November, which almost nothing else does — ivory bells hanging beside the previous year’s scarlet strawberries. Add peeling cinnamon-red bark and evergreen leaves and it earns its space three times over. Unusually among the heather family it is happy on chalk.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Arbutus%20unedo',
  },
  {
    id: 'ginkgo-biloba',
    common: 'Maidenhair tree',
    latin: 'Ginkgo biloba',
    genus: 'Ginkgo',
    family: 'Ginkgoaceae',
    type: 'tree',
    habit: 'columnar',
    foliage: 'deciduous',
    plantedHeight: 2.0,
    plantedSpread: 0.6,
    matureHeight: 15.0,
    matureSpread: 7.0,
    yearsToMature: 45,
    budBurst: 112,
    fullLeaf: 142,
    autumnStart: 285,
    leafFall: 318,
    flowerStart: 115,
    flowerEnd: 132,
    colors: {
      leafSpring: '#a8c86a',
      leafSummer: '#5f8a4a',
      leafAutumn: '#f0c81e',
      flower: '#c4c88a',
      bark: '#7a6f60',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H6',
    sizeClass: 'large',
    flowerColour: 'insignificant green',
    foliageColour: 'fan-shaped, turning pure butter yellow',
    notes:
      'A living fossil, unchanged for two hundred million years, with fan-shaped leaves unlike anything else and a butter-yellow autumn so pure it looks artificial — and it drops the entire canopy within a few days of turning. Bombproof in city pollution. Buy a named male: female trees produce fruit that smells strongly of vomit.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Ginkgo%20biloba',
  },
  {
    id: 'olea-europaea',
    common: 'Olive',
    latin: 'Olea europaea',
    genus: 'Olea',
    family: 'Oleaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'evergreen',
    plantedHeight: 1.5,
    plantedSpread: 1.0,
    matureHeight: 4.5,
    matureSpread: 4.0,
    yearsToMature: 25,
    budBurst: 112,
    fullLeaf: 155,
    autumnStart: 300,
    leafFall: 345,
    flowerStart: 152,
    flowerEnd: 180,
    colors: {
      leafSpring: '#a8b898',
      leafSummer: '#8a9c82',
      leafAutumn: '#90a288',
      flower: '#f0eede',
      bark: '#9a9184',
    },
    sun: ['full'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['loam', 'sand', 'chalk'],
    drainage: ['free'],
    hardiness: 'H4',
    sizeClass: 'medium',
    flowerColour: 'tiny cream, barely noticed',
    foliageColour: 'narrow grey-green, silver underneath',
    notes:
      'Grey-green above and silver beneath, so the whole tree changes colour as the wind turns it — the reason to plant one, since fruit in Britain is a rarity rather than a crop. H4 is the honest warning: it survives cold far better than it survives cold wet roots, so sharp drainage matters more than shelter. Southern gardens and pots.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Olea%20europaea',
  },
  {
    id: 'acer-campestre',
    common: 'Field maple',
    latin: 'Acer campestre',
    genus: 'Acer',
    family: 'Sapindaceae',
    type: 'tree',
    habit: 'round',
    foliage: 'deciduous',
    clipped: true,
    annualGrowth: 0.35,
    plantedHeight: 1.0,
    plantedSpread: 0.5,
    matureHeight: 2.5,
    matureSpread: 1.0,
    yearsToMature: 12,
    budBurst: 100,
    fullLeaf: 132,
    autumnStart: 272,
    leafFall: 318,
    flowerStart: 118,
    flowerEnd: 138,
    colors: {
      leafSpring: '#a8c46a',
      leafSummer: '#4a7042',
      leafAutumn: '#e8c020',
      flower: '#c0c47a',
      bark: '#8a7f6e',
    },
    sun: ['full', 'dappled', 'partial'],
    soilPh: ['acidic', 'neutral', 'alkaline'],
    soilType: ['clay', 'loam', 'sand', 'chalk'],
    drainage: ['free', 'retentive'],
    hardiness: 'H7',
    sizeClass: 'medium',
    flowerColour: 'small green, insignificant',
    foliageColour: 'neat lobed green, clear butter yellow in autumn',
    notes:
      'Our only native maple, modelled here as the clipped hedge it is most often specified as rather than the fifteen-metre tree it becomes — it mixes into a native hedge with hawthorn and takes chalk and clay equally. Butter-yellow in autumn, which is unusually good colour for a hedging plant.',
    source: 'https://www.rhs.org.uk/plants/search-results?query=Acer%20campestre',
  },
];
